#!/usr/bin/env node
'use strict';
// CI browser acceptance of actual assembled, INACTIVE usage pages.
// No response fulfilment, fake totals, live sign-in, event write or runtime patch.
const {chromium}=require('playwright');
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const assert=require('node:assert/strict');
const education=new URL(process.env.MBM_EDUCATION_ORIGIN||'http://127.0.0.1:4173').origin;
const play=new URL(process.env.MBM_PLAY_ORIGIN||'http://127.0.0.1:4174').origin;
const output=path.resolve(process.env.MBM_USAGE_OUTPUT||'audit-output/usage-discovery');
const lessons=path.resolve(process.env.MBM_USAGE_LESSONS_SOURCE||'.sources/Lessons');
const hub='/Lessons/Humanities_Teesside/David_Cover_Autumn1_W3-W7/index.html';
const lesson='/Lessons/Humanities_Teesside/David_Cover_Autumn1_W3-W7/BH_W3.html';
const zip='David_BUILD_Humanities_RE_Pack.zip';
const widths=[390,1280];
const report={schema:1,scope:'Actual inactive assembled UI; genuine signed-in ordinary-user denial is a separate backend/live activation acceptance',education,play,startedAt:new Date().toISOString(),cases:[],pageErrors:[],providerRequests:[],downloads:[],fatal:null};
fs.mkdirSync(output,{recursive:true});
function provider(url){const value=new URL(url);return /(?:^|\.)(?:supabase\.co|goatcounter\.com|counterapi\.dev)$/.test(value.hostname)||/\/functions\/v1\/(?:usage-ingest|usage-public|owner-usage)(?:\/|$)/.test(value.pathname);}
function urlFor(route,origin=education){return new URL(route,origin).href;}
async function check(name,page,action){const row={name,ok:false};report.cases.push(row);try{row.evidence=await action();row.ok=true;}catch(error){row.error=error.stack||String(error);if(page&&!page.isClosed())try{row.screenshot=await shot(page,'FAIL-'+name);}catch(_){}}console.log(`${row.ok?'PASS':'FAIL'} ${name}`);}
async function shot(page,name,fullPage=false){const file=name.replace(/[^\w.-]/g,'-')+'.png';await page.screenshot({path:path.join(output,file),animations:'disabled',fullPage});return file;}
async function responsive(page){const sizes=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));assert(sizes.scroll<=sizes.width+1,`Horizontal overflow: ${JSON.stringify(sizes)}`);return sizes;}
async function target(locator){await locator.scrollIntoViewIfNeeded();const size=await locator.evaluate(el=>{const r=el.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{width:r.width,height:r.height,left:r.left,right:r.right,viewport:innerWidth,uncovered:!!hit&&(hit===el||el.contains(hit))};});assert(size.width>=43.5&&size.height>=43.5,`Touch target too small: ${JSON.stringify(size)}`);assert(size.left>=-.5&&size.right<=size.viewport+.5&&size.uncovered,`Control clipped/covered: ${JSON.stringify(size)}`);return size;}
async function goto(page,route,origin=education){const response=await page.goto(urlFor(route,origin),{waitUntil:'networkidle'});assert.equal(response.status(),200,route);await responsive(page);return response;}
async function clientReady(page){await page.waitForFunction(()=>!!window.MBMUsage);const config=await page.evaluate(()=>window.MBMUsage.ready);assert.equal(config?.enabled,false,'Inactive acceptance must run against an honestly disabled service');return config;}
async function newContext(browser,width,origins=[]){const context=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce',acceptDownloads:true,storageState:{cookies:[],origins}});await context.route('**/*',route=>{if(provider(route.request().url()))return route.abort('blockedbyclient');return route.continue();});context.on('request',request=>{if(provider(request.url())){const url=new URL(request.url());report.providerRequests.push({origin:url.origin,path:url.pathname,method:request.method()});}});context.on('page',page=>{page.on('pageerror',error=>report.pageErrors.push({origin:new URL(page.url()).origin,path:new URL(page.url()).pathname,message:error.message}));});return context;}
async function choices(page,width,prefix){const panel=page.locator('#usage-statistics');await panel.locator('summary').click();assert(await panel.getAttribute('open')!==null);const allow=panel.getByRole('button',{name:'Allow optional statistics',exact:true});const deny=panel.getByRole('button',{name:'Keep statistics off',exact:true});assert(await allow.isDisabled());assert(!(await deny.isDisabled()));await target(deny);await deny.click();assert.equal(await deny.getAttribute('aria-pressed'),'true');assert.match(await panel.locator('[data-usage-choice-status]').innerText(),/not active|unavailable/i);const screenshot=await shot(page,`${width}-${prefix}-choices`);await page.reload({waitUntil:'networkidle'});await clientReady(page);await page.locator('#usage-statistics summary').click();assert.equal(await page.locator('[data-usage-choice="deny"]').getAttribute('aria-pressed'),'true');return{screenshot,refusalPersists:true};}
async function download(page,width){await goto(page,hub);await clientReady(page);const link=page.locator(`a[href="${zip}"]`);assert.equal((await link.innerText()).trim(),'Download BUILD pack','Inactive service must preserve the actual download action label');assert.equal(await page.locator('.usage-resource-count').count(),0,'Inactive counters belong on the statistics page, not on download controls');await target(link);const screenshot=await shot(page,`${width}-download-requests-inactive`);const [file]=await Promise.all([page.waitForEvent('download'),link.click()]);assert.equal(await file.failure(),null);const downloaded=fs.readFileSync(await file.path());const original=fs.readFileSync(path.join(lessons,'Humanities_Teesside/David_Cover_Autumn1_W3-W7',zip));assert.deepEqual(downloaded,original,'A real selected download must retain exact completed pack bytes');const evidence={route:hub.replace(/index\.html$/,'')+zip,bytes:downloaded.length,sha256:crypto.createHash('sha256').update(downloaded).digest('hex'),screenshot};report.downloads.push(evidence);await file.delete();return evidence;}
(async()=>{let browser;try{
 browser=await chromium.launch({headless:true});
 const request=await browser.newContext();
 await check('assembled-configuration-is-inactive-on-both-origins',null,async()=>{const evidence=[];for(const origin of [education,play]){const response=await request.request.get(urlFor('/data/usage-config.json',origin));assert.equal(response.status(),200);const cfg=await response.json();assert.equal(cfg.enabled,false);assert.equal(cfg.geography_enabled,false);assert.equal(cfg.default_choice,'off');evidence.push({origin,source:cfg.source,enabled:cfg.enabled,geography:cfg.geography_enabled});}return evidence;});await request.close();
 for(const width of widths){const context=await newContext(browser,width);const page=await context.newPage();page.setDefaultTimeout(12000);
  await check(`${width}-education-two-learning-top10-lists`,page,async()=>{await goto(page,'/stats/');await clientReady(page);assert.equal(await page.locator('[data-usage-list="games"]').count(),0);for(const kind of ['lessons','packs']){const list=page.locator(`[data-usage-list="${kind}"]`);assert.equal(await list.count(),1);assert.equal(await list.locator('li').count(),0);assert.match(await list.innerText(),/not active|unavailable/i);}assert.equal(await page.getByRole('heading',{name:'Top 10 lesson packs',exact:true}).count(),1);const select=page.locator('[data-usage-period]');await target(select);await select.selectOption('alltime');assert.match(await page.locator('[data-usage-measured-since]').innerText(),/not active|unavailable/i);assert.equal(await page.locator('[data-usage-popularity] ol li').count(),0);return{screenshot:await shot(page,`${width}-education-top10`,true),periods:['last30days','alltime'],rankedRows:0};});
  await check(`${width}-play-top10-keeps-games-separate`,page,async()=>{await goto(page,'/stats/',play);await clientReady(page);assert.equal(await page.locator('[data-usage-list="games"]').count(),1);assert.equal(await page.locator('[data-usage-list="lessons"], [data-usage-list="packs"]').count(),0);assert.equal(await page.locator('[data-usage-list="games"] li').count(),0);await page.locator('[data-usage-period]').selectOption('alltime');assert.match(await page.locator('[data-usage-list="games"]').innerText(),/not active|unavailable/i);return{screenshot:await shot(page,`${width}-play-top10`,true),rankedRows:0};});
  await check(`${width}-education-privacy-and-free-refusal`,page,async()=>{await goto(page,'/privacy/#shared-usage');await clientReady(page);const notice=page.locator('#shared-usage');assert.match(await notice.innerText(),/off by default/i);assert.match(await notice.innerText(),/IP address/);assert.match(await notice.innerText(),/Country and UK-region collection is off/);assert.match(await notice.innerText(),/searches, full URLs/);const noticeShot=await shot(page,`${width}-education-privacy`);return{noticeShot,...await choices(page,width,'education')};});
  await check(`${width}-play-choice-is-separate-and-visible`,page,async()=>{await goto(page,'/privacy/',play);await clientReady(page);await page.locator('#usage-statistics summary').click();assert.equal(await page.locator('[data-usage-choice="deny"]').getAttribute('aria-pressed'),'false','Education preference must not identify or configure the separate Play browser origin');await page.locator('#usage-statistics summary').click();const evidence=await choices(page,width,'play');assert.match(await page.locator('#shared-usage').innerText(),/Country and UK-region collection is off/);return evidence;});
  await check(`${width}-owner-dashboard-inactive-and-locked`,page,async()=>{await goto(page,'/owner/stats/');await clientReady(page);await page.waitForFunction(()=>/not active/.test(document.querySelector('[data-owner-status]')?.textContent||''));assert(await page.locator('[data-owner-load]').isDisabled());assert(await page.locator('[data-owner-export]').isDisabled());assert(!(await page.locator('[data-owner-content]').isVisible()));assert.equal(await page.locator('[data-owner-content]').innerText(),'');assert.equal(await page.locator('input[type="password"]').count(),0);const account=page.getByRole('link',{name:'Open your existing account sign-in',exact:true});assert.equal(await account.getAttribute('href'),'/account/');await page.locator('[data-owner-source]').selectOption('play');await page.locator('[data-owner-period]').selectOption('alltime');assert(await page.locator('[data-owner-load]').isDisabled());assert(!(await page.locator('[data-owner-content]').isVisible()));return{screenshot:await shot(page,`${width}-owner-locked`,true),newAccountForm:false,privateFiguresVisible:false};});
  await check(`${width}-real-pack-download-still-works`,page,()=>download(page,width));
  await check(`${width}-completed-lesson-opens-without-statistics`,page,async()=>{await page.locator('a[href="BH_W3.html"]').first().click();await page.waitForURL(url=>url.pathname===lesson);await clientReady(page);assert(await page.getByRole('heading',{name:'Places and their jobs',exact:true}).first().isVisible());await responsive(page);assert.equal(await page.locator('script[src="/assets/usage-client.js"]').count(),1);return{route:new URL(page.url()).pathname,screenshot:await shot(page,`${width}-completed-lesson`)};});
  await context.close();
 }
 const stored=[{origin:education,localStorage:[{name:'mbm_usage_choice_v1',value:'allow'},{name:'mbm_cloud_identity_v1',value:JSON.stringify({id:'ordinary-fixture',email:'ordinary-fixture@example.invalid',cloud:true,offlineHint:true})}]},{origin:play,localStorage:[{name:'mbm_usage_choice_v1',value:'allow'}]}];
 const fixture=await newContext(browser,390,stored),page=await fixture.newPage();
 await check('stored-opt-in-does-not-activate-disabled-education-or-play',page,async()=>{for(const [origin,route] of [[education,lesson],[play,'/stats/']]){await goto(page,route,origin);await clientReady(page);assert.equal(await page.evaluate(()=>localStorage.getItem('mbm_usage_choice_v1')),'allow');}return{origins:2,storedChoice:'allow',providerCalls:report.providerRequests.length};});
 await check('local-account-hint-cannot-unlock-inactive-owner-dashboard',page,async()=>{await goto(page,'/owner/stats/');await clientReady(page);assert(await page.locator('[data-owner-load]').isDisabled());assert(!(await page.locator('[data-owner-content]').isVisible()));assert.equal(await page.locator('[data-owner-content]').innerText(),'');return{fixture:'non-authenticating offline identity hint only',privateFiguresVisible:false,screenshot:await shot(page,'390-owner-local-hint-locked')};});
 await fixture.close();
 await check('no-provider-requests-and-no-browser-errors',null,async()=>{assert.deepEqual(report.providerRequests,[],'Inactive usage must not make an analytics or owner provider request, even if a previous choice allowed it');assert.deepEqual(report.pageErrors,[]);return{providerRequests:0,pageErrors:0};});
 }catch(error){report.fatal=error.stack||String(error);}finally{if(browser)await browser.close();report.passed=report.cases.filter(row=>row.ok).length;report.failed=report.cases.length-report.passed;report.result=report.failed||report.fatal?'FAIL':'PASS';report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(output,'usage-discovery.json'),JSON.stringify(report,null,2)+'\n');console.log(`${report.result}: ${report.passed}/${report.cases.length} inactive usage browser checks; ${report.providerRequests.length} provider requests.`);if(report.result!=='PASS'){console.error(report.fatal||report.cases.filter(row=>!row.ok).map(row=>row.name+': '+row.error).join('\n'));process.exitCode=1;}}
})();
