// Offline controls only. No test event is sent to a deployed service.
const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const crypto=require('node:crypto');const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'usage-client.js'),'utf8');
const lessonId='a'.repeat(64),downloadId='b'.repeat(64),gameId='c'.repeat(64);
const registry=[{source:'education',resource_id:lessonId,route:'/Lessons/test.html',title:'Test lesson',kind:'lesson',event_types:['lesson_open']},{source:'education',resource_id:downloadId,route:'/Lessons/pack.zip',title:'Test pack',kind:'pack',event_types:['download_request']},{source:'play',resource_id:gameId,route:'/game/',title:'Test game',kind:'game',event_types:['game_launch']}];
function make({enabled=true,choice='unset',privacy=false,webdriver=false,locationHref='https://madebymatt.uk/Lessons/test.html?q=pupil-name&email=private#work',failPublic=false,showDownloadLink=false,resourceCount=null}={}){
  const local=new Map(choice==='unset'?[]:[['mbm_usage_choice_v1',choice]]),calls=[],listeners={};
  const downloadLink={textContent:'Download real pack',siblings:[],getAttribute:()=>'/Lessons/pack.zip',insertAdjacentElement:(_position,label)=>downloadLink.siblings.push(label)};
  const location=new URL(locationHref),document={body:{},createElement:()=>({textContent:''}),querySelectorAll:selector=>showDownloadLink&&selector==='a[href]'?[downloadLink]:[],addEventListener:(name,fn)=>{(listeners[name]??=[]).push(fn);}};
  const window={location,crypto,localStorage:{getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v)},addEventListener:()=>{}};
  const config={schema:1,enabled,source:'education',service_origin:'https://example.supabase.co',allowed_origins:['https://madebymatt.uk']};
  function fetch(url,options={}){
    calls.push({url,options});if(url==='/data/usage-config.json')return Promise.resolve({ok:true,json:()=>Promise.resolve(config)});
    if(url==='/data/usage-registry.json')return Promise.resolve({ok:true,json:()=>Promise.resolve(registry)});
    if(url.includes('usage-public'))return failPublic?Promise.reject(new Error('offline')):Promise.resolve({ok:true,json:()=>Promise.resolve({schema:1,source:'education',enabled:true,resources:resourceCount===null?[]:[{resource_id:downloadId,event_type:'download_request',alltime:resourceCount,last30days:resourceCount}],windows:{last30days:{top:{lessons:[],packs:[],games:[]}},alltime:{top:{lessons:[],packs:[],games:[]}}}})});
    return Promise.resolve({ok:true,json:()=>Promise.resolve({ok:true,counted:true})});
  }
  vm.runInNewContext(source,{window,document,location,navigator:{globalPrivacyControl:privacy,webdriver,onLine:true},fetch,URL,Promise,Map,Set,Array,JSON,Number,Date,AbortController,setTimeout,clearTimeout,MutationObserver:class{observe(){}}});
  function click(href){const link={getAttribute:()=>href};const target={closest:selector=>selector==='a[href]'?link:null};(listeners.click||[]).forEach(fn=>fn({target,button:0,defaultPrevented:false}));}
  return {window,calls,local,click,downloadLink,posts:()=>calls.filter(c=>c.url.includes('usage-ingest'))};
}
(async()=>{
 let cases=0;async function run(name,fn){await fn();cases++;process.stdout.write('PASS '+name+'\n');}
 await run('disabled feature makes no provider request even with stored allow',async()=>{const x=make({enabled:false,choice:'allow'});await x.window.MBMUsage.ready;x.click('/Lessons/pack.zip');assert.equal(x.calls.filter(c=>c.url.startsWith('https:')).length,0);});
 await run('default opt-out allows resources without recording',async()=>{const x=make();await x.window.MBMUsage.ready;x.click('/Lessons/pack.zip');x.click('https://www.madebymatt-play.uk/game/');assert.equal(x.posts().length,0);});
 await run('real destination lesson opening sends only strict anonymous payload',async()=>{const x=make({choice:'allow'});await x.window.MBMUsage.ready;assert.equal(x.posts().length,1);const call=x.posts()[0],body=JSON.parse(call.options.body);assert.deepEqual(Object.keys(body).sort(),['event_nonce','event_type','resource_id','source']);assert.equal(body.resource_id,lessonId);assert.equal(body.event_type,'lesson_open');assert.equal(call.options.credentials,'omit');assert.equal(call.options.referrerPolicy,'no-referrer');assert.equal(call.options.keepalive,true);assert.deepEqual(Object.keys(call.options.headers),['Content-Type']);assert(!call.options.body.includes('pupil'));assert(!call.options.body.includes('private'));assert.match(body.event_nonce,/^[\da-f-]{36}$/);assert.deepEqual([...x.local.keys()],['mbm_usage_choice_v1']);});
 await run('lesson link click is not counted again at source',async()=>{const x=make({choice:'allow'});await x.window.MBMUsage.ready;x.click('/Lessons/test.html');assert.equal(x.posts().length,1);});
 await run('downloads record one request per item per page and omit URL parameters',async()=>{const x=make({choice:'allow'});await x.window.MBMUsage.ready;x.click('/Lessons/pack.zip?token=secret#pupil');x.click('/Lessons/pack.zip');assert.equal(x.posts().length,2);assert.equal(JSON.parse(x.posts()[1].options.body).event_type,'download_request');assert(!x.posts()[1].options.body.includes('secret'));});
 await run('game launch from education uses play resource without cross-domain ID',async()=>{const x=make({choice:'allow'});await x.window.MBMUsage.ready;x.click('https://www.madebymatt-play.uk/game/?saved=private');const body=JSON.parse(x.posts()[1].options.body);assert.equal(body.source,'play');assert.equal(body.event_type,'game_launch');assert.notEqual(body.event_nonce,JSON.parse(x.posts()[0].options.body).event_nonce);});
 await run('unknown and external destinations never emit',async()=>{const x=make({choice:'allow'});await x.window.MBMUsage.ready;x.click('/unknown.pdf');x.click('https://third.example/pack.zip');assert.equal(x.posts().length,1);});
 await run('opting out stops future events',async()=>{const x=make({choice:'allow'});await x.window.MBMUsage.ready;x.window.MBMUsage.setChoice('deny');x.click('/Lessons/pack.zip');assert.equal(x.posts().length,1);assert.equal(x.window.MBMUsage.choice(),'deny');});
 await run('privacy signal overrides an earlier opt-in',async()=>{const x=make({choice:'allow',privacy:true});await x.window.MBMUsage.ready;x.click('/Lessons/pack.zip');assert.equal(x.posts().length,0);});
 await run('automation and unapproved origins cannot write',async()=>{for(const options of [{webdriver:true},{locationHref:'https://preview.invalid/Lessons/test.html'}]){const x=make({choice:'allow',...options});await x.window.MBMUsage.ready;x.click('/Lessons/pack.zip');assert.equal(x.posts().length,0);}});
 await run('provider failure has no local-count fallback',async()=>{const x=make({failPublic:true});await x.window.MBMUsage.ready;await assert.rejects(x.window.MBMUsage.publicSummary('education'),/offline/);assert(![...x.local.keys()].some(k=>k.startsWith('mbm_c_')));});
 await run('inactive counters preserve the existing download action and add no badge',async()=>{const x=make({enabled:false,choice:'allow',showDownloadLink:true});await x.window.MBMUsage.ready;assert.equal(x.downloadLink.textContent,'Download real pack');assert.equal(x.downloadLink.siblings.length,0);assert.equal(x.calls.filter(c=>c.url.startsWith('https:')).length,0);});
 await run('active shared count appears beside the unchanged download action',async()=>{const x=make({showDownloadLink:true,resourceCount:7});await x.window.MBMUsage.ready;await new Promise(resolve=>setImmediate(resolve));assert.equal(x.downloadLink.textContent,'Download real pack');assert.equal(x.downloadLink.siblings.length,1);assert.equal(x.downloadLink.siblings[0].textContent,'Shared download requests: 7 all time');assert.equal(x.posts().length,0);});
 const assembly=process.argv[2]||fs.readFileSync(path.join(__dirname,'ASSEMBLY_PATH'),'utf8').trim();
 const account=fs.readFileSync(path.join(assembly,'education-site/assets/mbm-account.js'),'utf8');
 const method=account.slice(account.indexOf('  function readUsageDashboard(source)'),account.indexOf('  function unsubscribeMailing()'));
 await run('owner method rejects unauthenticated users before request',async()=>{let called=0;const context={Promise,Error,requireUser:()=>Promise.reject(new Error('sign in')),sb:{functions:{invoke:()=>{called++;return Promise.resolve({data:{private:true}});}}}};vm.createContext(context);vm.runInContext(method,context);await assert.rejects(context.readUsageDashboard('education'),/sign in/);assert.equal(called,0);});
 await run('owner server denial never exposes private response',async()=>{let called=0;const context={Promise,Error,requireUser:()=>Promise.resolve({id:'ordinary-user'}),sb:{functions:{invoke:(name,options)=>{called++;assert.equal(name,'owner-usage?source=play');assert.equal(options.method,'GET');return Promise.resolve({error:new Error('403'),data:{private:true}});}}}};vm.createContext(context);vm.runInContext(method,context);await assert.rejects(context.readUsageDashboard('play'),/denied/);await assert.rejects(context.readUsageDashboard('../export?token=x'),/Invalid/);assert.equal(called,1);assert(!/access_token|localStorage|user_metadata|createClient/.test(method));});

 function dashboardFixture(){
   const events={};class Element{constructor(){this.hidden=false;this.disabled=false;this.value='';this.dataset={};this.children=[];this.handlers={};}addEventListener(name,fn){this.handlers[name]=fn;}replaceChildren(){this.children=[];}append(...nodes){this.children.push(...nodes);}appendChild(node){this.children.push(node);}querySelector(){return null;}}
   const elements=Object.fromEntries(['data-owner-status','data-owner-content','data-owner-source','data-owner-period','data-owner-load','data-owner-export'].map(key=>[key,new Element()]));
   elements['data-owner-source'].value='education';elements['data-owner-period'].value='last30days';
   const root={querySelector:selector=>elements[selector.slice(1,-1)]},document={querySelector:()=>root,createElement:()=>new Element()};
   let resolveRead;const window={addEventListener:(name,fn)=>events[name]=fn,MBMUsage:{ready:Promise.resolve({enabled:true}),paintRanks:()=>{}},MBMAccount:{ready:Promise.resolve(),state:{user:{id:'owner-id'}},readUsageDashboard:()=>new Promise(resolve=>{resolveRead=resolve;})}};
   vm.runInNewContext(fs.readFileSync(path.join(__dirname,'usage-dashboard.js'),'utf8'),{window,document,Promise,Error,Number,Date,URL,Blob,setTimeout});
   const data={schema:1,source:'education',enabled:true,measured_since:null,windows:{last30days:{totals:{lesson_open:0,download_request:0,game_launch:0},top:{lessons:[],packs:[],games:[]}}},geography:{enabled:false,rows:[]}};
   return{elements,events,resolve:()=>resolveRead(data),load:()=>elements['data-owner-load'].handlers.click()};
 }
 async function tick(){await new Promise(resolve=>setImmediate(resolve));}
 await run('late owner response cannot appear after sign-out',async()=>{const x=dashboardFixture();await tick();x.load();await tick();x.events['mbm:account-state']({detail:{user:null}});x.resolve();await tick();assert.equal(x.elements['data-owner-content'].hidden,true);assert.equal(x.elements['data-owner-export'].disabled,true);});
 await run('sign-out clears already displayed owner figures',async()=>{const x=dashboardFixture();await tick();x.load();await tick();x.resolve();await tick();assert.equal(x.elements['data-owner-content'].hidden,false);x.events['mbm:account-state']({detail:{user:null}});assert.equal(x.elements['data-owner-content'].hidden,true);assert.equal(x.elements['data-owner-content'].children.length,0);assert.equal(x.elements['data-owner-export'].disabled,true);});
 process.stdout.write(JSON.stringify({status:'PASS',checks:cases,live_requests:0})+'\n');
})().catch(e=>{console.error(e);process.exitCode=1;});
