// P3 screenshots at 412x915: idle, PERFECT lockout, form change, trial last 3 s. Also counts V5 effects.
import path from 'node:path';import fs from 'node:fs';
import { serve, launch, phoneContext, lockNetwork, coarsePointer, waitForGame } from './lib.mjs';
const file=process.argv[2],outDir=process.argv[3];fs.mkdirSync(outDir,{recursive:true});
const dir=path.dirname(path.resolve(file)),name=path.basename(file);
const {server,base}=await serve(dir);const browser=await launch();
async function open(seed){const ctx=await phoneContext(browser,{width:412,height:915,coarse:true});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e.message||e)));await coarsePointer(page);const url=`${base}/${name}`;await lockNetwork(page,url);if(seed)await page.addInitScript((s)=>{try{localStorage.setItem('mbm_titanforge_save_v1',JSON.stringify(s));}catch(e){}},seed);await page.goto(url);await waitForGame(page);await page.waitForTimeout(600);return {ctx,page,errors};}
const rep=async(page)=>page.evaluate(async()=>{const ctl=window.__MBM_TITAN_AAA__.getController();const raf=()=>new Promise(r=>requestAnimationFrame(r));while(ctl.phase!=='concentric'||ctl.committing)await raf();let prev=ctl.position;while(!(Math.abs(ctl.position-.72)<=.05&&ctl.position>=prev)){prev=ctl.position;await raf();}ctl.action();let lastTap=0;while(ctl.phase==='isometric'){const t=performance.now();if(Math.abs(ctl.balance-.5)>.035&&t-lastTap>=112){ctl.action();lastTap=t;}await raf();}while(ctl.phase==='eccentric'&&ctl.position<.665)await raf();let lifted=false;const h=()=>{lifted=true;};window.addEventListener('mbm:titan-lift',h);ctl.action();const t0=performance.now();while(!lifted&&performance.now()-t0<2500)await raf();window.removeEventListener('mbm:titan-lift',h);return lifted;});
const base_seed={strength:12,coins:80,gems:3,reps:0,perfects:0,bestCombo:0,ascensions:0,equipped:0,purchased:[0],zone:0,claimedQuests:[],lastDaily:"",attemptedTrials:[],starterTier:0,windowLevel:0,comboLevel:0,sound:true,reducedMotion:false};
const lines=[];
// 1 idle
{const {ctx,page,errors}=await open(null);await page.waitForTimeout(3200);const st=await page.evaluate(()=>({idle:!!document.querySelector('.mbm-v5-bg.mbm-v5-idle'),zone:window.__MBM_TITAN_V5__.zoneKey(),rim:!!document.querySelector('.mbm-v5-rim.mbm-v5-on'),parallax:!!document.querySelector('.arena.mbm-v5-parallax'),layers:document.querySelectorAll('.mbm-v5-bg>i').length,anims:document.getAnimations().filter(a=>a.playState==='running'&&/mbmV5/.test(a.animationName||'')).map(a=>a.animationName)}));await page.screenshot({path:path.join(outDir,'p3-idle-412x915.png')});lines.push(`idle: parallax=${st.parallax} layers=${st.layers} idleDrift=${st.idle} zone=${st.zone} rim=${st.rim} running V5 animations=${st.anims.join(',')} errors=${errors.length}`);await ctx.close();}
// 2 PERFECT lockout
{const {ctx,page,errors}=await open(null);const lifted=await rep(page);await page.waitForTimeout(70);const st=await page.evaluate(()=>({fx:window.__MBM_TITAN_V5__.fxCounters,cam:getComputedStyle(document.querySelector('.arena')).getPropertyValue('--mbm-cam').trim(),squash:!!document.querySelector('.avatar-placeholder.mbm-v5-squash'),hit:!!document.querySelector('.mbm-v5-bg.mbm-v5-hit')||!!document.querySelector('.mbm-v5-bg.mbm-v5-settle'),spawned:window.__MBM_TITAN_MOBILE_V2__.metrics.spawned,glow:window.__MBM_TITAN_MOBILE_V2__.metrics.glowPasses}));await page.screenshot({path:path.join(outDir,'p3-perfect-412x915.png')});lines.push(`PERFECT lockout: lifted=${lifted} counters=${JSON.stringify(st.fx)} cam=${st.cam} squash=${st.squash} kick=${st.hit} particles spawned=${st.spawned} glowPasses=${st.glow} errors=${errors.length}`);await ctx.close();}
// 3 form change (reps 11 -> 12 unlocks FORGED) + rank (495 -> CONTENDER)
{const {ctx,page,errors}=await open(Object.assign({},base_seed,{reps:11,strength:495}));const lifted=await rep(page);await page.waitForTimeout(560);const st=await page.evaluate(()=>({fx:window.__MBM_TITAN_V5__.fxCounters,cine:!!document.querySelector('.mbm-v5-cine'),plate:(document.querySelector('.mbm-v5-plate')||{}).textContent,imgs:document.querySelectorAll('.mbm-v5-cine img').length,rank:(document.querySelector('.mbm-v5-rank.mbm-v5-show strong')||{}).textContent,form:document.querySelector('.fighter-stage').getAttribute('data-mbm-form')}));await page.screenshot({path:path.join(outDir,'p3-formchange-412x915.png')});lines.push(`form change: lifted=${lifted} cinematic=${st.cine} plate="${st.plate}" wipe imgs=${st.imgs} data-mbm-form=${st.form} rank card="${st.rank}" counters=${JSON.stringify(st.fx)} errors=${errors.length}`);await ctx.close();}
// 4 trial last 3 s (Rook, required strength 0)
{const {ctx,page,errors}=await open(null);
 await page.click('.mobile-dock button:has-text("TRIALS")');await page.waitForTimeout(500);
 const buttons=await page.evaluate(()=>Array.from(document.querySelectorAll('[role="dialog"] button')).map(b=>b.textContent.trim()));
 const btn=await page.$('[role="dialog"] button:has-text("Rook")')||await page.$('[role="dialog"] button:has-text("CHALLENGE")')||await page.$('[role="dialog"] button:has-text("START")');
 let started=false,secsSeen=[],red=false,crowd=false,tint=false;
 if(btn){await btn.click();started=await page.waitForSelector('.trial-hud',{timeout:4000}).then(()=>true).catch(()=>false);}
 if(started){for(let i=0;i<200;i++){const s=await page.evaluate(()=>{const b=document.querySelector('.trial-hud .trial-head b');return b?parseFloat(b.textContent):NaN;});if(Number.isFinite(s))secsSeen.push(s);if(s<=3){await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(380);break;}await page.waitForTimeout(100);}
  const st=await page.evaluate(()=>({red:document.querySelector('.arena').classList.contains('mbm-v5-trial-red'),crowd:document.querySelector('.arena').classList.contains('mbm-v5-trial'),tintOpacity:getComputedStyle(document.querySelector('.mbm-v5-redtint')).opacity,crowdOpacity:getComputedStyle(document.querySelector('.mbm-v5-crowd')).opacity,key:getComputedStyle(document.querySelector('.arena')).getPropertyValue('--mbm-key').trim(),secs:(document.querySelector('.trial-hud .trial-head b')||{}).textContent}));red=st.red;crowd=st.crowd;tint=st.tintOpacity;
  await page.screenshot({path:path.join(outDir,'p3-trial-last3s-412x915.png')});lines.push(`trial: started=${started} timer seen ${secsSeen[0]}s→${secsSeen[secsSeen.length-1]}s crowd=${crowd} (opacity ${st.crowdOpacity}) red=${red} tint opacity=${st.tintOpacity} key=${st.key} at ${st.secs} errors=${errors.length}`);}
 else lines.push(`trial: could not start. dialog buttons: ${buttons.join(' | ')}`);
 await ctx.close();}
await browser.close();server.close();console.log(lines.join('\n'));
