#!/usr/bin/env python3
"""Regenerate ONLY the site-repo section of sitemap.xml (Pass Q5).
- site URLs derived from disk (root + top-level dirs with index.html)
- robots.txt Disallow honoured; redirect-stub-marked index.html excluded
- lastmod = true last-commit date; changefreq/priority preserved from existing
- order preserved; everything from the first sibling (/Lessons/) onward is byte-identical
Usage: sitemap_regen.py            (check: print intended diff, exit 1 if would change)
       sitemap_regen.py --write    (write the file)"""
import os,re,sys,subprocess
HOST='https://madebymatt.uk/'
SIB=('Lessons/','Games/','Matt-s-Apps-/')
WRITE='--write' in sys.argv
raw=open('sitemap.xml').read()

# robots Disallow
disallow=[re.match(r'\s*Disallow:\s*(\S+)',l).group(1).strip('/')+'/' for l in open('robots.txt') if re.match(r'\s*Disallow:\s*\S',l)]
def blocked(u): return any(u==d or u.startswith(d) for d in disallow)
def is_stub(path):
    try: return 'mbm:redirect-stub' in open(path,encoding='utf-8').read(4000)
    except: return False
def gitdate(path):
    return subprocess.run(['git','log','-1','--format=%cs','--',path],capture_output=True,text=True).stdout.strip()

# derive site URLs from disk -> backing file
derived={}   # url -> backing file
derived[HOST]='index.html'
for name in sorted(os.listdir('.')):
    if name.startswith('.') or name.startswith('_'): continue
    idx=os.path.join(name,'index.html')
    if os.path.isdir(name) and os.path.exists(idx):
        u=name+'/'
        if blocked(u): continue
        if is_stub(idx): continue
        derived[HOST+u]=idx

# split sitemap at first sibling <url>
m=re.search(r'  <url>\s*<loc>'+re.escape(HOST)+r'(?:'+'|'.join(re.escape(s) for s in SIB)+r')',raw)
if not m: sys.exit('could not find sibling boundary')
head_end=raw.index('  <url>')                 # start of first <url>
prefix=raw[:head_end]                          # xml decl + urlset open (+ any comment)
suffix=raw[m.start():]                          # from first sibling <url> onward — BYTE-IDENTICAL

# parse existing site-section blocks (between prefix and suffix) to preserve order + cf/priority
site_raw=raw[head_end:m.start()]
existing=[]  # (loc,cf,pri)
for b in re.finditer(r'<loc>('+re.escape(HOST)+r'[^<]*)</loc>\s*<lastmod>[^<]*</lastmod>\s*<changefreq>([^<]*)</changefreq>\s*<priority>([^<]*)</priority>',site_raw):
    existing.append((b.group(1),b.group(2),b.group(3)))
existing_locs=[e[0] for e in existing]

# drift between disk and sitemap site-section
missing=[u for u in derived if u not in existing_locs]     # on disk, not in sitemap
extra=[u for u in existing_locs if u not in derived]        # in sitemap, no live section
if missing or extra:
    print('SITE-SECTION SET DRIFT:')
    for u in missing: print('  + on disk, absent from sitemap:',u)
    for u in extra:   print('  - in sitemap, no live section:',u)

# rebuild site blocks: preserve existing order (+append any disk-only at end), lastmod from git
order=existing_locs+[u for u in derived if u not in existing_locs]
cfpri={loc:(cf,pri) for loc,cf,pri in existing}
blocks=[]
for loc in order:
    if loc in extra: continue                  # drop locs with no backing file
    cf,pri=cfpri.get(loc,('weekly','0.8'))
    lm=gitdate(derived[loc])
    blocks.append(f"  <url>\n    <loc>{loc}</loc>\n    <lastmod>{lm}</lastmod>\n    <changefreq>{cf}</changefreq>\n    <priority>{pri}</priority>\n  </url>\n")
prov="  <!-- Site-repo section below: generated by _passq/sitemap_regen.py from disk (true last-commit lastmods, robots.txt Disallow honoured, redirect stubs excluded). Do not hand-edit. Cross-repo sections that follow are hand-maintained. -->\n"
new=prefix+prov+''.join(blocks)+suffix

if new==raw:
    print('no change'); sys.exit(0)
if WRITE:
    open('sitemap.xml','w').write(new); print('written'); sys.exit(0)
else:
    # show intended diff via temp
    open('_passq/sitemap_new.xml','w').write(new)
    print('would change; see _passq/sitemap_new.xml'); sys.exit(1)
