/* Made by Matt — Live-Teach HUD v1
   One floating dock for the whole estate: timer, name picker, noise meter, calm reset.
   Self-contained, no dependencies, everything stays on this device. */
(function () {
  "use strict";
  if (window.__mbmHud) return; window.__mbmHud = true;
  try {

  var NS = "mbmhud";
  var PATH = location.pathname;
  /* The directory form of the path, so /apexgolf/ and /apexgolf/index.html are
     the same page as far as the game lookup below is concerned. They are the
     same page to the server too. */
  var ROUTE = PATH.replace(/index\.html$/, "");

  /* The site's own root-level games, GENERATED from data/mbm-search-index.json
     by tools/render_audience_homepages.py. Do not edit between the markers.

     These pages matched none of the four path patterns below, so BACK resolved
     null, mount() had nothing to append, and a script tag alone gave them
     nothing at all - /neonbreach/ has loaded this file for months and rendered
     no HUD whatsoever. A fifth pattern would have been a hand-written second
     copy of an inventory the estate already keeps, stale the first time a game
     shipped. This is that inventory, filtered to single-segment game routes. */
  /* MBM-ROOT-GAMES:BEGIN generated by tools/render_audience_homepages.py, do not edit by hand */
  var ROOT_GAMES = {"/apexcurl/":1,"/apexgolf/":1,"/apexkick/":1,"/apexpool/":1,"/apexrally/":1,"/apextennis/":1,"/apexvelodrome/":1,"/auroralinks/":1,"/biopunkhive/":1,"/crownbadge/":1,"/cyberpulse/":1,"/echovault/":1,"/emberwild/":1,"/fracture/":1,"/houseolympiad/":1,"/hyperdraft/":1,"/luminahaven/":1,"/medevac/":1,"/micro-tinkerer/":1,"/neonbreach/":1,"/neonmeridian/":1,"/neonsync/":1,"/neonturf/":1,"/novasiege/":1,"/offbrand/":1,"/olympics/":1,"/ouroboros/":1,"/rallyvector3d/":1,"/relicforge/":1,"/titanforge/":1,"/touchline/":1,"/townlife/":1,"/trailrunner/":1,"/voxel/":1};
  /* MBM-ROOT-GAMES:END */

  /* Teacher tools that live at their own root route rather than under
     /Matt-s-Apps-/ or as /<name>/app.html. Listed rather than pattern-matched,
     so admitting a tool to the HUD stays a deliberate act.

     /artsaward/ is here because it matched none of the four patterns below,
     which is the /neonbreach/ failure described above repeating exactly: the
     script tag is present, BACK resolves null, mount() has nothing to append,
     and the page renders no HUD at all while looking as though it carries one.
     Shipping the tag without this entry would have been that bug again. */
  var ROOT_TOOLS = { "/artsaward/": 1, "/evidence-binder/moderator-pro/": 1, "/asdan/moderation-lab/": 1 };

  var IS_GAME = /\/Games\//.test(PATH)
    || Object.prototype.hasOwnProperty.call(ROOT_GAMES, ROUTE);
  var IS_APP = /\/Matt-s-Apps-\/.+\.html/.test(PATH);
  var IS_REG = /^\/(uas|asdan)\/app\.html$/.test(PATH)
    || Object.prototype.hasOwnProperty.call(ROOT_TOOLS, ROUTE);
  var IS_LESSON = /\/Lessons\//.test(PATH) && !IS_GAME;
  var BACK = IS_GAME ? { h: "/games/", l: "\u2190 Arcade" }
    : IS_APP ? { h: "/Matt-s-Apps-/", l: "\u2190 Studios" }
    : IS_REG ? { h: "/tools/", l: "\u2190 Tools" }
    : IS_LESSON ? { h: "/Lessons/", l: "\u2190 Lessons" } : null;
  var LS_NAMES = "mbm_hud_names", LS_USED = "mbm_hud_used";
  function lsGet(k, fb) { try { var v = localStorage.getItem(k); return v === null ? fb : v; } catch (e) { return fb; } }
  function lsSet(k, v) { try { localStorage.setItem(k, v); } catch (e) {} }

  /* The homepage types a visitor can choose, and where each one lives.

     GENERATED, not typed. hud.js is served onto games, apps, registers and
     lessons, and it cannot read data/audience-homepages.json at run time: a
     fetch on a game's load path would put a request in front of a child
     mid-session, break the offline promise, and trip the estate-wide "no third
     party at page load" assertion. So the region below is spliced in by
     tools/render_audience_homepages.py from the file that owns these values,
     and --check fails if it drifts from them. Do not edit between the markers. */
  /* MBM-HOMEPAGE-CHOICES:BEGIN generated by tools/render_audience_homepages.py, do not edit by hand */
  var HOME_KEY = "mbm_audience_view";
  var HOMES = {"pupils":{r:"/for/pupils/",l:"Pupils & learners"},"teachers":{r:"/for/teachers/",l:"Teachers & education staff"},"parents":{r:"/for/parents-carers/",l:"Parents & carers"},"schools":{r:"/for/schools-semh/",l:"Schools & specialist settings"},"trusts":{r:"/for/trusts/",l:"Academy trusts & education groups"},"councils":{r:"/for/councils-organisations/",l:"Local authorities & education partners"},"partners":{r:"/for/partners/",l:"Education organisations & service providers"},"main":{r:"/main/",l:"Main homepage"}};
  /* MBM-HOMEPAGE-CHOICES:END */

  /* ---------- styles ---------- */
  var css = ""
  + "#" + NS + "-pill{position:fixed;left:50%;bottom:10px;transform:translateX(-50%);z-index:2147483000;background:rgba(22,29,61,.72);color:#B9E6CD;border:1.5px solid rgba(185,230,205,.45);border-radius:999px;padding:6px 16px;font:700 12px/1 Poppins,'Segoe UI',system-ui,sans-serif;letter-spacing:.08em;cursor:pointer;backdrop-filter:blur(6px);-webkit-backdrop-filter:blur(6px);opacity:.75}"
  + "#" + NS + "-pill:hover,#" + NS + "-pill:focus-visible{opacity:1;outline:none;border-color:#B9E6CD}"
  + "#" + NS + "-back{position:fixed;left:10px;bottom:10px;z-index:2147483000;min-height:44px;box-sizing:border-box;display:inline-flex;align-items:center;background:rgba(22,29,61,.72);color:#B9E6CD;border:1.5px solid rgba(185,230,205,.45);border-radius:999px;padding:6px 13px;font:700 12px/1 Poppins,'Segoe UI',system-ui,sans-serif;letter-spacing:.06em;text-decoration:none;backdrop-filter:blur(6px);-webkit-backdrop-filter:blur(6px);opacity:.72}"
  + "#" + NS + "-back:hover,#" + NS + "-back:focus-visible{opacity:1;outline:none;border-color:#B9E6CD}"
  + "#" + NS + "-back.game{left:calc(8px + env(safe-area-inset-left,0px));top:calc(8px + env(safe-area-inset-top,0px));bottom:auto;width:44px;height:44px;padding:0;display:flex;align-items:center;justify-content:center;border-radius:50%;font-size:16px;opacity:.55}"
  + "#" + NS + "-home{position:fixed;left:10px;bottom:10px;z-index:2147483000;min-height:44px;box-sizing:border-box;max-width:calc(100vw - 20px);background:rgba(22,29,61,.72);color:#B9E6CD;border:1.5px solid rgba(185,230,205,.45);border-radius:999px;padding:6px 13px;font:700 12px/1 Poppins,'Segoe UI',system-ui,sans-serif;letter-spacing:.06em;text-decoration:none;display:inline-flex;align-items:center;gap:6px;backdrop-filter:blur(6px);-webkit-backdrop-filter:blur(6px);opacity:.72}"
  + "#" + NS + "-home:hover,#" + NS + "-home:focus-visible{opacity:1;outline:none;border-color:#B9E6CD}"
  + "#" + NS + "-home:focus-visible{outline:3px solid #F2A24A;outline-offset:2px}"
  + "#" + NS + "-home span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}"
  + "#" + NS + "-home.game{left:calc(8px + env(safe-area-inset-left,0px));top:calc(8px + env(safe-area-inset-top,0px));bottom:auto;width:44px;height:44px;padding:0;gap:0;display:flex;align-items:center;justify-content:center;border-radius:50%;opacity:.55}"
  + "#" + NS + "-dock{position:fixed;left:50%;bottom:10px;transform:translateX(-50%);z-index:2147483001;width:min(680px,calc(100vw - 20px));background:rgba(246,241,228,.92);border:2px solid #161D3D;border-radius:18px;box-shadow:0 14px 40px rgba(15,21,48,.45);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);padding:12px 14px;display:none;font-family:Poppins,'Segoe UI',system-ui,sans-serif;color:#1B2140}"
  + "#" + NS + "-dock.open{display:block}"
  + "." + NS + "-row{display:flex;gap:10px;align-items:stretch;flex-wrap:wrap}"
  + "." + NS + "-mod{flex:1;min-width:150px;background:#FFFDF6;border:1.5px solid #E0D6C0;border-radius:12px;padding:9px 10px;display:flex;flex-direction:column;gap:6px}"
  + "." + NS + "-mod b{font-size:10px;letter-spacing:.14em;color:#4A5170}"
  + "." + NS + "-btns{display:flex;gap:6px;flex-wrap:wrap}"
  + "." + NS + "-btn{font:800 12px/1 Poppins,'Segoe UI',sans-serif;letter-spacing:.04em;background:#FFFDF6;color:#161D3D;border:1.5px solid #161D3D;border-radius:999px;padding:7px 12px;cursor:pointer;box-sizing:border-box;min-height:44px;display:inline-flex;align-items:center;justify-content:center}"
  + "." + NS + "-btn:hover{background:#161D3D;color:#FFF6E8}"
  + "." + NS + "-btn.amber{background:#F2A24A;border-color:#C97F2E;color:#161D3D}"
  + "." + NS + "-btn.amber:hover{filter:brightness(1.06);background:#F2A24A;color:#161D3D}"
  + "." + NS + "-btn.mint{background:#B9E6CD;border-color:#2F6B4D;color:#143324}"
  + "." + NS + "-btn:focus-visible{outline:3px solid #F2A24A;outline-offset:2px}"
  + "#" + NS + "-name{font:800 17px/1.2 Poppins,'Segoe UI',sans-serif;color:#161D3D;min-height:22px}"
  + "#" + NS + "-names{width:100%;box-sizing:border-box;font:12px/1.4 Poppins,'Segoe UI',sans-serif;border:1.5px solid #C9C0AB;border-radius:8px;padding:6px;resize:vertical;min-height:44px;max-height:90px;background:#fff}"
  + "#" + NS + "-meter{display:flex;align-items:flex-end;gap:2px;height:44px}"
  + "#" + NS + "-meter i{flex:1;background:#2F8F6B;border-radius:2px 2px 0 0;min-height:2px;transition:height .12s ease}"
  + "#" + NS + "-meter.loud i{background:#C25B4E}"
  + "." + NS + "-note{font-size:10px;color:#4A5170;line-height:1.35}"
  + "#" + NS + "-dock button:focus-visible,#" + NS + "-pill:focus-visible,#" + NS + "-back:focus-visible,#" + NS + "-close:focus-visible{outline:3px solid #F2A24A;outline-offset:2px}" + 
  "#" + NS + "-close{position:absolute;top:4px;right:6px;background:none;border:0;font:800 13px Poppins,sans-serif;color:#4A5170;cursor:pointer;padding:4px;min-width:44px;min-height:44px;display:flex;align-items:center;justify-content:center;touch-action:manipulation}"
  + "#" + NS + "-timerbox{position:fixed;top:14px;right:14px;z-index:2147483002;background:rgba(22,29,61,.94);color:#FFF6E8;border:2px solid #F2A24A;border-radius:16px;padding:10px 18px;text-align:center;display:none;font-family:Poppins,'Segoe UI',sans-serif}"
  + "#" + NS + "-timerbox.on{display:block}"
  + "#" + NS + "-timerbox.done{border-color:#B9E6CD;animation:" + NS + "-pulse 2s ease-in-out infinite}"
  + "#" + NS + "-time{font:800 34px/1 Poppins,sans-serif;letter-spacing:.04em}"
  + "#" + NS + "-timerbox ." + NS + "-btns{justify-content:center;margin-top:6px}"
  + "@keyframes " + NS + "-pulse{0%,100%{box-shadow:0 0 0 0 rgba(185,230,205,.5)}50%{box-shadow:0 0 0 10px rgba(185,230,205,0)}}"
  + "#" + NS + "-calm{position:fixed;inset:0;z-index:2147483003;background:radial-gradient(ellipse at 50% 42%,#232C55,#0F1530 75%);display:none;flex-direction:column;align-items:center;justify-content:center;gap:26px;font-family:Poppins,'Segoe UI',sans-serif}"
  + "#" + NS + "-calm.on{display:flex}"
  + "#" + NS + "-ring{width:min(38vmin,240px);height:min(38vmin,240px);border-radius:50%;border:3px solid #B9E6CD;background:radial-gradient(circle,#B9E6CD22,transparent 70%);animation:" + NS + "-breathe 8s ease-in-out infinite}"
  + "#" + NS + "-calmtext{color:#C9D1E2;font:600 clamp(16px,3vmin,24px)/1.4 Poppins,sans-serif;letter-spacing:.06em;text-align:center}"
  + "#" + NS + "-calmexit{margin-top:8px;background:none;border:1.5px solid rgba(185,230,205,.5);color:#B9E6CD;border-radius:999px;padding:9px 20px;font:700 13px Poppins,sans-serif;cursor:pointer;opacity:.8}"
  + "#" + NS + "-calmexit:hover{opacity:1;border-color:#B9E6CD}"
  + "@keyframes " + NS + "-breathe{0%,100%{transform:scale(.72)}45%,55%{transform:scale(1)}}"
  + "@media (prefers-reduced-motion:reduce){#" + NS + "-ring{animation:none;transform:scale(.86)}#" + NS + "-timerbox.done{animation:none}}"
  + "@media print{#" + NS + "-back,#" + NS + "-home,#" + NS + "-pill,#" + NS + "-dock,#" + NS + "-timerbox,#" + NS + "-calm{display:none!important}}";
  var st = document.createElement("style"); st.id = NS + "-style"; st.textContent = css;
  (document.head || document.documentElement).appendChild(st);

  /* ---------- markup ---------- */
  function el(tag, attrs, html) {
    var e = document.createElement(tag);
    if (attrs) for (var k in attrs) e.setAttribute(k, attrs[k]);
    if (html !== undefined) e.innerHTML = html;
    return e;
  }
  var pill = el("button", { id: NS + "-pill", type: "button", "aria-expanded": "false", "aria-label": "Open the Live-Teach HUD" }, "\u26A1 TEACH");
  var dock = el("div", { id: NS + "-dock", role: "dialog", "aria-label": "Live-Teach HUD" });
  dock.innerHTML =
    '<button id="' + NS + '-close" type="button" aria-label="Close the HUD">\u2715</button>'
    + '<div class="' + NS + '-row">'
    + '<div class="' + NS + '-mod"><b>QUICK TIMER</b><div class="' + NS + '-btns">'
    + '<button class="' + NS + '-btn" type="button" data-min="1">1 min</button>'
    + '<button class="' + NS + '-btn" type="button" data-min="5">5 min</button>'
    + '<button class="' + NS + '-btn" type="button" data-min="10">10 min</button></div>'
    + '<span class="' + NS + '-note">Overlays the top corner \u2014 no sound, just a gentle pulse at zero.</span></div>'
    + '<div class="' + NS + '-mod"><b>NAME PICKER</b><div id="' + NS + '-name" aria-live="polite" aria-atomic="true">\u2014</div><div class="' + NS + '-btns">'
    + '<button class="' + NS + '-btn amber" type="button" id="' + NS + '-pick">Pick a name</button>'
    + '<button class="' + NS + '-btn" type="button" id="' + NS + '-edit">Edit list</button></div>'
    + '<textarea id="' + NS + '-names" style="display:none" placeholder="One name per line \u2014 saved on this device only" aria-label="Class name list"></textarea></div>'
    + '<div class="' + NS + '-mod"><b>NOISE METER</b><div id="' + NS + '-meter" aria-hidden="true"></div><div class="' + NS + '-btns">'
    + '<button class="' + NS + '-btn" type="button" id="' + NS + '-mic">Start meter</button></div>'
    + '<span class="' + NS + '-note" id="' + NS + '-micnote">Uses the mic on this device only \u2014 nothing is recorded or uploaded.</span></div>'
    + '<div class="' + NS + '-mod" style="justify-content:center"><b>RESET THE ROOM</b>'
    + '<button class="' + NS + '-btn mint" type="button" id="' + NS + '-calmbtn" style="font-size:13px;padding:12px 14px">\uD83C\uDF3F CALM RESET \u2192</button>'
    + '<span class="' + NS + '-note">Replaces the screen with a slow breathing guide. Tap to return.</span></div>'
    + '</div>';
  var timerbox = el("div", { id: NS + "-timerbox", role: "timer", "aria-live": "off" });
  timerbox.innerHTML = '<div id="' + NS + '-time">0:00</div><div class="' + NS + '-btns">'
    + '<button class="' + NS + '-btn" type="button" id="' + NS + '-tpause">Pause</button>'
    + '<button class="' + NS + '-btn" type="button" id="' + NS + '-tstop">Clear</button></div>';
  var calm = el("div", { id: NS + "-calm", role: "dialog", "aria-label": "Calm reset breathing guide" });
  calm.innerHTML = '<div id="' + NS + '-ring"></div><div id="' + NS + '-calmtext">Breathe in\u2026</div>'
    + '<button id="' + NS + '-calmexit" type="button">Return to the lesson</button>';

  var backEl = null;
  if (BACK) {
    backEl = el("a", { id: NS + "-back", href: BACK.h, "aria-label": "Back: " + BACK.l.replace("\u2190 ", "") });
    if (IS_GAME) { backEl.className = "game"; backEl.textContent = "\u2190"; backEl.title = BACK.l.replace("\u2190 ", "Back to the "); }
    else backEl.textContent = BACK.l;
  }

  /* ---------- the chosen homepage ---------- */
  /* A SECOND control, never a replacement. The back control keeps its own
     target and its own label: a pupil mid-session wants the arcade, not the
     front door, and replacing the exit they know with one they do not is a
     worse page even when the new destination is nicer.

     IT RENDERS ONLY WHEN A HOMEPAGE HAS BEEN CHOSEN. With nothing stored there
     is no "your homepage" to return to, and a home button pointing at the adult
     platform homepage one tap from a child's game is not a default worth
     having. The back control already gives an exit.

     THE PUPIL RULE, held by construction rather than by a branch. This control
     navigates only to the route of the value that is actually stored - there is
     no fallback arm - so a stored 'pupils' resolves to /for/pupils/, and
     nothing resolves to /main/ except an explicit choice of /main/. Games carry
     no data-mbm-adult-features flag, so keying on the stored value is the only
     form of the rule available here, and it is the strict form. */
  var HOME_GLYPH = '<svg viewBox="0 0 24 24" width="15" height="15" aria-hidden="true" focusable="false"'
    + ' fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'
    + '<path d="M4 10.6 12 4.2l8 6.4"/><path d="M6.2 9.6V19.8h11.6V9.6"/></svg>';
  function chosenHome() {
    var v = lsGet(HOME_KEY, "");
    return Object.prototype.hasOwnProperty.call(HOMES, v) ? HOMES[v] : null;
  }
  var home = chosenHome();
  var homeEl = null;
  if (home) {
    homeEl = el("a", { id: NS + "-home", href: home.r,
      "aria-label": "Your homepage: " + home.l, title: "Your homepage: " + home.l });
    if (IS_GAME) { homeEl.className = "game"; homeEl.innerHTML = HOME_GLYPH; }
    else homeEl.innerHTML = HOME_GLYPH + "<span></span>";
    var caption = homeEl.querySelector("span");
    if (caption) caption.textContent = home.l;
  }

  /* Placement is derived from the back control's real box, never from a guess
     at its width or its line height. Both are position:fixed siblings on body,
     so the only way to be sure they never overlap - at any viewport, in any
     font, under any of the four back labels - is to measure one and offset the
     other. With no back control the CSS default already puts this one in that
     corner, which is why the measurement is conditional and the default is not.
     Re-derived on resize and orientation change. */
  var HOME_GAP = 6;
  function placeHome() {
    if (!homeEl || !backEl || !backEl.parentNode) return;
    var b = backEl.getBoundingClientRect();
    if (!b.width && !b.height) return;
    if (IS_GAME) {
      homeEl.style.left = Math.round(b.right + HOME_GAP) + "px";
      homeEl.style.top = Math.round(b.top) + "px";
    } else {
      homeEl.style.left = Math.round(b.left) + "px";
      homeEl.style.bottom = Math.round(window.innerHeight - b.top + HOME_GAP) + "px";
    }
  }
  function mount() {
    if (backEl) document.body.appendChild(backEl);
    if (homeEl) { document.body.appendChild(homeEl); placeHome(); }
    if (!IS_LESSON) return;
    document.body.appendChild(pill); document.body.appendChild(dock);
    document.body.appendChild(timerbox); document.body.appendChild(calm);
  }
  if (document.body) mount(); else document.addEventListener("DOMContentLoaded", mount);
  try {
    window.addEventListener("resize", placeHome);
    window.addEventListener("orientationchange", placeHome);
  } catch (x) {}

  var $ = function (id) { return document.getElementById(NS + "-" + id); };

  /* ---------- dock open/close ---------- */
  pill.addEventListener("click", function () {
    var open = dock.classList.toggle("open");
    pill.setAttribute("aria-expanded", open ? "true" : "false");
    pill.style.display = open ? "none" : "";
    dock.setAttribute("aria-hidden", open ? "false" : "true");
    if (open) { dockOpener = document.activeElement; try { $("close").focus(); } catch (x) {} }
  });
  dock.addEventListener("click", function (e) {
    if (e.target && e.target.id === NS + "-close") {
      dock.classList.remove("open"); pill.style.display = ""; pill.setAttribute("aria-expanded", "false"); pill.focus();
     try { (dockOpener && dockOpener.focus ? dockOpener : pill).focus(); } catch (x) {} dockOpener = null;}
  });

  /* ---------- timer ---------- */
  var tLeft = 0, tRun = null;
  function tShow() {
    var m = Math.floor(tLeft / 60), s = tLeft % 60;
    $("time").textContent = m + ":" + (s < 10 ? "0" : "") + s;
  }
  function tTick() {
    if (tLeft > 0) { tLeft--; tShow(); if (tLeft === 0) { timerbox.classList.add("done"); clearInterval(tRun); tRun = null; $("tpause").textContent = "Pause"; } }
  }
  dock.addEventListener("click", function (e) {
    var b = e.target && e.target.getAttribute && e.target.getAttribute("data-min");
    if (!b) return;
    tLeft = parseInt(b, 10) * 60; timerbox.classList.add("on"); timerbox.classList.remove("done"); tShow();
    if (tRun) clearInterval(tRun);
    tRun = setInterval(tTick, 1000); $("tpause").textContent = "Pause";
  });
  timerbox.addEventListener("click", function (e) {
    if (!e.target) return;
    if (e.target.id === NS + "-tpause") {
      if (tRun) { clearInterval(tRun); tRun = null; e.target.textContent = "Resume"; }
      else if (tLeft > 0) { tRun = setInterval(tTick, 1000); e.target.textContent = "Pause"; }
    }
    if (e.target.id === NS + "-tstop") {
      if (tRun) clearInterval(tRun); tRun = null; tLeft = 0;
      timerbox.classList.remove("on", "done");
    }
  });

  /* ---------- name picker ---------- */
  function nameList() {
    return lsGet(LS_NAMES, "").split("\n").map(function (s) { return s.trim(); }).filter(Boolean);
  }
  $("edit") && 0; // placeholder guard removed below by direct wiring
  dock.addEventListener("click", function (e) {
    if (!e.target) return;
    if (e.target.id === NS + "-edit") {
      var ta = $("names");
      if (ta.style.display === "none") { ta.style.display = ""; ta.value = lsGet(LS_NAMES, ""); ta.focus(); e.target.textContent = "Save list"; }
      else { lsSet(LS_NAMES, ta.value); lsSet(LS_USED, "[]"); ta.style.display = "none"; e.target.textContent = "Edit list"; $("name").textContent = "\u2014"; }
    }
    if (e.target.id === NS + "-pick") {
      var names = nameList();
      if (!names.length) { $("name").textContent = "Add names first \u2192"; return; }
      var used = [];
      try { used = JSON.parse(lsGet(LS_USED, "[]")) || []; } catch (err) { used = []; }
      var pool = names.filter(function (n) { return used.indexOf(n) < 0; });
      if (!pool.length) { used = []; pool = names.slice(); }
      var n = pool[Math.floor(Math.random() * pool.length)];
      used.push(n); lsSet(LS_USED, JSON.stringify(used));
      $("name").textContent = n;
    }
  });

  /* ---------- noise meter ---------- */
  var micOn = false, audioCtx = null, rafId = null, micStream = null, micReq = 0;
  (function bars() { var m = $("meter"); if (!m) { setTimeout(bars, 50); return; } for (var i = 0; i < 16; i++) m.appendChild(document.createElement("i")); })();
  function releaseMic() {
    try { if (micStream && micStream.getTracks) micStream.getTracks().forEach(function (t) { try { t.stop(); } catch (x) {} }); } catch (x) {}
    micStream = null;
  }
  try { window.addEventListener("pagehide", function () {
    micOn = false; micReq++; if (rafId) cancelAnimationFrame(rafId);
    if (audioCtx && audioCtx.close) { try { audioCtx.close(); } catch (x) {} }
    releaseMic();
  }); } catch (x) {}
  dock.addEventListener("click", function (e) {
    if (!e.target || e.target.id !== NS + "-mic") return;
    if (micOn) {
      micOn = false; e.target.textContent = "Start meter";
      if (rafId) cancelAnimationFrame(rafId);
      if (audioCtx && audioCtx.close) audioCtx.close(); audioCtx = null;
      micReq++;
      releaseMic();
      return;
    }
    if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {
      $("micnote").textContent = "No microphone available on this device/browser."; return;
    }
    var AC = window.AudioContext || window.webkitAudioContext;
    try {
      if (!audioCtx || audioCtx.state === "closed") audioCtx = new AC();
      if (audioCtx.state === "suspended" && audioCtx.resume) audioCtx.resume();
    } catch (x) { $("micnote").textContent = "Audio is not available in this browser."; return; }
    var myReq = ++micReq;
    navigator.mediaDevices.getUserMedia({ audio: true }).then(function (stream) {
      if (myReq !== micReq) {
        try { stream.getTracks().forEach(function (t) { try { t.stop(); } catch (x) {} }); } catch (x) {}
        return;
      }
      micStream = stream;
      micOn = true; e.target.textContent = "Stop meter";
      /* audioCtx was created synchronously in the gesture above */
      var src = audioCtx.createMediaStreamSource(stream);
      var an = audioCtx.createAnalyser(); an.fftSize = 64;
      src.connect(an);
      var data = new Uint8Array(an.frequencyBinCount);
      var bars = $("meter").children;
      /* Bar heights are inline styles, so they are driven from the meter's OWN
         rendered height rather than from a literal repeated beside it. The two
         used to be the same number typed twice, and changing one without the
         other is a silently half-height meter. */
      var meterH = Math.round($("meter").getBoundingClientRect().height) || 44;
      /* reduced-motion: the bars are driven by inline heights, so CSS animation:none
         cannot reach them. When the pupil/teacher has asked for reduced motion we keep
         the meter VISUAL (it is a regulation aid, not decoration) but drop it to ~4
         updates a second and snap heights to 5 steps, so it reads as a level rather
         than a shimmer. rAF is retained either way so the existing
         cancelAnimationFrame teardown and mic-release path are untouched. */
      var rmq = null;
      try { rmq = window.matchMedia ? window.matchMedia("(prefers-reduced-motion: reduce)") : null; } catch (x) {}
      function calmMotion() { try { return !!(rmq && rmq.matches); } catch (x) { return false; } }
      var lastPaint = 0;
      (function loop() {
        if (!micOn) { for (var i = 0; i < bars.length; i++) bars[i].style.height = "2px"; return; }
        var easy = calmMotion(), now = (Date.now ? Date.now() : +new Date());
        if (easy && (now - lastPaint) < 250) { rafId = requestAnimationFrame(loop); return; }
        lastPaint = now;
        an.getByteFrequencyData(data);
        var avg = 0;
        for (var i = 0; i < bars.length; i++) {
          var v = data[i] / 255; avg += v;
          var h = (easy ? (Math.round(v * 5) / 5) : v) * meterH;
          bars[i].style.height = Math.max(2, Math.round(h)) + "px";
        }
        $("meter").classList.toggle("loud", (avg / bars.length) > 0.55);
        rafId = requestAnimationFrame(loop);
      })();
    }).catch(function () {
      $("micnote").textContent = "Mic permission was blocked \u2014 the meter needs it to listen (nothing is recorded).";
    });
  });

  /* ---------- calm reset ---------- */
  var calmTimer = null, calmPhase = 0;
  var PHASES = ["Breathe in\u2026", "Hold\u2026", "Breathe out slowly\u2026", "Rest\u2026"];
  function calmLoop() { calmPhase = (calmPhase + 1) % PHASES.length; $("calmtext").textContent = PHASES[calmPhase]; }
  dock.addEventListener("click", function (e) {
    if (!e.target || e.target.id !== NS + "-calmbtn") return;
    calm.classList.add("on"); dock.classList.remove("open");
    calmPhase = 0; $("calmtext").textContent = PHASES[0];
    calmTimer = setInterval(calmLoop, 4000);
    lastFocus = document.activeElement;
    try { calm.setAttribute("aria-modal", "true"); var ex = $("calmexit"); if (ex && ex.focus) ex.focus(); } catch (x) {}
  });
  var lastFocus = null, dockOpener = null;
  function closeCalm() {
    if (!calm.classList.contains("on")) return false;
    calm.classList.remove("on");
    if (calmTimer) clearInterval(calmTimer);
    pill.style.display = ""; pill.setAttribute("aria-expanded", "false");
    try { if (lastFocus && lastFocus.focus) lastFocus.focus(); } catch (x) {}
    lastFocus = null;
    return true;
  }
  calm.addEventListener("click", function () { closeCalm(); });
  /* Escape closes whatever HUD layer is open, innermost first */
  document.addEventListener("keydown", function (ev) {
    if (ev.key !== "Escape") return;
    if (closeCalm()) { ev.stopPropagation(); return; }
    /* the dock is a panel, not a full-screen modal: close it but let the
       lesson handle Escape too, so its own dialogs still close */
    if (dock.classList.contains("open")) {
      dock.classList.remove("open");
      pill.style.display = ""; pill.setAttribute("aria-expanded", "false");
      try { pill.focus(); } catch (x) {}
    }
  }, true);

  /* ---------- keys typed into the HUD stay in the HUD ----------
     The dock is a panel inside the page, so a key pressed in its name list
     bubbles to whatever the lesson bound on document. 93 of the 234 arrow-key
     decks in the estate never check the event target, and those advance the
     slide mid-word: measured on /Lessons/primary/year5/science/autumn/forces/
     Lesson1_Friction.html, typing a name and pressing ArrowRight twice moved
     the deck from slide 0 to slide 2 while the caret went nowhere, because the
     lesson calls preventDefault as well.

     Deliberately bubble-phase on the HUD's own hosts, not capture on document:
     capture would fire before the textarea itself saw the key and would break
     typing outright. It calls stopPropagation only - never preventDefault - so
     the caret, the newline and the selection all keep working.

     Escape returns immediately. Its layering (calm overlay, then dock, then the
     lesson's own dialogs) is decided by the capture-phase handler above and
     nothing here may reorder it. Tab is absent for the same reason: focus must
     still be able to leave the dock. */
  var HELD_KEYS = {
    ArrowLeft: 1, ArrowRight: 1, ArrowUp: 1, ArrowDown: 1,
    PageUp: 1, PageDown: 1, Home: 1, End: 1, Enter: 1, " ": 1, Spacebar: 1
  };
  function holdKeys(ev) {
    if (ev.key === "Escape") return;
    if (!HELD_KEYS[ev.key]) return;
    ev.stopPropagation();
  }
  /* Held for any target inside the HUD, not only for text entry. Space on the
     dock's own buttons is the same defect wearing a different hat: it activates
     the button AND advances the lesson on every deck that does not special-case
     it. */
  var KEY_HOSTS = [dock, timerbox, calm];
  for (var kh = 0; kh < KEY_HOSTS.length; kh++) {
    if (!KEY_HOSTS[kh]) continue;
    KEY_HOSTS[kh].addEventListener("keydown", holdKeys);
    KEY_HOSTS[kh].addEventListener("keyup", holdKeys);
    KEY_HOSTS[kh].addEventListener("keypress", holdKeys);
  }

  /* ---------- slide-change announcer ----------
     A deck changes slide by toggling a class. Nothing in that is an event a
     screen reader is told about, so a reader who cannot see the screen gets
     silence where a sighted reader gets a new slide. This watches the deck and
     writes the new slide's HEADING into a polite live region.

     Headings only, never body text: a slide's body can be hundreds of words and
     a polite region would read the lot over the top of whatever the teacher is
     saying. The heading is what a sighted reader takes from the transition.

     The countdown stays aria-live="off" and is deliberately not observed. A
     live timer announces every single second, which is the loudest possible way
     to make a room unusable. That verdict is settled and this does not reopen
     it.

     Lesson mode only, and entirely inside the enclosing try/catch: if any part
     of this throws, the page is exactly as it was. */
  if (IS_LESSON && window.MutationObserver) {
    var slides = document.querySelectorAll(".slide");
    if (slides.length > 1) {
      var say = el("div", { id: NS + "-say", "aria-live": "polite", "aria-atomic": "true" });
      /* Visually hidden, but never display:none - a display:none live region is
         not in the accessibility tree and announces nothing at all. */
      say.style.cssText = "position:absolute!important;width:1px;height:1px;margin:-1px;"
        + "padding:0;border:0;clip:rect(0 0 0 0);clip-path:inset(50%);overflow:hidden;white-space:nowrap";
      document.body.appendChild(say);

      var lastIndex = -1, sayTimer = null;
      function activeSlide() {
        for (var i = 0; i < slides.length; i++) {
          var s = slides[i];
          if (s.classList.contains("active") || s.classList.contains("show")) return i;
        }
        for (var j = 0; j < slides.length; j++) {
          if (getComputedStyle(slides[j]).display !== "none") return j;
        }
        return -1;
      }
      function headingOf(slide) {
        var h = slide.querySelector("h1,h2,h3,[data-title]");
        var text = h ? (h.getAttribute("data-title") || h.textContent || "") : "";
        if (!text) text = slide.getAttribute("data-title") || "";
        return text.replace(/\s+/g, " ").trim().slice(0, 140);
      }
      function announce() {
        var i = activeSlide();
        if (i < 0 || i === lastIndex) return;
        lastIndex = i;
        var text = headingOf(slides[i]);
        if (!text) return;
        /* Clearing first is what makes a repeat announce at all: two slides can
           share a heading, and an unchanged textContent is not a change. */
        /* Do not staple a full stop onto a heading that already ends in one:
           "what is a force?. Slide 2" is how that reads out loud. */
        var joined = text + (/[.!?:;—-]$/.test(text) ? " " : ". ")
          + "Slide " + (i + 1) + " of " + slides.length;
        say.textContent = "";
        setTimeout(function () { say.textContent = joined; }, 60);
      }
      /* Debounced: a transition can touch several slides' classes in one frame,
         and a reveal-step deck fires far more often than it changes slide. */
      var observer = new MutationObserver(function () {
        if (sayTimer) clearTimeout(sayTimer);
        sayTimer = setTimeout(announce, 220);
      });
      for (var k = 0; k < slides.length; k++) {
        observer.observe(slides[k], { attributes: true, attributeFilter: ["class", "style", "hidden"] });
      }
      lastIndex = activeSlide();   /* the first slide is not a transition */
    }
  }

  } catch (e) { /* the HUD must never break a lesson */ }
})();
