(function(){
  "use strict";
  var G=window.__MBM_TITAN_V5__;if(!G||G.duel)return;
  var KEY="mbm_titanforge_duel_v1",SIGNAL_KEY="mbm_titanforge_duel_signal",CHANNEL="mbm-titanforge-duel",BASE_URL="https://madebymatt.uk/titanforge/";
  var POWER={PERFECT:100,GREAT:60,SOLID:30},POWER_MS=20000,GRACE_MS=3000,LEAD_MS=1500,ICE_TIMEOUT=4000;
  var refs={},built=false,session=null,bc=null,hashJob=null;
  function clamp(v,a,b){v=Number(v);return Number.isFinite(v)?Math.max(a,Math.min(b,v)):a;}
  function el(tag,cls,html){var n=document.createElement(tag);if(cls)n.className=cls;if(html!==undefined)n.innerHTML=html;return n;}
  function sanitizeName(s){return String(s||"").replace(/[^A-Za-z0-9 _-]/g,"").slice(0,12).trim();}
  function announce(text){var v4=window.__MBM_TITAN_V4__;if(v4&&v4.announce)v4.announce(text);}
  function reduced(){return !!(window.matchMedia&&window.matchMedia("(prefers-reduced-motion: reduce)").matches)||!!document.querySelector(".game-shell.reduced-motion");}
  /* ---------- record (the only thing that survives a reload) ---------- */
  function fresh(){return {schema:1,name:"",wins:0,losses:0,bestPower:0,lastOpponent:"",updatedAt:Date.now()};}
  function load(){var b=fresh();try{var r=JSON.parse(localStorage.getItem(KEY)||"null");if(r&&typeof r==="object"){b.name=sanitizeName(r.name);b.wins=clamp(r.wins,0,1e7);b.losses=clamp(r.losses,0,1e7);b.bestPower=clamp(r.bestPower,0,1e9);b.lastOpponent=sanitizeName(r.lastOpponent);}}catch(e){}return b;}
  var record=load();
  function persist(){record.updatedAt=Date.now();try{localStorage.setItem(KEY,JSON.stringify(record));}catch(e){}}
  /* ---------- share-code codec: minimal SDP fields, deflate-raw, base64url ---------- */
  function b64url(bytes){var s="";for(var i=0;i<bytes.length;i++)s+=String.fromCharCode(bytes[i]);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
  function unb64url(str){str=String(str).replace(/-/g,"+").replace(/_/g,"/");while(str.length%4)str+="=";var s=atob(str),out=new Uint8Array(s.length);for(var i=0;i<s.length;i++)out[i]=s.charCodeAt(i);return out;}
  function deflate(bytes){if(!window.CompressionStream)return Promise.resolve(null);try{var cs=new CompressionStream("deflate-raw"),w=cs.writable.getWriter();w.write(bytes);w.close();return new Response(cs.readable).arrayBuffer().then(function(b){return new Uint8Array(b);}).catch(function(){return null;});}catch(e){return Promise.resolve(null);}}
  function inflate(bytes){var ds=new DecompressionStream("deflate-raw"),w=ds.writable.getWriter();w.write(bytes);w.close();return new Response(ds.readable).arrayBuffer().then(function(b){return new Uint8Array(b);});}
  function encodeCode(fields){var raw=new TextEncoder().encode(fields.join("~"));return deflate(raw).then(function(z){return (z&&z.length<raw.length)?"TZ"+b64url(z):"TR"+b64url(raw);});}
  function decodeCode(code){code=String(code||"").trim().replace(/\s+/g,"");var m=code.match(/#duel=([A-Za-z0-9_-]+)/);if(m)code=m[1];if(!/^T[ZR][A-Za-z0-9_-]{8,}$/.test(code))return Promise.reject(new Error("BAD_CODE"));var bytes=unb64url(code.slice(2));return (code[1]==="Z"?inflate(bytes):Promise.resolve(bytes)).then(function(b){var f=new TextDecoder().decode(b).split("~");if(f.length<6||(f[0]!=="o"&&f[0]!=="a"))throw new Error("BAD_CODE");return f;});}
  function parseSdp(sdp,extraCands){var ufrag=(sdp.match(/a=ice-ufrag:(\S+)/)||[])[1],pwd=(sdp.match(/a=ice-pwd:(\S+)/)||[])[1],fp=(sdp.match(/a=fingerprint:sha-256 ([0-9A-F:]+)/i)||[])[1],setup=(sdp.match(/a=setup:(\S+)/)||[])[1],cands=[];
    function add(line){var m=line.match(/candidate:(\S+) (\d+) (udp|UDP) (\d+) (\S+) (\d+) typ host/);if(m&&m[2]==="1"){var c=m[5]+":"+m[6];if(cands.indexOf(c)<0)cands.push(c);}}
    sdp.split(/\r?\n/).forEach(add);(extraCands||[]).forEach(add);if(!ufrag||!pwd||!fp)throw new Error("SDP_INCOMPLETE");return {ufrag:ufrag,pwd:pwd,fp:fp,setup:setup,cands:cands};}
  function toFields(role,nick,p){var fpBytes=new Uint8Array(p.fp.split(":").map(function(h){return parseInt(h,16);}));return [role,p.ufrag,p.pwd,b64url(fpBytes),p.setup==="active"?"c":p.setup==="passive"?"p":"a",nick||"RIVAL"].concat(p.cands.slice(0,4));}
  function buildSdp(f){var fp=Array.prototype.map.call(unb64url(f[3]),function(b){return ("0"+b.toString(16).toUpperCase()).slice(-2);}).join(":"),setup=f[4]==="c"?"active":f[4]==="p"?"passive":"actpass",cands=f.slice(6);
    var lines=["v=0","o=- 0 0 IN IP4 127.0.0.1","s=-","t=0 0","a=group:BUNDLE 0","a=msid-semantic: WMS","m=application 9 UDP/DTLS/SCTP webrtc-datachannel","c=IN IP4 0.0.0.0","a=ice-ufrag:"+f[1],"a=ice-pwd:"+f[2],"a=ice-options:trickle","a=fingerprint:sha-256 "+fp,"a=setup:"+setup,"a=mid:0","a=sctp-port:5000","a=max-message-size:262144"];
    cands.forEach(function(c,i){var idx=c.lastIndexOf(":");if(idx<0)return;lines.push("a=candidate:"+(i+1)+" 1 udp "+(2122260223-i*256)+" "+c.slice(0,idx)+" "+c.slice(idx+1)+" typ host generation 0");});
    lines.push("a=end-of-candidates");return lines.join("\r\n")+"\r\n";}
  /* ---------- peer connection ---------- */
  function gather(pc){return new Promise(function(res){var done=false;function fin(){if(!done){done=true;res();}}if(pc.iceGatheringState==="complete")return fin();pc.addEventListener("icegatheringstatechange",function(){if(pc.iceGatheringState==="complete")fin();});setTimeout(fin,ICE_TIMEOUT);});}
  function newSession(role){closeSession(true);var pc=new RTCPeerConnection({iceServers:[]}),s=session={role:role,pc:pc,cands:[],rival:"",connected:false,offset:0,mode:"power",game:null,ended:false,createdAt:performance.now()};
    pc.onicecandidate=function(e){if(e.candidate&&e.candidate.candidate)s.cands.push(e.candidate.candidate);};
    pc.onconnectionstatechange=function(){if(session!==s)return;if(pc.connectionState==="failed"||pc.connectionState==="disconnected")onGone("LOST");};
    if(role==="guest")pc.ondatachannel=function(e){wire(e.channel);};
    return s;}
  function closeSession(silent){if(!session)return;var s=session;session=null;try{if(s.dc)s.dc.close();}catch(e){}try{s.pc.close();}catch(e){}if(s.game)teardownGame(s.game);if(!silent)setStep("lobby");}
  function hostCreate(){var s=newSession("host"),dc=s.pc.createDataChannel("duel",{ordered:true});wire(dc);
    return s.pc.createOffer().then(function(o){return s.pc.setLocalDescription(o);}).then(function(){return gather(s.pc);}).then(function(){var p=parseSdp(s.pc.localDescription.sdp,s.cands);return encodeCode(toFields("o",record.name,p));}).then(function(code){s.offerCode=code;return code;});}
  function guestAnswer(code){return decodeCode(code).then(function(f){if(f[0]!=="o")throw new Error("NOT_OFFER");var s=newSession("guest");s.rival=sanitizeName(f[5]);
    return s.pc.setRemoteDescription({type:"offer",sdp:buildSdp(f)}).then(function(){return s.pc.createAnswer();}).then(function(a){return s.pc.setLocalDescription(a);}).then(function(){return gather(s.pc);}).then(function(){var p=parseSdp(s.pc.localDescription.sdp,s.cands);return encodeCode(toFields("a",record.name,p));}).then(function(ans){s.answerCode=ans;return ans;});});}
  function hostAccept(code){var s=session;if(!s||s.role!=="host")return Promise.reject(new Error("NO_HOST"));return decodeCode(code).then(function(f){if(f[0]!=="a")throw new Error("NOT_ANSWER");s.rival=sanitizeName(f[5]);s.acceptAt=performance.now();return s.pc.setRemoteDescription({type:"answer",sdp:buildSdp(f)});});}
  function send(msg){var s=session;if(!s||!s.dc||s.dc.readyState!=="open")return false;try{s.dc.send(JSON.stringify(msg));return true;}catch(e){return false;}}
  function hostNow(){var s=session;return Date.now()+(s&&s.role==="guest"?s.offset:0);}
  function wire(dc){var s=session;s.dc=dc;dc.onopen=function(){if(session!==s)return;s.connected=true;s.openedAt=performance.now();s.openMs=Math.round(s.openedAt-(s.acceptAt||s.createdAt));send({t:"hello",name:record.name,ht:Date.now()});setStep("ready");status("CONNECTED"+(s.rival?" TO "+s.rival:""));};
    dc.onmessage=function(e){if(session!==s)return;var m;try{m=JSON.parse(e.data);}catch(err){return;}onMessage(m);};
    dc.onclose=function(){if(session===s)onGone("LEFT");};dc.onerror=function(){};}
  function onMessage(m){var s=session;if(!s||!m)return;
    if(m.t==="hello"){s.rival=sanitizeName(m.name)||s.rival||"RIVAL";if(s.role==="guest")s.offset=clamp(m.ht,0,8.64e15)-Date.now();status("CONNECTED TO "+s.rival);paintReady();return;}
    if(m.t==="start"&&s.role==="guest"){beginGame(m.mode==="form"?"form":"power",clamp(m.at,0,8.64e15)-s.offset,clamp(m.dur,1000,120000));return;}
    if(m.t==="leave"){onGone("LEFT");return;}
    if(!s.game)return;var g=s.game;
    if(m.t==="lift"&&g.mode==="power"){var ht=clamp(m.ht,0,8.64e15);if(ht>=g.atHost&&ht<=g.atHost+g.dur){g.them+=clamp(m.power,0,1000);g.themLifts++;paintHud();}return;}
    if(m.t==="end"&&g.mode==="power"){g.themFinal=clamp(m.total,0,1e9);return;}
    if(m.t==="score"&&g.mode==="form"){var r=clamp(m.round,1,999);if(r!==g.round)return;g.themScore=clamp(m.score,0,6);resolveRound();return;}}
  function onGone(kind){var s=session;if(!s||s.leaving)return;var last=s.lastResult||null;closeSession(true);showResult({left:true,kind:kind,last:last});}
  /* ---------- game modes ---------- */
  function modeBtn(){return document.querySelector(".mbm-mode-btn");}
  function setAdvanced(want){var b=modeBtn();if(!b)return;var is=b.getAttribute("aria-pressed")==="true";if(is!==want)b.click();}
  function beginGame(mode,atLocal,dur){var s=session;if(!s||s.game)return;var wasAdvanced=!!(modeBtn()&&modeBtn().getAttribute("aria-pressed")==="true");
    var g=s.game={mode:mode,at:atLocal,atHost:atLocal+(s.role==="guest"?s.offset:0),dur:dur,me:0,them:0,meLifts:0,themLifts:0,round:1,meRounds:0,themRounds:0,meScore:null,themScore:null,wasAdvanced:wasAdvanced,timers:[],done:false};
    setAdvanced(mode==="form");refs.dialog.hidden=true;refs.hud.hidden=false;try{window.scrollTo({top:0,behavior:reduced()?"auto":"smooth"});}catch(e){window.scrollTo(0,0);}refs.hudThemName.textContent=s.rival||"RIVAL";refs.hudMeName.textContent=record.name||"YOU";
    g.onLift=function(e){var d=e.detail||{},grade=String(d.grade||"SOLID").toUpperCase();if(g.mode!=="power"||g.done)return;var ht=hostNow();if(ht<g.atHost||ht>g.atHost+g.dur)return;var p=POWER[grade]||30;g.me+=p;g.meLifts++;send({t:"lift",ht:ht,grade:grade,power:p});paintHud();};
    g.onForm=function(e){var d=e.detail||{};if(g.mode!=="form"||g.done||g.meScore!==null)return;if(Date.now()<g.at)return;g.meScore=clamp(d.total,0,6);send({t:"score",round:g.round,score:g.meScore});paintHud();resolveRound();};
    window.addEventListener("mbm:titan-lift",g.onLift);window.addEventListener("mbm:titan-form-result",g.onForm);
    g.tick=setInterval(paintHud,200);
    if(mode==="power"){g.timers.push(setTimeout(function(){send({t:"end",total:g.me});},Math.max(0,g.at+g.dur-Date.now())));g.timers.push(setTimeout(function(){finishPower();},Math.max(0,g.at+g.dur+GRACE_MS-Date.now())));}
    announce("DUEL STARTED · "+(mode==="power"?"POWER-OFF 20 SECONDS":"FORM DUEL FIRST TO 3"));paintHud();}
  function teardownGame(g){if(!g)return;window.removeEventListener("mbm:titan-lift",g.onLift);window.removeEventListener("mbm:titan-form-result",g.onForm);clearInterval(g.tick);g.timers.forEach(clearTimeout);if(refs.hud)refs.hud.hidden=true;setAdvanced(g.wasAdvanced);}
  function finishPower(){var s=session;if(!s||!s.game||s.game.done)return;var g=s.game;g.done=true;s.ended=true;var them=g.themFinal!==undefined?g.themFinal:g.them,me=g.me,outcome=me>them?"win":me<them?"loss":"draw";teardownGame(g);s.game=null;settle(outcome,me,them,"POWER");}
  function resolveRound(){var s=session;if(!s||!s.game)return;var g=s.game;if(g.meScore===null||g.themScore===null)return;var me=g.meScore,them=g.themScore;
    if(me===them){announce("ROUND "+g.round+" TIED "+me+" ALL · REPLAY");g.meScore=null;g.themScore=null;paintHud();return;}
    if(me>them)g.meRounds++;else g.themRounds++;announce("ROUND "+g.round+" · YOU "+me+" · "+(s.rival||"RIVAL")+" "+them);g.round++;g.meScore=null;g.themScore=null;paintHud();
    if(g.meRounds>=3||g.themRounds>=3){g.done=true;s.ended=true;var outcome=g.meRounds>=3?"win":"loss",m=g.meRounds,t=g.themRounds;teardownGame(g);s.game=null;settle(outcome,m,t,"FORM");}}
  function settle(outcome,me,them,kind){var s=session,rival=s?s.rival:"";if(outcome==="win"){record.wins++;var v2=window.__MBM_TITAN_MOBILE_V2__;if(v2&&v2.addCrests)v2.addCrests(1);}else if(outcome==="loss")record.losses++;if(kind==="POWER")record.bestPower=Math.max(record.bestPower,me);record.lastOpponent=rival||record.lastOpponent;persist();
    announce("DUEL "+(outcome==="win"?"WON":outcome==="loss"?"LOST":"DRAWN")+" · YOU "+me+" · "+(rival||"RIVAL")+" "+them+(outcome==="win"?" · +1 CREST":""));
    showResult({outcome:outcome,me:me,them:them,kind:kind,rival:rival});if(s){s.ended=true;s.lastResult={me:me,them:them,rival:rival,outcome:outcome};}}
  function paintHud(){var s=session;if(!s||!s.game||!refs.hud)return;var g=s.game,now=Date.now();
    if(g.mode==="power"){var left=g.at+g.dur-now;refs.hudClock.textContent=now<g.at?"GET READY · "+Math.ceil((g.at-now)/1000):left>0?(left/1000).toFixed(1)+"s":"TIME · TALLYING";refs.hudLabel.textContent="POWER-OFF";var max=Math.max(300,g.me,g.them);refs.hudMeBar.style.width=(g.me/max*100)+"%";refs.hudThemBar.style.width=(g.them/max*100)+"%";refs.hudMe.textContent=String(g.me);refs.hudThem.textContent=String(g.them);}
    else{refs.hudClock.textContent=now<g.at?"GET READY · "+Math.ceil((g.at-now)/1000):"ROUND "+g.round+(g.meScore!==null?" · WAITING FOR RIVAL":"");refs.hudLabel.textContent="FORM DUEL · FIRST TO 3";refs.hudMeBar.style.width=(g.meRounds/3*100)+"%";refs.hudThemBar.style.width=(g.themRounds/3*100)+"%";refs.hudMe.textContent=g.meRounds+"/3";refs.hudThem.textContent=g.themRounds+"/3";}}
  /* ---------- UI ---------- */
  function status(text){if(refs.status)refs.status.textContent=text||"";}
  function setStep(name){if(!refs.steps)return;Object.keys(refs.steps).forEach(function(k){refs.steps[k].hidden=k!==name;});if(name==="ready")paintReady();paintRecord();}
  function paintRecord(){if(refs.record)refs.record.textContent="RECORD · "+record.wins+" W · "+record.losses+" L · BEST POWER "+record.bestPower+(record.lastOpponent?" · LAST RIVAL "+record.lastOpponent:"");}
  function paintReady(){var s=session;if(!refs.readyName)return;refs.readyName.textContent=s&&s.rival?s.rival:"RIVAL";refs.startBtn.hidden=!(s&&s.role==="host");refs.waitNote.hidden=!(s&&s.role==="guest");}
  function showResult(r){var box=refs.resultBox;box.innerHTML="";var card=el("div","mbm-v5-result"+(r.left?" mbm-v5-left":""));
    if(r.left){card.innerHTML='<small>CONNECTION CLOSED</small><strong>RIVAL LEFT</strong><p>'+(r.last?'Last result stands: you '+r.last.me+' · '+esc(r.last.rival||'rival')+' '+r.last.them+'.':'No result recorded.')+' Host or join again to reconnect.</p>';}
    else{var title=r.outcome==="win"?"VICTORY":r.outcome==="loss"?"DEFEAT":"DRAW";card.innerHTML='<small>'+(r.kind==="POWER"?"POWER-OFF · 20 S":"FORM DUEL")+'</small><strong>'+title+(r.outcome==="win"?" · +1 CREST":"")+'</strong><div class="mbm-v5-totals"><span>'+esc(record.name||"YOU")+'<b class="mbm-v5-r-me">'+r.me+'</b></span><span>VS</span><span>'+esc(r.rival||"RIVAL")+'<b class="mbm-v5-r-them">'+r.them+'</b></span></div>';}
    var again=el("button","mbm-v5-btn mbm-v5-primary","DUEL AGAIN");again.type="button";again.addEventListener("click",function(){setStep("lobby");status("");});var close=el("button","mbm-v5-btn","CLOSE");close.type="button";close.addEventListener("click",closeDialog);var row=el("div","mbm-v5-row");row.appendChild(again);row.appendChild(close);card.appendChild(row);box.appendChild(card);
    refs.dialog.hidden=false;setStep("result");if(!r.left&&!reduced()){var v4=window.__MBM_TITAN_V4__,st=v4&&v4.getState?v4.getState():{};if(navigator.vibrate&&st.feedback!=="calm")try{navigator.vibrate(r.outcome==="win"?[40,30,80]:30);}catch(e){}}}
  function esc(s){return String(s).replace(/[&<>"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c];});}
  function copyText(text,btn){var done=function(ok){if(btn){var old=btn.getAttribute("data-label")||btn.textContent;btn.setAttribute("data-label",old);btn.textContent=ok?"COPIED":"COPY FAILED";setTimeout(function(){btn.textContent=old;},1400);}};
    if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(text).then(function(){done(true);},function(){fallback();});else fallback();
    function fallback(){try{var ta=document.createElement("textarea");ta.value=text;ta.setAttribute("readonly","");ta.style.position="fixed";ta.style.left="-9999px";document.body.appendChild(ta);ta.select();var ok=document.execCommand("copy");ta.remove();done(ok);}catch(e){done(false);}}}
  function drawQr(canvas,text){var Q=window.__MBM_TITAN_QR__;if(!Q||!canvas)return;try{var scale=Math.max(2,Math.floor(Math.min(300,(innerWidth-60))/(Q.build(text).size+8)));Q.draw(canvas,text,scale);canvas.hidden=false;}catch(e){canvas.hidden=true;}}
  function openDialog(){record.name=sanitizeName(refs.name.value||record.name);refs.name.value=record.name;refs.returnFocus=document.activeElement;refs.dialog.hidden=false;if(!session||!session.connected)setStep(session&&session.game?"ready":"lobby");refs.close.focus();paintRecord();}
  function closeDialog(){refs.dialog.hidden=true;if(refs.returnFocus&&refs.returnFocus.focus)refs.returnFocus.focus();}
  function startHost(){record.name=sanitizeName(refs.name.value)||"HOST";refs.name.value=record.name;persist();setStep("host");status("GATHERING CANDIDATES…");refs.offerOut.value="";refs.answerIn.value="";
    hostCreate().then(function(code){refs.offerOut.value=code;drawQr(refs.hostQr,BASE_URL+"#duel="+code);status("CODE READY · "+code.length+" CHARS · WAITING FOR RIVAL'S ANSWER");listenForAnswer();}).catch(function(e){status("COULD NOT CREATE A CODE · "+(e&&e.message||e));});}
  function startJoin(){record.name=sanitizeName(refs.name.value)||"GUEST";refs.name.value=record.name;persist();setStep("join");status("");refs.answerOut.value="";refs.joinQr.hidden=true;}
  function generateAnswer(code){status("BUILDING ANSWER…");return guestAnswer(code).then(function(ans){refs.answerOut.value=ans;drawQr(refs.joinQr,BASE_URL+"#duel="+ans);status("ANSWER READY · "+ans.length+" CHARS · SEND IT TO THE HOST");return ans;}).catch(function(e){status("THAT CODE DID NOT WORK · "+(e&&e.message||e));throw e;});}
  function connectHost(code){status("CONNECTING…");return hostAccept(code).then(function(){status("ANSWER ACCEPTED · OPENING CHANNEL…");}).catch(function(e){status("THAT ANSWER DID NOT WORK · "+(e&&e.message||e));throw e;});}
  function listenForAnswer(){try{if(!bc&&window.BroadcastChannel){bc=new BroadcastChannel(CHANNEL);bc.onmessage=function(e){var d=e.data||{};if(d.type==="answer"&&d.code)deliverAnswer(d.code);};}}catch(e){}}
  function deliverAnswer(code){var s=session;if(!s||s.role!=="host"||s.connected||!refs.answerIn)return;refs.answerIn.value=code;status("ANSWER RECEIVED FROM THE SCAN · CONNECTING…");connectHost(code).catch(function(){});}
  window.addEventListener("storage",function(e){if(e.key!==SIGNAL_KEY||!e.newValue)return;try{var d=JSON.parse(e.newValue);if(d&&d.code)deliverAnswer(d.code);}catch(err){}});
  function hostStart(){var s=session;if(!s||s.role!=="host"||!s.connected)return;var mode=refs.modeBtns[0].getAttribute("aria-pressed")==="true"?"power":"form",dur=mode==="power"?POWER_MS:0,at=Date.now()+LEAD_MS;send({t:"start",mode:mode,at:at,dur:dur});beginGame(mode,at,dur);}
  function leave(){var s=session;if(s)s.leaving=true;send({t:"leave"});closeSession(true);if(s&&s.game)refs.hud.hidden=true;setStep("lobby");status("YOU LEFT THE DUEL");}
  /* hash path: #duel=<code> opened from a camera-app scan */
  function handleHash(code){decodeCode(code).then(function(f){G.duel.hashHandled=f[0];if(f[0]==="o"){openDialog();startJoin();refs.offerIn.value=code;return generateAnswer(code);}
      var sent=false;try{if(window.BroadcastChannel){new BroadcastChannel(CHANNEL).postMessage({type:"answer",code:code});sent=true;}}catch(e){}
      try{localStorage.setItem(SIGNAL_KEY,JSON.stringify({code:code,ts:Date.now()}));setTimeout(function(){try{localStorage.removeItem(SIGNAL_KEY);}catch(e){}},1500);sent=true;}catch(e){}
      openDialog();refs.resultBox.innerHTML="";var card=el("div","mbm-v5-sent",(sent?"SENT — return to the game":"COULD NOT HAND OVER — paste the code in the host tab")+'<small>The host tab has your answer. You can close this tab.</small>');refs.resultBox.appendChild(card);setStep("result");}).catch(function(){});}
  function injectTrials(){var h2=Array.prototype.find.call(document.querySelectorAll('[role="dialog"] h2'),function(h){return /FORGE TRIALS/i.test(h.textContent);});if(!h2)return;var dlg=h2.closest('[role="dialog"]');if(!dlg||dlg.querySelector(".mbm-v5-rival-btn"))return;
    var head=h2.parentElement,btn=el("button","mbm-v5-btn mbm-v5-primary mbm-v5-rival-btn","RIVAL · LAN DUEL");btn.type="button";btn.setAttribute("aria-label","Forge Rival: duel a friend on the same Wi-Fi");btn.addEventListener("click",function(){leaveTrials(dlg);});head.appendChild(btn);
    var list=dlg.querySelector(".rival-list");if(list){var card=el("article","mbm-v5-duel-card",'<div class="rival-avatar" aria-hidden="true"><svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 20l6-6M14 4l6 6M4 4l16 16"/><path d="M4 9V4h5M15 20h5v-5"/></svg></div><span><small>LAN duel · same Wi-Fi</small><b>Forge Rival</b><em>20 s power-off or first to 3 form rounds</em></span>');var b=el("button","mbm-v5-btn mbm-v5-primary","DUEL");b.type="button";b.setAttribute("aria-label","Start a Forge Rival LAN duel");b.addEventListener("click",function(){leaveTrials(dlg);});card.appendChild(b);list.appendChild(card);}}
  function leaveTrials(dlg){var close=dlg.querySelector("button.absolute");if(close)close.click();setTimeout(openDialog,120);}
  function build(){
    if(built)return true;if(!G.ready||!window.__MBM_TITAN_V4__||!window.__MBM_TITAN_V4__.ready||!document.querySelector(".arena"))return false;
    var dialog=el("div","mbm-v4-dialog mbm-v5-duel-dialog");dialog.hidden=true;dialog.setAttribute("role","dialog");dialog.setAttribute("aria-modal","true");dialog.setAttribute("aria-labelledby","mbm-v5-duel-title");
    dialog.innerHTML='<section class="mbm-v4-dna-panel"><header class="mbm-v4-dna-head"><div><small>LAN DUEL · SAME WI-FI · NO SERVER</small><strong id="mbm-v5-duel-title">FORGE RIVAL</strong></div><button class="mbm-v4-close mbm-v5-close" type="button" aria-label="Close Forge Rival">×</button><span class="mbm-v5-duel-record"></span></header><div class="mbm-v4-dna-scroll">'
      +'<div class="mbm-v5-step" data-step="lobby"><label>NICKNAME · 12 CHARS<input class="mbm-v5-name" maxlength="12" autocomplete="nickname" aria-label="Your duel nickname"></label><div class="mbm-v5-row mbm-v5-modes" role="group" aria-label="Duel mode"><button class="mbm-v5-btn" type="button" aria-pressed="true">POWER-OFF · 20 S</button><button class="mbm-v5-btn" type="button" aria-pressed="false">FORM DUEL · FIRST TO 3</button></div><p>Both phones on the same Wi-Fi. Nothing leaves the network: the codes carry only the connection details.</p><div class="mbm-v5-row"><button class="mbm-v5-btn mbm-v5-primary mbm-v5-host" type="button">HOST</button><button class="mbm-v5-btn mbm-v5-join" type="button">JOIN</button></div></div>'
      +'<div class="mbm-v5-step" data-step="host" hidden><p>1 · Share this code, or let your rival scan the QR with their camera app.</p><textarea class="mbm-v5-offer" readonly aria-label="Your host code"></textarea><button class="mbm-v5-btn mbm-v5-copy" type="button" data-for="offer">COPY CODE</button><canvas class="mbm-v5-qr mbm-v5-host-qr" aria-label="QR code of your host code" hidden></canvas><p>2 · Paste your rival\'s answer code here. If they scanned your QR it arrives by itself.</p><textarea class="mbm-v5-answer-in" aria-label="Rival answer code"></textarea><div class="mbm-v5-row"><button class="mbm-v5-btn mbm-v5-primary mbm-v5-connect" type="button">CONNECT</button><button class="mbm-v5-btn mbm-v5-back" type="button">BACK</button></div></div>'
      +'<div class="mbm-v5-step" data-step="join" hidden><p>1 · Paste the host code.</p><textarea class="mbm-v5-offer-in" aria-label="Host code"></textarea><button class="mbm-v5-btn mbm-v5-primary mbm-v5-generate" type="button">GENERATE ANSWER</button><p>2 · Send this answer back: copy it, or let the host scan the QR.</p><textarea class="mbm-v5-answer" readonly aria-label="Your answer code"></textarea><button class="mbm-v5-btn mbm-v5-copy" type="button" data-for="answer">COPY ANSWER</button><canvas class="mbm-v5-qr mbm-v5-join-qr" aria-label="QR code of your answer code" hidden></canvas><button class="mbm-v5-btn mbm-v5-back" type="button">BACK</button></div>'
      +'<div class="mbm-v5-step" data-step="ready" hidden><p class="mbm-v5-ready-line">CONNECTED TO <strong class="mbm-v5-ready-name">RIVAL</strong></p><button class="mbm-v5-btn mbm-v5-primary mbm-v5-start" type="button">START DUEL</button><p class="mbm-v5-wait" hidden>WAITING FOR THE HOST TO START…</p><button class="mbm-v5-btn mbm-v5-leave" type="button">LEAVE</button></div>'
      +'<div class="mbm-v5-step" data-step="result" hidden><div class="mbm-v5-result-box"></div></div>'
      +'<div class="mbm-v5-duel-status"></div></div></section>';
    document.body.appendChild(dialog);refs.dialog=dialog;refs.close=dialog.querySelector(".mbm-v5-close");refs.record=dialog.querySelector(".mbm-v5-duel-record");refs.status=dialog.querySelector(".mbm-v5-duel-status");refs.name=dialog.querySelector(".mbm-v5-name");refs.name.value=record.name;
    refs.steps={};Array.prototype.forEach.call(dialog.querySelectorAll(".mbm-v5-step"),function(s){refs.steps[s.getAttribute("data-step")]=s;});
    refs.modeBtns=Array.prototype.slice.call(dialog.querySelectorAll(".mbm-v5-modes button"));refs.modeBtns.forEach(function(b,i){b.addEventListener("click",function(){refs.modeBtns.forEach(function(x,j){x.setAttribute("aria-pressed",String(i===j));});});});
    refs.offerOut=dialog.querySelector(".mbm-v5-offer");refs.answerIn=dialog.querySelector(".mbm-v5-answer-in");refs.hostQr=dialog.querySelector(".mbm-v5-host-qr");refs.offerIn=dialog.querySelector(".mbm-v5-offer-in");refs.answerOut=dialog.querySelector(".mbm-v5-answer");refs.joinQr=dialog.querySelector(".mbm-v5-join-qr");refs.readyName=dialog.querySelector(".mbm-v5-ready-name");refs.startBtn=dialog.querySelector(".mbm-v5-start");refs.waitNote=dialog.querySelector(".mbm-v5-wait");refs.resultBox=dialog.querySelector(".mbm-v5-result-box");
    refs.close.addEventListener("click",closeDialog);dialog.addEventListener("click",function(e){if(e.target===dialog)closeDialog();});document.addEventListener("keydown",function(e){if(e.key==="Escape"&&!dialog.hidden){e.stopPropagation();closeDialog();}},true);
    dialog.querySelector(".mbm-v5-host").addEventListener("click",startHost);dialog.querySelector(".mbm-v5-join").addEventListener("click",startJoin);
    Array.prototype.forEach.call(dialog.querySelectorAll(".mbm-v5-back"),function(b){b.addEventListener("click",function(){closeSession(true);setStep("lobby");status("");});});
    Array.prototype.forEach.call(dialog.querySelectorAll(".mbm-v5-copy"),function(b){b.addEventListener("click",function(){copyText((b.getAttribute("data-for")==="offer"?refs.offerOut:refs.answerOut).value,b);});});
    dialog.querySelector(".mbm-v5-generate").addEventListener("click",function(){generateAnswer(refs.offerIn.value).catch(function(){});});
    dialog.querySelector(".mbm-v5-connect").addEventListener("click",function(){connectHost(refs.answerIn.value).catch(function(){});});
    refs.startBtn.addEventListener("click",hostStart);dialog.querySelector(".mbm-v5-leave").addEventListener("click",leave);
    refs.name.addEventListener("change",function(){record.name=sanitizeName(refs.name.value);refs.name.value=record.name;persist();});
    var hud=el("div","mbm-v5-duelhud",'<div class="mbm-v5-clock"><b class="mbm-v5-hud-clock">—</b><span class="mbm-v5-hud-label">DUEL</span></div><div class="mbm-v5-bar mbm-v5-me"><span class="mbm-v5-hud-me-name">YOU</span><i><b></b></i><em class="mbm-v5-hud-me">0</em></div><div class="mbm-v5-bar mbm-v5-them"><span class="mbm-v5-hud-them-name">RIVAL</span><i><b></b></i><em class="mbm-v5-hud-them">0</em></div>');hud.hidden=true;hud.setAttribute("aria-hidden","true");document.querySelector(".arena").appendChild(hud);refs.hud=hud;refs.hudClock=hud.querySelector(".mbm-v5-hud-clock");refs.hudLabel=hud.querySelector(".mbm-v5-hud-label");refs.hudMeName=hud.querySelector(".mbm-v5-hud-me-name");refs.hudThemName=hud.querySelector(".mbm-v5-hud-them-name");refs.hudMeBar=hud.querySelector(".mbm-v5-me i b");refs.hudThemBar=hud.querySelector(".mbm-v5-them i b");refs.hudMe=hud.querySelector(".mbm-v5-hud-me");refs.hudThem=hud.querySelector(".mbm-v5-hud-them");
    if(window.MutationObserver)new MutationObserver(function(){setTimeout(injectTrials,0);}).observe(document.body,{childList:true});injectTrials();
    window.addEventListener("pagehide",function(){send({t:"leave"});});
    built=true;paintRecord();
    var m=(location.hash||"").match(/^#duel=(T[ZR][A-Za-z0-9_-]+)/);if(m){try{history.replaceState(null,"",location.pathname+location.search);}catch(e){location.hash="";}handleHash(m[1]);}
    return true;}
  var tries=0,timer=setInterval(function(){if(build()||++tries>240)clearInterval(timer);},60);
  G.duel={open:function(){if(built)openDialog();},host:function(){return hostCreate();},answer:function(c){return guestAnswer(c);},accept:function(c){return hostAccept(c);},start:hostStart,leave:leave,state:function(){var s=session;return s?{role:s.role,rival:s.rival,connected:s.connected,offset:s.offset,openMs:s.openMs||null,offerLen:s.offerCode?s.offerCode.length:null,answerLen:s.answerCode?s.answerCode.length:null,game:s.game?{mode:s.game.mode,me:s.game.me,them:s.game.them,round:s.game.round,meRounds:s.game.meRounds,themRounds:s.game.themRounds,done:s.game.done}:null,ended:s.ended}:null;},record:function(){return JSON.parse(JSON.stringify(record));},codec:{encode:encodeCode,decode:decodeCode,parseSdp:parseSdp,buildSdp:buildSdp},saveKey:KEY,hashHandled:null,built:function(){return built;}};
})();
