#!/usr/bin/env node

/* Browser acceptance gate for the Titan Forge + Crown & Badge launch.
 *
 * Every family includes a biting control. The generated splash and inline-exit
 * regions have their own canonical verifiers; this file removes only the
 * splash while driving the game so a timed intro cannot mask the product UI.
 */
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const OUT = path.resolve(process.argv[2] || path.join(ROOT, 'artifacts/titan-crown'));
fs.mkdirSync(OUT, { recursive: true });

const SPLASH = /<!-- MBM-SPLASH:BEGIN generated by tools\/render_splash\.py, do not edit by hand -->[\s\S]*?<!-- MBM-SPLASH:END -->\n?/;
const MIME = {
  '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml', '.webp': 'image/webp', '.png': 'image/png',
};
const MAP_COMPARE_FREEZE = '*,*::before,*::after{animation:none!important;transition:none!important;caret-color:transparent!important}';

let pass = 0;
const failures = [];
const metrics = {};
function check(ok, label, detail = '') {
  if (ok) { pass += 1; console.log(`  [PASS] ${label}${detail ? ` · ${detail}` : ''}`); }
  else { failures.push(`${label}${detail ? ` · ${detail}` : ''}`); console.error(`  [FAIL] ${label}${detail ? ` · ${detail}` : ''}`); }
  return ok;
}

function replaceOnce(source, before, after, label) {
  const count = source.split(before).length - 1;
  if (count !== 1) throw new Error(`${label}: expected one source match, found ${count}`);
  return source.replace(before, after);
}

function preFoldSource(source, brokenControl = false) {
  let out = source;
  out = replaceOnce(out,
    '.map-card .frontier-svg{min-width:0;width:100%;left:0;transform:none}',
    '.map-card .frontier-svg{min-width:720px;width:720px;left:50%;transform:translateX(-50%)}',
    'pre-fold 760 map');
  out = replaceOnce(out,
    '.map-nodes{min-width:0;width:100%;left:0;transform:none}',
    '.map-nodes{min-width:720px;width:720px;left:50%;transform:translateX(-50%)}',
    'pre-fold 760 nodes');
  out = replaceOnce(out,
    '.map-card .frontier-svg,.map-nodes{min-width:0;width:100%}',
    '.map-card .frontier-svg,.map-nodes{min-width:660px;width:660px}',
    'pre-fold 430 map');
  const width = brokenControl ? '97%' : '100%';
  const narrowWidth = brokenControl ? '96%' : '100%';
  const trailing = `\n@media(max-width:760px){.map-card .frontier-svg,.map-nodes{min-width:0;width:${width};left:0;transform:none}}\n` +
    `@media(max-width:430px){.map-card .frontier-svg,.map-nodes{min-width:0;width:${narrowWidth}}}\n`;
  return replaceOnce(out, '</style>', `${trailing}</style>`, 'pre-fold trailing patch');
}

const titanSource = fs.readFileSync(path.join(ROOT, 'titanforge/index.html'), 'utf8');
const crownSource = fs.readFileSync(path.join(ROOT, 'crownbadge/index.html'), 'utf8');
const corruptTitan = titanSource.replace(
  /(src:"data:image\/webp;base64,)[A-Za-z0-9+/=]+/,
  '$1UklGRg=='
);
if (corruptTitan === titanSource) throw new Error('corrupt-WebP control did not mutate Titan');

function transformed(pathname, source) {
  if (pathname.startsWith('/__game__/')) return source.replace(SPLASH, '');
  if (pathname.startsWith('/__no_touch__/')) {
    return source.replace(SPLASH, '').replaceAll('touch-action:manipulation', 'touch-action:auto');
  }
  if (pathname.startsWith('/__corrupt__/')) return corruptTitan.replace(SPLASH, '');
  if (pathname.startsWith('/__prefold_control__/')) return preFoldSource(source, true).replace(SPLASH, '');
  if (pathname.startsWith('/__prefold__/')) return preFoldSource(source, false).replace(SPLASH, '');
  return source;
}

function createServer() {
  return new Promise((resolve, reject) => {
    const instance = http.createServer((req, res) => {
      const raw = decodeURIComponent((req.url || '/').split('?')[0]);
      const prefixes = ['/__game__', '/__no_touch__', '/__corrupt__', '/__prefold__', '/__prefold_control__'];
      let pathname = raw;
      for (const prefix of prefixes) if (pathname.startsWith(`${prefix}/`)) pathname = pathname.slice(prefix.length);
      let file = path.resolve(ROOT, pathname.replace(/^\/+/, ''));
      if (!file.startsWith(`${ROOT}${path.sep}`)) { res.writeHead(403).end('forbidden'); return; }
      if (fs.existsSync(file) && fs.statSync(file).isDirectory()) file = path.join(file, 'index.html');
      if (!fs.existsSync(file) || fs.statSync(file).isDirectory()) { res.writeHead(404).end('not found'); return; }
      const ext = path.extname(file);
      res.writeHead(200, { 'Content-Type': MIME[ext] || 'application/octet-stream', 'Cache-Control': 'no-store' });
      if (ext === '.html') res.end(transformed(raw, fs.readFileSync(file, 'utf8')));
      else fs.createReadStream(file).pipe(res);
    });
    instance.once('error', reject);
    instance.listen(0, '127.0.0.1', () => resolve(instance));
  });
}

function playwrightChromium() {
  const require = createRequire(import.meta.url);
  for (const spec of ['playwright', process.env.MBM_PLAYWRIGHT, '/opt/node22/lib/node_modules/playwright'].filter(Boolean)) {
    try {
      const mod = spec === 'playwright' ? require(spec) : require(spec);
      if (mod.chromium) return mod.chromium;
    } catch { /* next */ }
  }
  throw new Error('Playwright is not importable; this browser gate is inconclusive, never green');
}

function sha(buffer) { return createHash('sha256').update(buffer).digest('hex'); }
function visible(box) { return !!box && box.width > 0 && box.height > 0; }
function maxRateHz(times) {
  if (times.length < 2) return times.length ? 1 : 0;
  let min = Infinity;
  for (let i = 1; i < times.length; i++) min = Math.min(min, times[i] - times[i - 1]);
  return min > 0 ? 1000 / min : Infinity;
}

async function trackedPage(browser, origin, route, options = {}) {
  const context = await browser.newContext({
    viewport: options.viewport || { width: 390, height: 844 },
    hasTouch: options.touch !== false,
    isMobile: options.mobile !== false,
    reducedMotion: options.reduced ? 'reduce' : 'no-preference',
  });
  const offOrigin = [];
  const failed = [];
  const errors = [];
  await context.route('**/*', async routeHandle => {
    const requestUrl = routeHandle.request().url();
    if (requestUrl.startsWith(origin)) await routeHandle.continue();
    else { offOrigin.push(requestUrl); await routeHandle.abort('blockedbyclient'); }
  });
  const page = await context.newPage();
  page.on('requestfailed', request => failed.push(`${request.method()} ${request.url()} ${request.failure()?.errorText || ''}`));
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(`console: ${message.text()}`); });
  await page.goto(`${origin}${route}`, { waitUntil: 'domcontentloaded', timeout: 45000 });
  return { context, page, offOrigin, failed, errors };
}

async function closeTracked(track, label) {
  check(track.offOrigin.length === 0, `${label}: 0 off-origin requests`, track.offOrigin.slice(0, 2).join(' | '));
  check(track.failed.length === 0, `${label}: 0 failed requests`, track.failed.slice(0, 2).join(' | '));
  check(track.errors.length === 0, `${label}: console and page errors are clean`, track.errors.slice(0, 2).join(' | '));
  await track.context.close();
}

async function waitTitan(track, label = 'Titan') {
  const { page } = track;
  try {
    await page.locator('.lift-button').waitFor({ state: 'visible', timeout: 20000 });
    await page.locator('.avatar-placeholder img').waitFor({ state: 'visible', timeout: 10000 });
  } catch (error) {
    const state = await page.evaluate(() => ({
      title: document.title,
      readyState: document.readyState,
      rootPresent: !!document.querySelector('#game-root'),
      rootChildren: document.querySelector('#game-root')?.childElementCount || 0,
      liftCount: document.querySelectorAll('.lift-button').length,
      bodyChildren: document.body?.childElementCount || 0,
      bodyText: (document.body?.innerText || '').trim().slice(0, 240),
    })).catch(evaluateError => ({ evaluateError: evaluateError.message }));
    const shot = path.join(OUT, 'titan-boot-failure.png');
    await page.screenshot({ path: shot, fullPage: false }).catch(() => {});
    const detail = { state, offOrigin: track.offOrigin, failed: track.failed, errors: track.errors };
    console.error(`[BOOT DIAGNOSTIC] ${label}: ${JSON.stringify(detail)}`);
    throw new Error(`${label} did not reach a playable mount: ${error.message}`);
  }
}

async function titanImageState(page) {
  return page.evaluate(async () => {
    const athlete = document.querySelector('.avatar-placeholder img');
    const bgUrl = [...document.querySelectorAll('*')].map(el => getComputedStyle(el).backgroundImage)
      .find(value => value && value.includes('data:image/webp;base64,'));
    let background = { painted: false, width: 0, height: 0 };
    if (bgUrl) {
      const match = bgUrl.match(/url\(["']?(data:image\/webp;base64,[A-Za-z0-9+/=]+)["']?\)/);
      if (match) background = await new Promise(resolve => {
        const image = new Image();
        image.onload = () => resolve({ painted: true, width: image.naturalWidth, height: image.naturalHeight });
        image.onerror = () => resolve({ painted: false, width: 0, height: 0 });
        image.src = match[1];
      });
    }
    return {
      athlete: { painted: !!athlete && athlete.complete && athlete.naturalWidth > 0, width: athlete?.naturalWidth || 0, height: athlete?.naturalHeight || 0 },
      background,
    };
  });
}

async function interactiveSizes(page) {
  return page.evaluate(() => [...document.querySelectorAll('button,a[href],input,select,textarea,[role="button"],[role="switch"]')]
    .map((el, index) => {
      const rect = el.getBoundingClientRect();
      const css = getComputedStyle(el);
      return { index, tag: el.tagName, text: (el.getAttribute('aria-label') || el.textContent || '').trim().slice(0, 42), width: rect.width, height: rect.height,
        visible: rect.width > 0 && rect.height > 0 && css.display !== 'none' && css.visibility !== 'hidden' };
    }).filter(item => item.visible && (item.width < 44 || item.height < 44)));
}

async function startCrown(subject, seed = 'QA-FRONTIER') {
  const track = subject.page ? subject : null;
  const page = track ? track.page : subject;
  try {
    await page.locator('#seedInput').waitFor({ state: 'visible', timeout: 15000 });
    await page.locator('#seedInput').fill(seed);
    await page.locator('#newCampaignBtn').click();
    await page.waitForFunction(() => document.querySelector('#intro')?.hidden === true, null, { timeout: 10000 });
    await page.locator('#mapCard').waitFor({ state: 'visible', timeout: 10000 });
  } catch (error) {
    const state = await page.evaluate(() => ({
      title: document.title,
      readyState: document.readyState,
      introHidden: document.querySelector('#intro')?.hidden,
      mapVisible: (() => { const node = document.querySelector('#mapCard'); const rect = node?.getBoundingClientRect(); return !!rect && rect.width > 0 && rect.height > 0; })(),
      seed: document.querySelector('#seedInput')?.value,
      campaignSaved: !!localStorage.getItem('mbm_crownbadge_campaign_v1'),
      testApi: !!window.__MBM_CROWN_TEST__,
      bodyText: (document.body?.innerText || '').trim().slice(0, 240),
    })).catch(evaluateError => ({ evaluateError: evaluateError.message }));
    await page.screenshot({ path: path.join(OUT, 'crown-start-failure.png'), fullPage: false }).catch(() => {});
    const detail = { state, offOrigin: track?.offOrigin || [], failed: track?.failed || [], errors: track?.errors || [] };
    console.error(`[BOOT DIAGNOSTIC] Crown ${seed}: ${JSON.stringify(detail)}`);
    throw new Error(`Crown ${seed} did not start a campaign: ${error.message}`);
  }
}

async function runTitan(browser, origin) {
  console.log('\n=== TITAN FORGE · RENDER, INPUT, SAVE, MOTION ===\n');
  for (const viewport of [{ width: 390, height: 844 }, { width: 1280, height: 800 }]) {
    const mobile = viewport.width < 600;
    const t = await trackedPage(browser, origin, '/__game__/titanforge/', { viewport, touch: mobile, mobile });
    await waitTitan(t, `Titan ${viewport.width}x${viewport.height}`);
    const images = await titanImageState(t.page);
    check(images.athlete.painted, `Titan ${viewport.width}×${viewport.height}: athlete WebP paints`, `${images.athlete.width}×${images.athlete.height}`);
    check(images.background.painted, `Titan ${viewport.width}×${viewport.height}: background WebP paints`, `${images.background.width}×${images.background.height}`);
    const shot = path.join(OUT, `titan-${viewport.width}x${viewport.height}.png`);
    await t.page.screenshot({ path: shot, fullPage: false });
    if (mobile) {
      const sizes = await interactiveSizes(t.page);
      check(sizes.length === 0, 'Titan 390px: 0 visible controls under 44px', JSON.stringify(sizes.slice(0, 4)));
      const actions = await t.page.locator('button').evaluateAll(buttons => buttons.filter(button => {
        const r = button.getBoundingClientRect(); return r.width > 0 && r.height > 0;
      }).map(button => getComputedStyle(button).touchAction));
      check(actions.length > 0 && actions.every(value => value === 'manipulation'), 'Titan: every visible button computes touch-action: manipulation', `${actions.length} buttons`);
      await t.page.locator('.lift-button').click();
    }
    await closeTracked(t, `Titan ${viewport.width}×${viewport.height} self-contained boot`);
  }

  const corrupt = await trackedPage(browser, origin, '/__corrupt__/titanforge/');
  await waitTitan(corrupt, 'Titan corrupt-WebP control');
  const corruptState = await titanImageState(corrupt.page);
  check(Buffer.byteLength(corruptTitan) < 1_000_000, 'CONTROL: corrupt Titan remains below the size ceiling', `${Buffer.byteLength(corruptTitan)} B`);
  check(!corruptState.athlete.painted, 'CONTROL: corrupt athlete makes the render predicate red', `${corruptState.athlete.width}×${corruptState.athlete.height}`);
  await corrupt.context.close();

  const noTouch = await trackedPage(browser, origin, '/__no_touch__/titanforge/');
  await waitTitan(noTouch, 'Titan no-touch control');
  const noTouchValue = await noTouch.page.locator('.lift-button').evaluate(el => getComputedStyle(el).touchAction);
  check(noTouchValue !== 'manipulation', 'CONTROL: removing touch-action makes the computed-style predicate red', noTouchValue);
  await noTouch.context.close();

  const save = await trackedPage(browser, origin, '/__game__/titanforge/');
  await waitTitan(save, 'Titan hostile-save path');
  const hostile = await save.page.evaluate(() => {
    const api = window.__MBM_TITAN_TEST__;
    const cases = [
      ['truncated JSON', '{"strength":'],
      ['wrong types', JSON.stringify({ strength: '12', coins: [], sound: 'yes' })],
      ['negative numbers', JSON.stringify({ strength: -900, coins: -4, reps: -2 })],
      ['null arrays', JSON.stringify({ purchased: null, claimedQuests: null, attemptedTrials: null })],
      ['Infinity', '{"strength":1e309,"coins":1e309}'],
      ['10 MB string', 'x'.repeat(10 * 1024 * 1024)],
      ['object number', JSON.stringify({ strength: { value: 12 }, gems: { value: 3 } })],
    ];
    const playable = state => state && Number.isFinite(state.strength) && state.strength >= 1 && Number.isFinite(state.coins) &&
      Array.isArray(state.purchased) && state.purchased.includes(0) && Array.isArray(state.claimedQuests) && Array.isArray(state.attemptedTrials);
    return cases.map(([name, raw]) => ({ name, playable: playable(api.loadState(raw)) }));
  });
  check(hostile.length === 7 && hostile.every(row => row.playable), 'Titan: all 7 hostile save blobs sanitise to playable state', JSON.stringify(hostile));
  const titanExpected = await save.page.evaluate(() => {
    const key = 'mbm_titanforge_save_v1';
    const expected = window.__MBM_TITAN_TEST__.sanitizeState({ strength: 4321.5, coins: 9876, gems: 44, reps: 432, perfects: 300,
      bestCombo: 25, ascensions: 2, equipped: 3, purchased: [0, 1, 2, 3], zone: 2, claimedQuests: [0, 2],
      lastDaily: '2026-08-27', attemptedTrials: [0, 2], starterTier: 2, windowLevel: 2, comboLevel: 1, sound: false, reducedMotion: true });
    localStorage.setItem(key, JSON.stringify(expected));
    return expected;
  });
  await save.page.reload({ waitUntil: 'domcontentloaded' });
  await waitTitan(save, 'Titan save reload');
  await save.page.waitForTimeout(350);
  const titanActual = await save.page.evaluate(() => JSON.parse(localStorage.getItem('mbm_titanforge_save_v1') || 'null'));
  check(JSON.stringify(titanActual) === JSON.stringify(titanExpected), 'Titan: a shipped save reloads lossless');
  await closeTracked(save, 'Titan hostile-save and roundtrip path');

  const motion = await trackedPage(browser, origin, '/__game__/titanforge/');
  await waitTitan(motion, 'Titan full-motion path');
  const aura = await motion.page.locator('.power-aura').evaluate(el => ({ name: getComputedStyle(el).animationName, duration: getComputedStyle(el).animationDuration }));
  const seconds = Number.parseFloat(aura.duration) || 0;
  metrics.titanAuraHz = seconds ? 1 / seconds : 0;
  check(aura.name !== 'none' && metrics.titanAuraHz < 3, 'Titan full-motion aura remains below 3 Hz', `${metrics.titanAuraHz.toFixed(4)} Hz (${aura.duration})`);
  await motion.context.close();

  const reduced = await trackedPage(browser, origin, '/__game__/titanforge/', { reduced: true });
  await waitTitan(reduced, 'Titan reduced-motion path');
  const reducedState = await reduced.page.evaluate(async () => {
    const shell = document.querySelector('.game-shell');
    const aura = document.querySelector('.power-aura');
    const needle = document.querySelector('.meter-needle');
    const one = getComputedStyle(needle).left;
    await new Promise(resolve => setTimeout(resolve, 220));
    const two = getComputedStyle(needle).left;
    return { classFloor: shell?.classList.contains('reduced-motion'), aura: getComputedStyle(aura).animationName, one, two };
  });
  check(reducedState.classFloor && reducedState.aura === 'none', 'Titan OS reduced motion is a floor and suppresses decorative aura', JSON.stringify(reducedState));
  check(reducedState.one !== reducedState.two, 'Titan timing meter remains gameplay motion under reduced motion', `${reducedState.one} → ${reducedState.two}`);
  await reduced.context.close();
}

async function runCrown(browser, origin) {
  console.log('\n=== CROWN & BADGE · PHONE SURFACES, SAVE, FLASH, MAP FOLD ===\n');
  for (const viewport of [{ width: 390, height: 844 }, { width: 1280, height: 800 }]) {
    const mobile = viewport.width < 600;
    const t = await trackedPage(browser, origin, '/__game__/crownbadge/', { viewport, touch: mobile, mobile });
    await startCrown(t, `QA-${viewport.width}`);
    const shot = path.join(OUT, `crown-${viewport.width}x${viewport.height}.png`);
    await t.page.screenshot({ path: shot, fullPage: false });
    if (mobile) {
      const surface = await t.page.evaluate(() => {
        const read = selector => { const el = document.querySelector(selector); const rect = el?.getBoundingClientRect(); return { text: el?.textContent?.trim() || '', visible: !!rect && rect.width > 0 && rect.height > 0 && getComputedStyle(el).display !== 'none', width: rect?.width || 0, height: rect?.height || 0 }; };
        return { goal: read('#mobileGoalProgress'), ledger: read('#endDayLedger'), valor: read('#valorVal') };
      });
      check(surface.goal.visible && /\d+\/3 secured/.test(surface.goal.text), 'Crown 390px: objective progress is visible and non-zero-sized', JSON.stringify(surface.goal));
      check(surface.ledger.visible && /Tomorrow: [+-]\d+G · [+-]\d+S/.test(surface.ledger.text), 'Crown 390px: daily net ledger is visible and non-zero-sized', JSON.stringify(surface.ledger));
      check(surface.valor.visible, 'Crown 390px: Valor remains visible', JSON.stringify(surface.valor));
      const sizes = await interactiveSizes(t.page);
      check(sizes.length === 0, 'Crown 390px: 0 visible controls under 44px', JSON.stringify(sizes.slice(0, 5)));

      await t.page.addStyleTag({ content: '#mobileGoalProgress{display:none!important}' });
      const hiddenGoal = await t.page.locator('#mobileGoalProgress').evaluate(el => { const r = el.getBoundingClientRect(); return r.width > 0 && r.height > 0; });
      check(!hiddenGoal, 'CONTROL: hiding the phone objective makes its visibility predicate red');
      await t.page.addStyleTag({ content: '#endDayLedger{display:none!important}' });
      const hiddenLedger = await t.page.locator('#endDayLedger').evaluate(el => { const r = el.getBoundingClientRect(); return r.width > 0 && r.height > 0; });
      check(!hiddenLedger, 'CONTROL: hiding the daily ledger makes its visibility predicate red');
    }
    await closeTracked(t, `Crown ${viewport.width}×${viewport.height} self-contained boot`);
  }

  const save = await trackedPage(browser, origin, '/__game__/crownbadge/');
  await startCrown(save, 'LOSSLESS-CROWN');
  const crownWritten = await save.page.evaluate(() => {
    const key = 'mbm_crownbadge_campaign_v1';
    return JSON.parse(localStorage.getItem(key) || 'null');
  });
  await save.page.reload({ waitUntil: 'domcontentloaded' });
  await save.page.locator('#continueBtn').waitFor({ state: 'visible', timeout: 10000 });
  await save.page.waitForTimeout(350);
  const crownLoaded = await save.page.evaluate(() => window.__MBM_CROWN_TEST__?.snapshot().state || null);
  check(JSON.stringify(crownLoaded) === JSON.stringify(crownWritten), 'Crown: a save written by the shipped build reloads lossless');
  await closeTracked(save, 'Crown save roundtrip path');

  const flash = await trackedPage(browser, origin, '/__game__/crownbadge/');
  await startCrown(flash, 'FLASH-RATE');
  const times = await flash.page.evaluate(async () => {
    const times = [];
    const observer = new MutationObserver(() => {
      if (document.body.classList.contains('flash-good') || document.body.classList.contains('flash-bad')) {
        const now = performance.now(); if (!times.length || now - times[times.length - 1] > 5) times.push(now);
      }
    });
    observer.observe(document.body, { attributes: true, attributeFilter: ['class'] });
    const timer = setInterval(() => window.__MBM_CROWN_TEST__.pulse(), 25);
    await new Promise(resolve => setTimeout(resolve, 2300));
    clearInterval(timer); observer.disconnect(); return times;
  });
  metrics.crownFlashHz = maxRateHz(times);
  check(times.length >= 3 && metrics.crownFlashHz < 3, 'Crown full-screen flash peak remains below 3 Hz', `${metrics.crownFlashHz.toFixed(4)} Hz across ${times.length} accepted pulses`);
  await flash.context.close();

  const reduced = await trackedPage(browser, origin, '/__game__/crownbadge/', { reduced: true });
  await startCrown(reduced, 'REDUCED-FLOOR');
  const reducedMotion = await reduced.page.evaluate(async () => {
    const before = document.body.className;
    for (let i = 0; i < 20; i++) window.__MBM_CROWN_TEST__.pulse();
    await new Promise(resolve => setTimeout(resolve, 100));
    const node = document.querySelector('.map-node'); node?.classList.add('critical');
    return { reduced: window.__MBM_CROWN_TEST__.snapshot().settings.reduced, flashed: /flash-(good|bad)/.test(document.body.className), nodeAnimation: node ? getComputedStyle(node).animationName : '' , before };
  });
  check(reducedMotion.reduced && !reducedMotion.flashed, 'Crown reduced motion suppresses celebratory full-screen flashes', JSON.stringify(reducedMotion));
  check(reducedMotion.nodeAnimation === 'node-bob', 'Crown map-node gameplay motion remains active under reduced motion', reducedMotion.nodeAnimation);
  metrics.crownReducedFlashHz = 0;
  await reduced.context.close();

  const hashes = {};
  for (const width of [390, 430, 760, 980]) {
    const context = await browser.newContext({ viewport: { width, height: 844 }, reducedMotion: 'reduce' });
    await context.addInitScript(() => localStorage.setItem('mbm_crownbadge_settings_v1', JSON.stringify({ muted: true, volume: 0, reduced: true, weather: 'clear' })));
    const after = await context.newPage();
    const before = await context.newPage();
    await after.goto(`${origin}/__game__/crownbadge/`, { waitUntil: 'domcontentloaded' });
    await before.goto(`${origin}/__prefold__/crownbadge/`, { waitUntil: 'domcontentloaded' });
    await startCrown(after, `FOLD-${width}`); await startCrown(before, `FOLD-${width}`);
    await Promise.all([after.addStyleTag({ content: MAP_COMPARE_FREEZE }), before.addStyleTag({ content: MAP_COMPARE_FREEZE })]);
    await after.waitForTimeout(60);
    const a = await after.locator('#mapCard').screenshot();
    const b = await before.locator('#mapCard').screenshot();
    hashes[width] = { after: sha(a), before: sha(b) };
    check(Buffer.compare(a, b) === 0, `Crown map fold ${width}px: rendered pixels are byte-identical`, hashes[width].after.slice(0, 16));
    await context.close();
  }
  metrics.mapFoldHashes = hashes;

  const controlContext = await browser.newContext({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' });
  await controlContext.addInitScript(() => localStorage.setItem('mbm_crownbadge_settings_v1', JSON.stringify({ muted: true, volume: 0, reduced: true, weather: 'clear' })));
  const good = await controlContext.newPage(); const bad = await controlContext.newPage();
  await good.goto(`${origin}/__game__/crownbadge/`, { waitUntil: 'domcontentloaded' });
  await bad.goto(`${origin}/__prefold_control__/crownbadge/`, { waitUntil: 'domcontentloaded' });
  await startCrown(good, 'FOLD-CONTROL'); await startCrown(bad, 'FOLD-CONTROL');
  await Promise.all([good.addStyleTag({ content: MAP_COMPARE_FREEZE }), bad.addStyleTag({ content: MAP_COMPARE_FREEZE })]);
  await good.waitForTimeout(60);
  const goodPixels = await good.locator('#mapCard').screenshot(); const badPixels = await bad.locator('#mapCard').screenshot();
  check(Buffer.compare(goodPixels, badPixels) !== 0, 'CONTROL: changing the restored trailing map width makes pixel identity red');
  await controlContext.close();
}

const instance = await createServer();
const origin = `http://127.0.0.1:${instance.address().port}`;
let browser;
let fatal = null;
try {
  const chromium = playwrightChromium();
  const executablePath = chromium.executablePath();
  browser = await chromium.launch({ headless: true, ...(executablePath && fs.existsSync(executablePath) ? { executablePath } : {}) });
  await runTitan(browser, origin);
  await runCrown(browser, origin);
} catch (error) {
  fatal = error instanceof Error ? `${error.name}: ${error.message}\n${error.stack || ''}` : String(error);
  failures.push(`browser harness fatal: ${fatal}`);
  console.error(fatal);
} finally {
  if (browser) await browser.close();
  await new Promise(resolve => instance.close(resolve));
}

fs.writeFileSync(path.join(OUT, 'browser-metrics.json'), JSON.stringify({ pass, failures, metrics, fatal }, null, 2) + '\n');
console.log(`\nbrowser launch contract: ${pass}/${pass + failures.length} passed`);
if (failures.length) {
  console.error(`${failures.length} FAILED`);
  process.exit(1);
}
