/* Real transfer UI, production assets, two isolated mapped HTTPS origins.
 * Fixture save bytes test transfer safety, not the game engine's save parser. */
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const base=process.env.PLAY_REVIEW_URL||'http://127.0.0.1:4173',out=path.resolve('.play-review/save-ui');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome'}),context=await browser.newContext({acceptDownloads:true});
await context.route(/^https:\/\/www\.madebymatt(?:-play)?\.uk\//,async route=>{const url=new URL(route.request().url());const response=await context.request.get(base+url.pathname+url.search);await route.fulfill({response});});
const page=await context.newPage();await page.goto('https://www.madebymatt.uk/game-saves/');await page.locator('#save-export:not([disabled])').waitFor();
await page.evaluate(()=>{localStorage.setItem('cyberpulse_blackout_v1','PLAY-QA-SOURCE-BYTES');localStorage.setItem('mbm_play_favourites_v1','["game-emberwild"]');});
assert(!await page.locator('#import-area').isVisible());const downloadPromise=page.waitForEvent('download');await page.locator('#save-export').click();const exported=await downloadPromise,saveFile=path.join(out,'fixture-export.json');await exported.saveAs(saveFile);const data=JSON.parse(fs.readFileSync(saveFile));assert.equal(data.localStorage.cyberpulse_blackout_v1,'PLAY-QA-SOURCE-BYTES');assert(!JSON.stringify(data).includes('game-emberwild'));assert.equal(await page.evaluate(()=>localStorage.getItem('cyberpulse_blackout_v1')),'PLAY-QA-SOURCE-BYTES');
await page.goto('https://www.madebymatt-play.uk/game-saves/');await page.locator('#import-area:not([hidden])').waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('cyberpulse_blackout_v1')),null,'Origins unexpectedly shared storage');
await page.evaluate(()=>localStorage.setItem('cyberpulse_blackout_v1','PLAY-QA-DESTINATION-BYTES'));await page.locator('#save-file').setInputFiles(saveFile);await page.locator('#save-import').click();await page.waitForFunction(()=>document.querySelector('#save-status').textContent.startsWith('Imported'));assert.equal(await page.evaluate(()=>localStorage.getItem('cyberpulse_blackout_v1')),'PLAY-QA-DESTINATION-BYTES');
await page.locator('#save-file').setInputFiles(saveFile);await page.locator('#save-overwrite').check();const backupPromise=page.waitForEvent('download');await page.locator('#save-import').click();const backup=await backupPromise,backupFile=path.join(out,'fixture-before-import.json');await backup.saveAs(backupFile);await page.waitForFunction(()=>document.querySelector('#save-status').textContent.startsWith('Imported'));assert.equal(JSON.parse(fs.readFileSync(backupFile)).localStorage.cyberpulse_blackout_v1,'PLAY-QA-DESTINATION-BYTES');assert.equal(await page.evaluate(()=>localStorage.getItem('cyberpulse_blackout_v1')),'PLAY-QA-SOURCE-BYTES');
await page.screenshot({path:path.join(out,'transfer-ui.png')});fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({pass:true,scope:'Production transfer UI on mapped isolated HTTPS test origins; fixture byte round trip, not live-user saves.',download:true,sourcePreserved:true,originIsolation:true,discoveryListsExcluded:true,existingSaveKept:true,replacementBackup:true,replacementImport:true},null,2));await browser.close();})().catch(e=>{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({pass:false,error:e.stack},null,2));console.error(e);process.exit(1);});
