/* Repository browser acceptance for the Play overlay. Every check records its
 * actual scope; route-start sampling is not a full playthrough of 69 engines.
 * UX2 C4 (2026-09-08): re-pinned to the one-DOM shelf — a server-rendered
 * "All games" grid (every catalogue game exactly once, series collapsed), a
 * static Featured card, lanes rendered from the inline data, a Filters drawer
 * and a game sheet. Counts are derived from play-discovery.json, never typed;
 * the grid-coverage limb carries its own planted-defect control so a green
 * here is a proof, not a vacancy. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const base=process.env.PLAY_REVIEW_URL||'http://127.0.0.1:4173',out=path.resolve('.play-review/qa'),root=path.resolve('.play-review/output');fs.mkdirSync(out,{recursive:true});
const data=JSON.parse(fs.readFileSync(path.join(root,'games/data/play-discovery.json'))),build=JSON.parse(fs.readFileSync(path.join(root,'build-report.json')));
const preserved=JSON.parse(fs.readFileSync('reports/play-upgrade/preservation.json')),baselineHashes=new Map(preserved.payloads.map(p=>[p.path,p.published_sha256]));
// Re-derive approved source revisions from the actual checkouts before accepting HTTP bytes.
const selectedRevisions=JSON.parse(require('node:child_process').execFileSync('python3',['domain-split/play/source_revisions.py','--output',root],{encoding:'utf8'}));
for(const [route,revision] of Object.entries(selectedRevisions))baselineHashes.set(route,revision.published_sha256);
const report={date:new Date().toISOString(),checks:[],sourceRevisions:selectedRevisions,routes:[],limitations:['Route coverage proves initial rendered state and available input surface, not completion of every game.','Source-supported control labels do not certify physical gamepad, real-device performance or two-device local pairing.'],errors:[]};
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
let currentPage=null;
const pause=ms=>new Promise(r=>setTimeout(r,ms));
// Populations, derived from the data the page was built from.
const catalogue=data.games.filter(g=>g.group==='games'),activities=data.games.filter(g=>g.group!=='games');
const routesOf=rows=>new Set(rows.map(g=>g.route));
const seriesLeads=new Set(catalogue.filter(g=>g.editions&&g.editions.find(id=>catalogue.some(c=>c.id===id))===g.id).map(g=>g.id));
const expectedCards=catalogue.filter(g=>!g.editions||seriesLeads.has(g.id)).length;
const genreCount=name=>catalogue.filter(g=>g.genre===name).length;
const EMBER='game-emberwild',emberwild=catalogue.find(g=>g.id===EMBER);assert(emberwild,'Emberwild is the fixture game');
// The grid must list every catalogue href exactly once — as a card's Play or as a
// collapsed edition's Play inside its lead card — and nothing that is not a catalogue game.
function coverage(hrefs,routes){const seen=new Map();for(const h of hrefs)seen.set(h,(seen.get(h)||0)+1);const twice=[...seen].filter(([,n])=>n>1).map(([h])=>h),missing=[...routes].filter(r=>!seen.has(r)),extra=[...seen.keys()].filter(h=>!routes.has(h));assert(!twice.length&&!missing.length&&!extra.length,'grid coverage: twice='+JSON.stringify(twice)+' missing='+JSON.stringify(missing)+' extra='+JSON.stringify(extra));return seen.size;}
function coverageControl(hrefs){// Planted defect: drop one game from a scratch copy of the data; the limb must bite.
 const dropped=new Set(routesOf(catalogue));dropped.delete(emberwild.route);let bit=false;try{coverage(hrefs,dropped);}catch(_){bit=true;}assert(bit,'coverage control did not bite when a game was dropped from the data');
 const doubled=[...hrefs,emberwild.route];let bit2=false;try{coverage(doubled,routesOf(catalogue));}catch(_){bit2=true;}assert(bit2,'coverage control did not bite when a card was duplicated');return{droppedGameRefused:true,duplicateCardRefused:true};}
async function test(name,fn){try{report.checks.push({name,pass:true,evidence:await fn()});}catch(e){report.checks.push({name,pass:false,error:e.stack});if(currentPage&&!currentPage.isClosed()){await currentPage.screenshot({path:path.join(out,name+'-failure.png')}).catch(()=>{});fs.writeFileSync(path.join(out,name+'-failure.txt'),await currentPage.locator('body').innerText().catch(()=>''));}}fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));}
async function overflow(page){const proof=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,culprits:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>document.documentElement.clientWidth+1&&e.getClientRects().length&&!e.closest('.lane-track,.chip-row')).slice(0,8).map(e=>({tag:e.tagName,id:e.id,cls:e.className,right:e.getBoundingClientRect().right}))}));assert(proof.scroll<=proof.width+1,'Horizontal overflow '+JSON.stringify(proof));}
function visible(page){return page.locator('#game-grid [data-card]:visible');}
async function visibleGames(page){return page.evaluate(()=>[...document.querySelectorAll('#game-grid [data-card]')].filter(e=>!e.hidden).reduce((n,e)=>n+e.dataset.games.split(' ').length,0));}
async function gridHrefs(page){return page.evaluate(()=>[...document.querySelectorAll('#game-grid a[data-play][href]')].map(a=>a.getAttribute('href')));}
async function noMedia(requests){assert(!requests.some(u=>/\.(mp4|webm)(\?|$)/.test(u)),'Video requested before selection');assert(!requests.some(u=>/supabase|google-analytics|goatcounter|ko-fi|kofi/i.test(u)),'Unexpected tracking or support widget');}
function firstParty(requests){const foreign=requests.filter(u=>!u.startsWith(base+'/')&&!u.startsWith('data:'));assert.equal(foreign.length,0,'Requests left the review origin: '+JSON.stringify(foreign.slice(0,5)));assert(!requests.some(u=>/madebymatt\.uk/.test(u)),'A load reached madebymatt.uk');return requests.length;}
async function targets(page,scope){// Every visible interactive control inside `scope` is at least 44x44.
 const small=await page.evaluate(sel=>{const root=sel?document.querySelector(sel):document;return[...root.querySelectorAll('a[href],button,input,select,summary')].filter(e=>e.getClientRects().length&&!e.closest('[hidden]')&&getComputedStyle(e).visibility!=='hidden').map(e=>{const r=e.getBoundingClientRect();return{t:e.tagName,id:e.id,cls:String(e.className).slice(0,30),text:(e.textContent||'').trim().slice(0,24),w:Math.round(r.width),h:Math.round(r.height)};}).filter(x=>x.w<43.5||x.h<43.5);},scope);assert.equal(small.length,0,'Targets under 44px in '+(scope||'page')+': '+JSON.stringify(small.slice(0,8)));}
async function ready(page){await page.waitForSelector('#lanes-genre .lane',{state:'attached'});}
async function settledShelfCapture(page,file){
 await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const geometry=await page.locator('.lane').evaluateAll(lanes=>lanes.filter(e=>e.getClientRects().length).map(e=>{const track=e.querySelector('.lane-track'),r=track.getBoundingClientRect(),heading=e.querySelector('.lane-head').getBoundingClientRect();return{id:e.id,headingTop:heading.top,headingBottom:heading.bottom,trackTop:r.top,trackBottom:r.bottom,tileBottom:Math.max(...[...track.children].map(t=>t.getBoundingClientRect().bottom))};}));
 for(let i=0;i<geometry.length;i++){const g=geometry[i];assert(g.headingBottom<=g.trackTop+1,'Shelf heading overlaps its cards: '+g.id);assert(g.tileBottom<=g.trackBottom+1,'Cards escape shelf vertically: '+g.id);if(i)assert(geometry[i-1].trackBottom<=g.headingTop+1,'Adjacent shelves overlap: '+g.id);}
 fs.writeFileSync(path.join(out,file+'-geometry.json'),JSON.stringify(geometry,null,2));
 await page.screenshot({path:path.join(out,file+'.png'),fullPage:false});
}
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.PLAY_BROWSER_CHANNEL||'chrome',args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});report.browser=browser.version();
await test('payloads-catalogue-and-initial-dependencies',async()=>{for(const p of build.payloads){assert.equal(p.published_sha256,baselineHashes.get(p.path),'Game payload changed from approved baseline: '+p.route);const r=await fetch(base+'/'+encodeURI(p.path));assert.equal(r.status,200,p.route);assert.equal(sha(Buffer.from(await r.arrayBuffer())),p.published_sha256,p.route);}assert.equal(build.counts.game_payloads,69);assert.equal(build.counts.missing_initial_load_refs,0);assert.equal(build.counts.external_initial_load_refs,0);assert.equal(data.games.length,69);assert.equal(catalogue.length,data.counts.games);assert.equal(activities.length,data.counts.activities+data.counts.staff);return {payloads:69,byteMatches:69,initialMissing:0,initialExternal:0,counts:data.counts};});
await test('reviewed-discovery-and-real-screen-bindings',async()=>{
 const review=JSON.parse(fs.readFileSync('domain-split/play/discovery-review.json')),screens=JSON.parse(fs.readFileSync('domain-split/play/screens/manifest.json'));
 const key=r=>decodeURIComponent(r).replace(/index\.html$/,'').replace(/\/$/,'');
 const omitted=JSON.parse(fs.readFileSync(path.join(root,'play-discovery-report.json'))).omitted_discovery,expectedOmissions=[];
 let reviewedRoutes=0,realScreens=0;
 for(const [route,facts] of Object.entries(review.routes)){const g=data.games.find(g=>key(g.route)===key(route));assert(g);const payload=build.payloads.find(p=>key(p.route)===key(route));
  if(facts.published_sha256!==payload.published_sha256){assert(!g.moods?.length);assert(!Object.keys(g.details||{}).length);expectedOmissions.push({route:g.route,kind:'selection',reason:'Different approved game revision'});continue;}
  assert.deepEqual(g.moods,facts.moods);assert.deepEqual(g.details,facts.details||{});reviewedRoutes++;
 }
 for(const screen of screens.screens){const g=data.games.find(g=>key(g.route)===key(screen.route)),payload=build.payloads.find(p=>key(p.route)===key(screen.route));assert(g);
  if(screen.published_sha256!==payload.published_sha256){assert.equal(g.image||'','');expectedOmissions.push({route:g.route,kind:'screen',reason:'Different approved game revision'});continue;}
  assert.equal(g.image,'/assets/play/screens/'+screen.file);const response=await fetch(base+g.image);assert.equal(response.status,200);assert.equal(sha(Buffer.from(await response.arrayBuffer())),screen.sha256);realScreens++;
 }
 const order=rows=>rows.map(x=>JSON.stringify(x)).sort();assert.deepEqual(order(omitted),order(expectedOmissions),'Every omitted optional asset must be reported');
 if(process.env.PLAY_REQUIRE_COMPLETE_DISCOVERY==='1')assert.equal(omitted.length,0,'Release-source review requires complete image and selection coverage');
 assert(!data.games.some(g=>g.image&&g.image.endsWith('.svg')),'illustrated covers cannot stand in for game captures');
 return{reviewedRoutes,realScreens,byteBound:true,omittedDiscovery:omitted,completeDiscovery:omitted.length===0};
});
await test('static-shelf-one-dom-vocabulary-and-one-count',async()=>{const html=await (await fetch(base+'/')).text();for(const word of ['In-game screenshot','Cover artwork','Ver.'])assert.equal((html.match(new RegExp(word.replace('.','\\.'),'g'))||[]).length,0,'retired vocabulary present: '+word);for(const old of ['games and activities','catalogue games ·','large-number','Choose your next adventure','Recently updated'])assert(!html.includes(old),'old shelf copy present: '+old);
 const countStatements=html.match(/<p id="result-count"[^>]*>([^<]*)<\/p>/g)||[];assert.equal(countStatements.length,1,'exactly one count statement');assert.equal(countStatements[0].replace(/<[^>]+>/g,''),catalogue.length+' games','count statement is derived from the catalogue');
 const cardIds=[...html.matchAll(/data-card="([^"]+)"/g)].map(m=>m[1]);assert.equal(cardIds.length,new Set(cardIds).size,'duplicate data-card ids');assert.equal(cardIds.length,expectedCards,'grid cards = leads + singles');
 const featured=catalogue.find(g=>g.featured);assert(featured,'the manifest carries a featured flag');assert(html.includes('data-feature="'+featured.id+'"'),'Featured is the first featured:true row in manifest order');assert.equal((html.match(/data-feature="/g)||[]).length,1,'exactly one Featured card');
 for(const g of catalogue.filter(x=>x.editions)){const n=new Set(g.editions).size;assert(html.includes('>'+n+' editions<'),'editions chip for '+g.series+' shows '+n);}
 for(const literal of ['Pick a game. <span>Make it yours.</span>','YOUR NEXT GAME STARTS HERE.','placeholder="Search games"','>Filters<','>All games<','>For your classroom<','Whole-class quizzes and a staff training activity. Not part of the games catalogue.','Privacy and saved progress','Report a problem','Made by Matt Education ↗','Made by Matt Play','Optional usage statistics — off until you allow it.','Read what is counted.','>Allow<','>Keep off<','usage-client.js','>Editions<','>Your progress<','id="dialog-saves"','>Transfer saves<','>Favourite<','>Share<'])assert(html.includes(literal),'copy missing: '+literal);
 assert(!/<(a|button)[\s>][^>]*>(?:(?!<\/(a|button)>).)*<(a|button)[\s>]/s.test(html.replace(/<script[\s\S]*?<\/script>/g,'')),'nested interactive elements');
 return{cards:cardIds.length,featured:featured.route,countStatement:countStatements[0].replace(/<[^>]+>/g,''),retiredVocabulary:0};});
for(const width of [320,390,768,1280]){
 const ctx=await browser.newContext({viewport:{width,height:width<700?844:900},isMobile:width<700,hasTouch:width<700,reducedMotion:'reduce'}),page=await ctx.newPage();page.setDefaultTimeout(10000);currentPage=page;const requests=[];page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>report.errors.push({width,message:e.message}));
 await test(width+'-layout-navigation-and-first-load',async()=>{await page.goto(base);await ready(page);await overflow(page);
  assert.equal(await page.locator('#intro-title').innerText(),'Pick a game. Make it yours.');
  // PLAY-D2: the approved controller is decorative, byte-bound to hero-art.json, omitted on phones, and never over a control or the copy.
  const heroRecord=JSON.parse(fs.readFileSync('domain-split/play/hero-art.json'));const art=page.locator('.intro-art');assert.equal(await art.count(),1,'one hero artwork in the markup');
  const artFacts=await art.evaluate(i=>({visible:!!i.offsetParent&&getComputedStyle(i).display!=='none',complete:i.complete,w:i.naturalWidth,h:i.naturalHeight,alt:i.getAttribute('alt'),src:i.getAttribute('src'),width:i.getAttribute('width'),height:i.getAttribute('height'),source:i.dataset.heroSource,sha:i.dataset.heroSha,box:i.getBoundingClientRect().toJSON()}));
  assert.equal(artFacts.alt,'','hero artwork is decorative');assert.equal(artFacts.source,heroRecord.sourceSha256);assert.equal(artFacts.sha,heroRecord.sha256);assert.equal(artFacts.src,'/'+heroRecord.published);assert.equal(Number(artFacts.width),heroRecord.width);assert.equal(Number(artFacts.height),heroRecord.height);
  const artResponse=await page.request.get(base+artFacts.src);assert.equal(artResponse.status(),200);const artBytes=Buffer.from(await artResponse.body());assert.equal(sha(artBytes),heroRecord.sha256,'served hero artwork is the recorded file');assert.equal(artBytes.length,heroRecord.bytes);
  // PLAY-D2 amended by Matt, 16 September 2026. This branch used to assert the
  // OPPOSITE below 768px - 'phones omit the hero artwork'. Matt asked for the
  // controller on phones too, like the education hero, so the phone case now
  // has to prove the artwork is painted rather than prove it is absent. Nothing
  // else is relaxed: every width still proves the picture decodes, fits without
  // overflowing the viewport in either direction, renders at a useful size and
  // covers no heading, copy or control. A phone that silently dropped it, drew
  // it at a few pixels, or let it slide over the search box now reds here.
  assert(artFacts.visible&&artFacts.complete&&artFacts.w>0,'hero artwork shows and decodes at every width');
  assert(artFacts.box.left>=-1&&artFacts.box.right<=width+1,'hero artwork fits the viewport');
  assert(artFacts.box.width>=160,'hero artwork renders at a useful size');
  {const overlaps=await page.evaluate(box=>[...document.querySelectorAll('#intro-title,.intro .eyebrow,.intro .lede,#discovery-form,.mood-tools,.mood-note,header,.browse-sidebar')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.height&&r.left<box.right&&r.right>box.left&&r.top<box.bottom&&r.bottom>box.top;}).map(e=>e.id||e.className||e.tagName),artFacts.box);
   assert.deepEqual(overlaps,[],'hero artwork overlaps nothing');}
  assert.equal(await page.locator('.intro .lede').innerText(),'Race, explore, build or work out your next move. Find your favourite or try something unexpected—play straight in your browser.');
  const navigation=page.locator('.collection-links');
  await navigation.locator('[data-collection=favourites]').click();assert.equal(await visibleGames(page),0,'new browser favourites empty');assert.equal(await navigation.locator('[aria-current=page]').getAttribute('data-collection'),'favourites');
  await navigation.locator('[data-collection=recent]').click();assert.equal(await visibleGames(page),0,'new browser recent list empty');assert.equal(await navigation.locator('[aria-current=page]').getAttribute('data-collection'),'recent');
  await navigation.locator('[data-collection=""]').click();assert.equal(await visibleGames(page),catalogue.length,'All games restores the complete catalogue');assert(await page.locator('#all-games-title').evaluate(e=>e===document.activeElement),'collection navigation moves focus to results');
  await page.evaluate(()=>scrollTo(0,0));
  const tokenResponse=await page.request.get(base+'/assets/mbm-tokens.css');assert.equal(tokenResponse.status(),200,'Composed Play tokens must resolve locally');
  assert.equal(sha(Buffer.from(await tokenResponse.body())),sha(fs.readFileSync('assets/mbm-tokens.css')),'Token bytes match the pinned Site source');
  assert.equal(await page.locator('link[rel=stylesheet][href="/assets/mbm-tokens.css"]').count(),1,'One origin-local token link');
  const header=page.locator('header[data-mbm-chrome="play"]');assert.equal(await header.getAttribute('data-theme'),'dark');
  assert.equal(await header.locator('.brand strong').innerText(),'Play');
  assert(await header.locator('.brand img').evaluate(e=>e.complete&&e.naturalWidth>0));
  const tokenStyle=await header.evaluate(e=>({ink:getComputedStyle(e).getPropertyValue('--text').trim(),token:getComputedStyle(e).getPropertyValue('--mbm-primary').trim()}));assert.equal(tokenStyle.ink,tokenStyle.token,'Header adopts dark token ink');
  await targets(page,'header');await page.locator('#search-jump').click();assert(await page.locator('#query').evaluate(e=>e===document.activeElement));
  assert.equal(await visible(page).count(),expectedCards);const hrefs=await gridHrefs(page);const covered=coverage(hrefs,routesOf(catalogue));const control=coverageControl(hrefs);assert.equal(await page.locator('#classroom a[data-play]').count(),activities.length);const all=await page.evaluate(()=>new Set([...document.querySelectorAll('a[data-play][href]')].map(a=>a.getAttribute('href'))).size);assert.equal(all,data.games.length,'every route reachable by href');await noMedia(requests);const total=firstParty(requests);
  const lanes=await page.evaluate(()=>[...document.querySelectorAll('.lane')].map(l=>({heading:l.querySelector('h2').textContent,tiles:l.querySelectorAll('.tile').length,seeAll:(l.querySelector('.see-all')||{}).textContent||null})));for(const lane of lanes){const g=data.games.length&&catalogue.some(x=>x.genre===lane.heading)?genreCount(lane.heading):null;if(g!==null){assert(g>=3,'genre lane below three games: '+lane.heading);assert.equal(lane.seeAll,'See all '+g+' →');}}
  assert(lanes.some(l=>l.heading==='New and updated'),'New and updated lane');const updatedTiles=await page.locator('#lane-updated .tile-meta').allTextContents();const expectedUpdated=catalogue.filter(g=>g.updated).sort((a,b)=>b.updated.date.localeCompare(a.updated.date)).map(g=>{const[y,m,d]=g.updated.date.split('-').map(Number);return d+' '+['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][m-1]+' '+y;});assert.deepEqual(updatedTiles,expectedUpdated,'updated dates derived and newest first');
  assert.equal(await page.locator('#lane-continue .lane').count(),0,'Continue playing hidden while recent is empty');
  await page.evaluate(()=>scrollTo(0,0));await settledShelfCapture(page,width+'-home');await page.locator('#all-games-title').scrollIntoViewIfNeeded();await settledShelfCapture(page,width+'-browse');await page.locator('.menu summary').click();await page.keyboard.press('Escape');assert.equal(await page.locator('.menu').getAttribute('open'),null);assert(await page.locator('.menu summary').evaluate(e=>e===document.activeElement));return{viewport:{width,height:width<700?844:900},noOverflow:true,cards:expectedCards,catalogueHrefsCoveredOnce:covered,coverageControl:control,classroomRows:activities.length,routesReachable:all,requests:total,thirdParty:0,initialMediaRequests:0,lanes};});
 await test(width+'-search-chips-drawer-empty-reset',async()=>{await page.goto(base+'?q=Emberwild');await ready(page);assert.equal(await page.locator('#query').inputValue(),'Emberwild');assert.equal(await visible(page).count(),1);assert.match(await visible(page).innerText(),/Emberwild/);assert.equal(await page.locator('#result-count').innerText(),'1 of '+catalogue.length+' games');assert(await page.locator('#lanes').isHidden(),'lanes hide while filtering');
  await page.locator('#query').fill('qzx nonexistent');assert.equal(await visible(page).count(),0);assert(await page.locator('#empty-state').isVisible());await page.locator('#empty-reset').click();assert.equal(await visible(page).count(),expectedCards);assert.equal(await page.locator('#result-count').innerText(),catalogue.length+' games');assert(await page.locator('#lanes').isVisible());
  assert.equal(await page.locator('input[type=search]').count(),1,'one search field');assert.equal(await page.locator('main select:visible').count(),0,'no stacked selects on the page');
  const chips=await page.locator('.chip-button').allTextContents();assert.deepEqual(chips,['All','Calm','Fast','Thinky','Together'],'visible reviewed mood choices');
  const genre='Sport';await page.locator('#filters-open').click();await page.locator('#genre').selectOption(genre);await page.keyboard.press('Escape');assert.equal(await visibleGames(page),genreCount(genre));assert.equal(new URL(page.url()).searchParams.get('genre'),genre);
  await page.locator('#filters-open').click();await page.locator('#filters-reset').click();await page.keyboard.press('Escape');assert.equal(await visibleGames(page),catalogue.length);assert.equal(new URL(page.url()).searchParams.get('genre'),null);
  const opener=page.locator('#filters-open');await opener.click();assert(await page.locator('#filters').isVisible());assert(await page.locator('#filters-close').evaluate(e=>e===document.activeElement),'drawer opens on its close control');for(let i=0;i<8;i++){await page.keyboard.press('Tab');assert(await page.evaluate(()=>!!document.activeElement.closest('#filters')),'Focus escaped the drawer');}
  await page.locator('#control').selectOption('unknown');const unknown=catalogue.filter(g=>!g.controls.length).length;assert.equal(await visibleGames(page),unknown);await page.locator('#mode').selectOption('local');const local=catalogue.filter(g=>!g.controls.length&&g.modes.includes('local')).length;assert.equal(await visibleGames(page),local);await page.locator('#filters-reset').click();assert.equal(await visibleGames(page),catalogue.length);await page.keyboard.press('Escape');assert(!await page.locator('#filters').isVisible());assert(await opener.evaluate(e=>e===document.activeElement),'closing the drawer returns focus to Filters');
  const seeAll=page.locator('#lanes-genre .see-all').first();const seeText=await seeAll.innerText();await seeAll.click();const n=Number(seeText.replace(/\D/g,''));assert.equal(await visibleGames(page),n,'See all opens the grid with that chip');assert.equal(await page.locator('#genre').inputValue(),new URL(page.url()).searchParams.get('genre'));await page.locator('[data-collection=""]').click();return{genreChip:genre,genreCount:genreCount(genre),unknownControlCount:unknown,localUnverifiedCount:local,seeAll:seeText};});
 await test(width+'-favourites-recent-persistence-save-safety',async()=>{await page.goto(base);await ready(page);await page.evaluate(()=>localStorage.setItem('apexkick.v1','PLAY-QA-SENTINEL'));await page.locator('#query').fill('Emberwild');await page.locator('#game-grid [data-info="'+EMBER+'"]').click();await page.locator('#dialog-favourite').click();assert.equal(await page.locator('#dialog-favourite').getAttribute('aria-pressed'),'true','Favourite toggled');assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('mbm_play_favourites_v1'))),[EMBER],'Favourite storage');assert.deepEqual(await page.evaluate(()=>Object.keys(localStorage).sort()),['apexkick.v1','mbm_play_favourites_v1'],'no new storage keys');await page.keyboard.press('Escape');
  await page.reload();await ready(page);await page.locator('#query').fill('Emberwild');await page.locator('#game-grid [data-info="'+EMBER+'"]').click();assert.equal(await page.locator('#dialog-favourite').getAttribute('aria-pressed'),'true');await page.keyboard.press('Escape');await page.locator('.collection-links [data-collection=favourites]').click();assert.equal(await visibleGames(page),1);assert.equal(new URL(page.url()).searchParams.get('list'),'favourites');assert(await page.locator('#clear-favourites').isVisible());
  await page.locator('#game-grid [data-info="'+EMBER+'"]').click();await page.locator('#dialog-favourite').click();await page.keyboard.press('Escape');assert.equal(await visible(page).count(),0);assert(await page.locator('#empty-state').isVisible());await page.locator('#empty-reset').click();
  await page.locator('#query').fill('Emberwild');const play=page.locator('#game-grid a[data-play="'+EMBER+'"]');await play.click();await page.waitForURL('**/emberwild/');await page.goBack();await page.waitForSelector('#query');await ready(page);assert.equal(await page.locator('#query').inputValue(),'Emberwild');assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('mbm_play_recently_opened_v1'))),[EMBER],'recent key unchanged');assert(await page.evaluate(()=>sessionStorage.getItem('mbm_play_browse_position_v1')!==null),'position key unchanged');
  await page.locator('#query').fill('');assert(await page.locator('#lane-continue .lane').isVisible(),'Continue playing renders from the recent key');assert.match(await page.locator('#lane-continue h2').innerText(),/^Recently played$/);assert.match(await page.locator('#lane-continue .lane-head').innerText(),/on this device/);assert.equal(await page.locator('#lane-continue .tile').count(),1);
  await page.locator('#filters-open').click();await page.locator('#list').selectOption('recent');await page.keyboard.press('Escape');assert.equal(await visibleGames(page),1);await page.locator('#filters-open').click();await page.locator('#filters-reset').click();await page.keyboard.press('Escape');await page.locator('#clear-recent').click();assert.equal(await page.locator('#lane-continue .lane').count(),0);
  await page.locator('#game-grid [data-info="'+EMBER+'"]').first().click();await page.locator('#dialog-favourite').click();await page.keyboard.press('Escape');await page.locator('.collection-links [data-collection=favourites]').click();await page.locator('#clear-favourites').click();assert.equal(await visible(page).count(),0);assert.equal(await page.evaluate(()=>localStorage.getItem('apexkick.v1')),'PLAY-QA-SENTINEL');assert.deepEqual(await page.evaluate(()=>Object.keys(localStorage).filter(k=>!['apexkick.v1','mbm_splash_last'].includes(k)).sort()),['mbm_play_favourites_v1','mbm_play_recently_opened_v1'],'only the shelf keys (plus the sentinel and the game-owned splash key)');await page.locator('#empty-reset').click();return{persistence:true,recentFromOpen:true,continuePlayingLane:true,resetPreservedGameSave:true,keys:['mbm_play_favourites_v1','mbm_play_recently_opened_v1','mbm_play_browse_position_v1']};});
 await test(width+'-reviewed-moods-surprise-and-card-lists',async()=>{
  await page.goto(base+'?mood=Together&genre=Sport');await ready(page);
  const eligible=catalogue.filter(g=>(g.moods||[]).includes('Together')&&g.genre==='Sport');assert(eligible.length>1);
  const ids=await visible(page).locator('.card-open').evaluateAll(es=>es.map(e=>e.dataset.info));assert.deepEqual(new Set(ids),new Set(eligible.map(g=>g.id)));
  await page.locator('#surprise').click();const picked=new URL(page.url()).searchParams.get('game');assert(eligible.some(g=>g.id===picked),'Surprise chose outside active mood/genre');assert.equal(await page.locator('#dialog-play').getAttribute('href'),eligible.find(g=>g.id===picked).route);assert.match(await page.locator('#dialog-players').innerText(),/device|network/i);await page.keyboard.press('Escape');assert(await page.locator('#surprise').evaluate(e=>e===document.activeElement),'Surprise opener regains focus');
  await page.locator('#query').fill('nonexistent qzx');await page.locator('#surprise').click();assert(!await page.locator('#game-dialog').isVisible());assert.match(await page.locator('#surprise-status').innerText(),/No games match/);assert(await page.locator('#empty-reset').evaluate(e=>e===document.activeElement));await page.locator('#empty-reset').click();
  await page.locator('#query').fill('Emberwild');const heart=page.locator('#game-grid [data-favourite="'+EMBER+'"]');if(await heart.getAttribute('aria-pressed')==='true')await heart.click();await heart.click();assert.equal(await heart.getAttribute('aria-pressed'),'true');assert(!await page.locator('#game-dialog').isVisible(),'card favourite does not open details or launch');
  await page.locator('.collection-links [data-collection=favourites]').click();await page.locator('#game-grid [data-favourite="'+EMBER+'"]').click();assert(await page.evaluate(()=>document.activeElement!==document.body&&document.activeElement.getClientRects().length>0),'removing a favourite leaves visible focus');
  await page.evaluate(id=>{localStorage.setItem('apexkick.v1','PLAY-QA-SENTINEL');localStorage.setItem('mbm_play_recently_opened_v1',JSON.stringify([id]));},EMBER);await page.goto(base+'?list=recent');await ready(page);assert.match(await page.locator('#list-note').innerText(),/not saved games/);await page.locator('#game-grid [data-remove-recent="'+EMBER+'"]').click();assert(await page.locator('#empty-state').isVisible());assert(await page.locator('#empty-reset').evaluate(e=>e===document.activeElement));assert.equal(await page.evaluate(()=>localStorage.getItem('apexkick.v1')),'PLAY-QA-SENTINEL');
  await page.evaluate(id=>localStorage.setItem('mbm_play_recently_opened_v1',JSON.stringify([id])),EMBER);await page.reload();await ready(page);await page.locator('#clear-recent-list').click();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('mbm_play_recently_opened_v1'))),[]);assert.equal(await page.evaluate(()=>localStorage.getItem('apexkick.v1')),'PLAY-QA-SENTINEL');
  await page.goto(base+'?mood=Calm&q=Lumina');await ready(page);await page.locator('#surprise').click();assert.match(await page.locator('#dialog-accessibility').innerText(),/Reduced motion/);assert.match(await page.locator('#dialog-saves').innerText(),/auto-saves/);await page.screenshot({path:path.join(out,width+'-discovery-details.png')});await page.keyboard.press('Escape');
  const lighthouse=catalogue.find(g=>g.route.includes('/The_Last_Lighthouse_'));
  await page.goto(base+'?game='+lighthouse.id);await ready(page);
  const lighthouseImage=page.locator('#dialog-media img');await lighthouseImage.evaluate(img=>img.decode());
  assert.equal(await lighthouseImage.evaluate(img=>getComputedStyle(img).objectPosition),'50% 0%','Tall title capture keeps its heading visible');
  await page.screenshot({path:path.join(out,width+'-lighthouse-details.png')});await page.keyboard.press('Escape');
  return{combinedMoodGenre:true,surpriseEligibleOnly:true,emptySurprise:true,directCardFavourite:true,removeRecentFocus:true,clearRecentFromList:true,saveSentinelPreserved:true};
 });
 await test(width+'-sheet-focus-deep-link-and-return',async()=>{await page.goto(base+'?q=Emberwild');await ready(page);const trigger=page.locator('#game-grid [data-info="'+EMBER+'"]');await trigger.click();assert(await page.locator('#game-dialog').isVisible());assert(await page.locator('#dialog-close').evaluate(e=>e===document.activeElement),'sheet opens on its close control');assert.equal(new URL(page.url()).searchParams.get('game'),EMBER,'deep link written');for(let i=0;i<16;i++){await page.keyboard.press('Tab');assert(await page.evaluate(()=>!!document.activeElement.closest('#game-dialog')),'Focus escaped dialog');}
  assert.equal(await page.locator('#dialog-title').innerText(),emberwild.displayTitle||emberwild.title);assert.equal(await page.locator('#dialog-play').innerText(),'Play '+(emberwild.displayTitle||emberwild.title)+' →');const chips=await page.locator('#dialog-support .chip').allTextContents();const expected=[['controls','touch','Touch'],['controls','keyboard','Keyboard'],['controls','gamepad','Gamepad'],['modes','single','1 player'],['modes','local','Local / same-network options']].filter(([f,v])=>emberwild[f].includes(v)).map(x=>x[2]);assert.deepEqual(chips,expected.length?expected:['Not yet verified']);assert.equal(await page.locator('#dialog-watch').isVisible(),Boolean(emberwild.media.video),'Watch gameplay only with media');assert.match(await page.locator('#dialog-description').innerText(),new RegExp('^'+emberwild.description.slice(0,20).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
  await page.keyboard.press('Escape');assert(!await page.locator('#game-dialog').isVisible());assert(await trigger.evaluate(e=>e===document.activeElement),'closing returns focus to the opener');assert.equal(new URL(page.url()).searchParams.get('game'),null,'deep link cleared on close');
  const footerReport=await page.locator('footer a[href^="mailto:"]').getAttribute('href');assert.match(footerReport,/^mailto:contactmadebymatt@gmail.com/);assert.equal(await page.locator('footer a[href^="mailto:"]').innerText(),'Report a problem');assert.equal(await page.locator('#game-dialog a[href^="mailto:"]').count(),0,'report link lives in the footer, not the sheet');
  await trigger.click();await page.locator('#dialog-play').click();await page.waitForURL('**/emberwild/');await page.goBack();await page.waitForSelector('#query');await ready(page);assert.equal(await page.locator('#query').inputValue(),'Emberwild');assert(!await page.locator('#game-dialog').isVisible(),'Back reopened the sheet');assert.equal(new URL(page.url()).searchParams.get('game'),null);
  await page.goto(base+'?game='+EMBER);await ready(page);assert(await page.locator('#game-dialog').isVisible(),'?game= deep link opens the sheet');assert.equal(await page.locator('#dialog-title').innerText(),emberwild.displayTitle||emberwild.title);await page.keyboard.press('Escape');
  const series=catalogue.find(g=>g.editions&&seriesLeads.has(g.id));await page.goto(base+'?game='+series.id);await ready(page);assert(await page.locator('#dialog-editions').isVisible(),'Editions row for a series');const editionLinks=await page.locator('#dialog-editions a[data-play]').evaluateAll(a=>a.map(x=>x.getAttribute('href')));assert.deepEqual(editionLinks,series.editions.map(id=>data.games.find(g=>g.id===id).route),'every edition has its own Play link');assert.equal(await page.locator('#dialog-editions h3').innerText(),'Editions');assert.match(await page.locator('#game-dialog .progress').innerText(),/Your progress\s+Save support has not yet been verified for this game\. Favourites and recent launches do not store game progress\.\s+Transfer saves/);assert.equal(await page.locator('#game-dialog .progress a').getAttribute('href'),'/game-saves/');const chapter=catalogue.find(g=>g.chapter);await page.keyboard.press('Escape');await page.goto(base+'?game='+chapter.id);await ready(page);assert.match(await page.locator('#dialog-description').innerText(),new RegExp(' New chapter: '+chapter.chapter.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\.$'));await page.keyboard.press('Escape');return{focusTrap:true,escapeFocusReturn:true,deepLink:true,backToResults:true,editions:series.series,chapter:chapter.chapter,reportInFooter:true};});
 await test(width+'-keyboard-warning-and-unverified',async()=>{await page.goto(base);await ready(page);const coarse=await page.evaluate(()=>matchMedia('(hover: none) and (pointer: coarse)').matches);const needs=catalogue.find(g=>g.controls.length&&!g.controls.includes('touch')&&(!g.editions||seriesLeads.has(g.id)));const unverified=catalogue.find(g=>!g.controls.length&&(!g.editions||seriesLeads.has(g.id)));
  const chip=page.locator('#game-grid [data-card="'+needs.id+'"] [data-needs-keyboard]');assert.equal(await chip.count(),1,'card carries the warning element for verified non-touch controls');assert.equal(await chip.isVisible(),coarse,'warning shown only on a coarse pointer');assert.equal(await page.locator('#game-grid [data-card="'+unverified.id+'"] [data-needs-keyboard]').count(),0,'unverified card carries nothing');
  await page.locator('#query').fill(needs.displayTitle||needs.title);await page.locator('#game-grid [data-info="'+needs.id+'"]').click();assert.equal(await page.locator('#dialog-keyboard').isVisible(),coarse);assert(await page.locator('#dialog-play').isVisible(),'Play never blocked');assert.equal(await page.locator('#dialog-play').getAttribute('href'),needs.route);await page.keyboard.press('Escape');
  await page.locator('#query').fill(unverified.displayTitle||unverified.title);await page.locator('#game-grid [data-info="'+unverified.id+'"]').click();assert.deepEqual(await page.locator('#dialog-support .chip').allTextContents(),['Not yet verified']);assert(!await page.locator('#dialog-keyboard').isVisible());assert(await page.locator('#dialog-play').isVisible());await page.keyboard.press('Escape');return{coarsePointer:coarse,needsKeyboard:needs.id,unverified:unverified.id};});
 if(width===390)await test('390-targets-44px-closed-drawer-sheet',async()=>{await page.goto(base);await ready(page);await targets(page,null);await page.locator('#filters-open').click();await targets(page,'#filters');await page.keyboard.press('Escape');await page.locator('#game-grid [data-info="'+EMBER+'"]').click();await targets(page,'#game-dialog');await page.keyboard.press('Escape');const series=catalogue.find(g=>g.editions&&seriesLeads.has(g.id));await page.locator('#game-grid [data-info="'+series.id+'"]').click();await targets(page,'#game-dialog');await page.keyboard.press('Escape');return{closed:true,drawerOpen:true,sheetOpen:true,sheetWithEditions:true};});
 await test(width+'-orientation-and-text-enlargement',async()=>{await page.goto(base);await ready(page);await page.setViewportSize({width:width<700?844:900,height:width});await overflow(page);await page.setViewportSize({width,height:900});await page.addStyleTag({content:':root{font-size:200%!important}'});assert((await page.evaluate(()=>parseFloat(getComputedStyle(document.documentElement).fontSize)))>=32,'Text enlargement did not apply');await overflow(page);const collectionFits=await page.locator('.browse-sidebar').evaluate(e=>e.scrollWidth<=e.clientWidth+1&&[...e.querySelectorAll('.collection-links a')].every(a=>a.scrollWidth<=a.clientWidth+1));assert(collectionFits,'Collection labels must fit at 200% text size');await page.screenshot({path:path.join(out,width+'-text-200.png')});return{landscapeNoOverflow:true,text200NoOverflow:true,collectionLabelsFit:true};});
 await ctx.close();
}
await test('essential-links-with-javascript-disabled',async()=>{const ctx=await browser.newContext({javaScriptEnabled:false}),page=await ctx.newPage();await page.goto(base);const hrefs=await gridHrefs(page);const covered=coverage(hrefs,routesOf(catalogue));assert.equal(await page.locator('#classroom a[data-play]').count(),activities.length);const distinct=await page.evaluate(()=>new Set([...document.querySelectorAll('a[data-play][href]')].map(a=>a.getAttribute('href'))).size);assert.equal(distinct,data.games.length,'every Play href present without JavaScript');const anchors=await page.locator('a[data-play][href]').count();await page.locator('.menu summary').click();assert(await page.getByRole('navigation',{name:'Main menu'}).isVisible());assert.match(await page.locator('noscript').innerText(),/direct Play links work/);await ctx.close();return{directHrefs:distinct,gridCatalogueHrefsOnce:covered,classroomRows:activities.length,playAnchors:anchors,nativeMenu:true};});
await test('unavailable-storage-missing-media-and-failure-fallback',async()=>{const ctx=await browser.newContext(),page=await ctx.newPage();await page.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('blocked','SecurityError');}});Object.defineProperty(window,'sessionStorage',{get(){throw new DOMException('blocked','SecurityError');}});});await page.route(/\.(png|jpg|webp|svg)(\?.*)?$/,r=>r.abort());await page.goto(base);await ready(page);await page.locator('#query').fill('Emberwild');await page.locator('#game-grid [data-info="'+EMBER+'"]').click();await page.locator('#dialog-favourite').click();assert.match(await page.locator('#storage-status').innerText(),/unavailable/);await pause(300);assert.match(await page.locator('#dialog-media').innerText(),/Image unavailable/);assert(await page.locator('#dialog-play').isVisible());await page.keyboard.press('Escape');assert(await page.locator('#game-grid .play').filter({visible:true}).first().isVisible());await ctx.close();return{browsing:true,inMemoryFavourite:true,gameLinks:true,imageFallback:true};});
await test('all-69-rendered-start-surfaces',async()=>{for(const g of data.games){const ctx=await browser.newContext({viewport:{width:1280,height:720},reducedMotion:'reduce'}),page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));try{const response=await page.goto(base+g.route,{waitUntil:'load',timeout:20000});await pause(4000);const surface=await page.evaluate(()=>({title:document.title,canvas:[...document.querySelectorAll('canvas')].filter(e=>e.getBoundingClientRect().width>20&&e.getBoundingClientRect().height>20).length,controls:[...document.querySelectorAll('button,input,select,a[href]')].filter(e=>e.getBoundingClientRect().width>0).length,text:document.body.innerText.slice(0,1100)}));const ready=response.status()===200&&(surface.canvas>0||surface.controls>0);report.routes.push({id:g.id,route:g.route,status:response.status(),ready,surface,errors,depth:'Initial load and rendered input surface; not a completed game'});// The Lighthouse first-visit primer focuses its bottom button. Dismiss it
// through the ordinary player control so the capture identifies the game.
if(g.route.includes('/The_Last_Lighthouse_')){
 await page.getByRole('button',{name:'TAKE THE WATCH',exact:true}).click();
 await page.setViewportSize({width:1280,height:1000});
 await page.locator('#startScreen h1').waitFor({state:'visible'});
 await page.locator('#startScreen h1').scrollIntoViewIfNeeded();
 await pause(250);
 report.routes[report.routes.length-1].captureAction='Dismissed first-visit primer with Take the watch; captured title screen at 1280x1000.';
}
await page.screenshot({path:path.join(out,'route-'+g.id+'.jpg'),quality:65});}catch(e){report.routes.push({id:g.id,route:g.route,ready:false,error:e.message});}await ctx.close();}assert(report.routes.every(r=>r.ready),'Some initial game surfaces did not render');return{routes:69,rendered:report.routes.filter(r=>r.ready).length,runtimeErrors:report.routes.filter(r=>r.errors?.length).map(r=>({route:r.route,errors:r.errors}))};});
await test('accepted-preview-playback-seeking-pause-close',async()=>{const media=data.games.filter(g=>g.media.video);if(!media.length)return{status:'not-run-no-accepted-media',count:0};const proofs=[];for(const width of [390,1280]){const ctx=await browser.newContext({viewport:{width,height:844}}),page=await ctx.newPage();const requests=[];page.on('request',r=>requests.push(r.url()));await page.goto(base);await noMedia(requests);for(const g of media){await page.locator('#query').fill(g.title);await page.locator('#game-grid [data-watch="'+g.id+'"]').click();const v=page.locator('#game-dialog video');await page.waitForFunction(()=>{const v=document.querySelector('#game-dialog video');return v&&!v.paused&&v.currentTime>.5;});const state=await v.evaluate(v=>({duration:v.duration,time:v.currentTime,ready:v.readyState}));assert(state.duration>=12&&state.duration<=25);await v.evaluate(v=>v.currentTime=v.duration/2);await page.waitForFunction(()=>{const v=document.querySelector('video');return v&&v.currentTime>v.duration/2-.5;});await v.evaluate(v=>v.pause());const paused=await v.evaluate(v=>v.currentTime);await pause(200);assert.equal(await v.evaluate(v=>v.currentTime),paused);assert.equal(await page.locator('video').count(),1);await page.locator('#dialog-close').click();assert.equal(await page.locator('video').count(),0);proofs.push({title:g.title,width,...state,seeking:true,paused:true,closedAndStopped:true});}await ctx.close();}return{count:media.length,proofs};});
await browser.close();report.pass=report.checks.every(c=>c.pass);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,checks:report.checks.map(c=>({name:c.name,pass:c.pass,error:c.error?.split('\n')[0]})),routes:report.routes.length},null,2));if(!report.pass)process.exitCode=1;})();
