/* Repository browser acceptance for the Play overlay. Every check records its
 * actual scope; route-start sampling is not a full playthrough of 69 engines. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const base=process.env.PLAY_REVIEW_URL||'http://127.0.0.1:4173',out=path.resolve('.play-review/qa'),root=path.resolve('.play-review/output');fs.mkdirSync(out,{recursive:true});
const data=JSON.parse(fs.readFileSync(path.join(root,'games/data/play-discovery.json'))),build=JSON.parse(fs.readFileSync(path.join(root,'build-report.json')));
const report={date:new Date().toISOString(),checks:[],routes:[],limitations:['Route coverage proves initial rendered state and available input surface, not completion of every game.','Source-supported control labels do not certify physical gamepad, real-device performance or two-device local pairing.'],errors:[]};
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
let currentPage=null;
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function test(name,fn){try{report.checks.push({name,pass:true,evidence:await fn()});}catch(e){report.checks.push({name,pass:false,error:e.stack});if(currentPage&&!currentPage.isClosed()){await currentPage.screenshot({path:path.join(out,name+'-failure.png')}).catch(()=>{});fs.writeFileSync(path.join(out,name+'-failure.txt'),await currentPage.locator('body').innerText().catch(()=>''));}}fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));}
async function overflow(page){const proof=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,culprits:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1&&e.getClientRects().length).slice(0,8).map(e=>({tag:e.tagName,id:e.id,cls:e.className,right:e.getBoundingClientRect().right}))}));assert(proof.scroll<=proof.width+1,'Horizontal overflow '+JSON.stringify(proof));}
function visible(page){return page.locator('#game-grid [data-card]:visible');}
async function noMedia(requests){assert(!requests.some(u=>/\.(mp4|webm)(\?|$)/.test(u)),'Video requested before selection');assert(!requests.some(u=>/supabase|google-analytics|goatcounter/.test(u)),'Unexpected tracking');}
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome',args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});report.browser=browser.version();
await test('payloads-catalogue-and-initial-dependencies',async()=>{for(const p of build.payloads){const r=await fetch(base+'/'+encodeURI(p.path));assert.equal(r.status,200,p.route);assert.equal(sha(Buffer.from(await r.arrayBuffer())),p.published_sha256,p.route);}assert.equal(build.counts.game_payloads,69);assert.equal(build.counts.missing_initial_load_refs,0);assert.equal(build.counts.external_initial_load_refs,0);return {payloads:69,byteMatches:69,initialMissing:0,initialExternal:0,counts:data.counts};});
for(const width of [320,390,768,1280]){
 const ctx=await browser.newContext({viewport:{width,height:width<700?844:900},reducedMotion:'reduce'}),page=await ctx.newPage();page.setDefaultTimeout(10000);currentPage=page;const requests=[];page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>report.errors.push({width,message:e.message}));
 await test(width+'-layout-navigation-and-first-load',async()=>{await page.goto(base);await page.waitForSelector('[data-info]:not([hidden])');await overflow(page);assert.equal(await visible(page).count(),69);await noMedia(requests);await page.screenshot({path:path.join(out,width+'-home.png'),fullPage:false});await page.locator('#browse').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,width+'-browse.png')});await page.locator('.menu summary').click();await page.keyboard.press('Escape');assert.equal(await page.locator('.menu').getAttribute('open'),null);assert(await page.locator('.menu summary').evaluate(e=>e===document.activeElement));return{viewport:{width,height:width<700?844:900},noOverflow:true,initialMediaRequests:0};});
 await test(width+'-search-filters-empty-reset',async()=>{await page.goto(base+'?q=Emberwild');await page.waitForSelector('[data-info]:not([hidden])');await page.locator('#query').fill('Emberwild');assert.equal(await visible(page).count(),1);assert.match(await visible(page).innerText(),/Emberwild/);await page.locator('#query').fill('qzx nonexistent');assert.equal(await visible(page).count(),0);assert(await page.locator('#empty-state').isVisible());await page.locator('#empty-reset').click();assert.equal(await visible(page).count(),69);await page.locator('#group').selectOption('activities');assert.equal(await visible(page).count(),6);await page.locator('#group').selectOption('staff');assert.equal(await visible(page).count(),1);await page.locator('#group').selectOption('');await page.locator('#genre').selectOption('Puzzles');assert((await visible(page).count())>0);await page.locator('#genre').selectOption('');await page.locator('#control').selectOption('unknown');const unknown=data.games.filter(g=>!g.controls.length).length;assert.equal(await visible(page).count(),unknown);await page.locator('button[type=reset]').click();return{classroom:6,staff:1,unknownControlCount:unknown};});
 await test(width+'-favourites-recent-persistence-save-safety',async()=>{await page.goto(base);await page.waitForSelector('[data-favourite]:not([hidden])');await page.evaluate(()=>localStorage.setItem('apexkick.v1','PLAY-QA-SENTINEL'));await page.locator('#query').fill('Emberwild');await page.locator('#game-grid [data-favourite="game-emberwild"]').click();assert.equal(await page.locator('#game-grid [data-favourite="game-emberwild"]').getAttribute('aria-pressed'),'true','Favourite toggled');assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('mbm_play_favourites_v1'))),['game-emberwild'],'Favourite storage');await page.reload();await page.waitForSelector('[data-favourite]:not([hidden])');assert.equal(await page.locator('#game-grid [data-favourite="game-emberwild"]').getAttribute('aria-pressed'),'true');await page.locator('#list').selectOption('favourites');await page.locator('#game-grid [data-favourite="game-emberwild"]').click();assert.equal(await visible(page).count(),0);assert(await page.locator('#empty-reset').evaluate(e=>e===document.activeElement));await page.locator('#empty-reset').click();await page.locator('#query').fill('Emberwild');const play=page.locator('#game-grid a[data-play="game-emberwild"]');await play.click();await page.waitForURL('**/emberwild/');await page.goBack();await page.waitForSelector('#query');assert.equal(await page.locator('#query').inputValue(),'Emberwild');await page.locator('#list').selectOption('recent');assert.equal(await visible(page).count(),1);await page.locator('#clear-recent').click();assert.equal(await visible(page).count(),0);await page.locator('#clear-favourites').click();assert.equal(await page.evaluate(()=>localStorage.getItem('apexkick.v1')),'PLAY-QA-SENTINEL');await page.locator('#empty-reset').click();return{persistence:true,recentFromOpen:true,resetPreservedGameSave:true};});
 await test(width+'-information-focus-report-and-return',async()=>{await page.goto(base+'?q=Emberwild');await page.waitForSelector('[data-info]:not([hidden])');await page.locator('#query').fill('Emberwild');const trigger=page.locator('#game-grid [data-info="game-emberwild"]');await trigger.click();assert(await page.locator('#game-dialog').isVisible());for(let i=0;i<16;i++){await page.keyboard.press('Tab');assert(await page.evaluate(()=>!!document.activeElement.closest('#game-dialog')),'Focus escaped dialog');}await page.keyboard.press('Escape');assert(!await page.locator('#game-dialog').isVisible());assert(await trigger.evaluate(e=>e===document.activeElement));await trigger.click();const href=await page.locator('#dialog-report').getAttribute('href');assert.match(href,/^mailto:contactmadebymatt@gmail.com/);assert.match(decodeURIComponent(href),/https:\/\/www.madebymatt-play.uk\/emberwild\//);await page.locator('#dialog-play').click();await page.waitForURL('**/emberwild/');await page.goBack();await page.waitForSelector('#query');assert.equal(await page.locator('#query').inputValue(),'Emberwild');assert(!await page.locator('#game-dialog').isVisible(),'Back reopened promotional dialog');return{focusTrap:true,escapeFocusReturn:true,reportPreparedNotSent:true,backToResults:true};});
 await test(width+'-orientation-and-text-enlargement',async()=>{await page.goto(base);await page.waitForSelector('[data-info]:not([hidden])');await page.setViewportSize({width:width<700?844:900,height:width});await overflow(page);await page.setViewportSize({width,height:900});await page.addStyleTag({content:':root{font-size:200%!important}'});assert((await page.evaluate(()=>parseFloat(getComputedStyle(document.documentElement).fontSize)))>=32,'Text enlargement did not apply');await overflow(page);await page.screenshot({path:path.join(out,width+'-text-200.png')});return{landscapeNoOverflow:true,text200NoOverflow:true};});
 await ctx.close();
}
await test('essential-links-with-javascript-disabled',async()=>{const ctx=await browser.newContext({javaScriptEnabled:false}),page=await ctx.newPage();await page.goto(base);assert.equal(await page.locator('#game-grid a[data-play]').count(),69);await page.locator('.menu summary').click();assert(await page.getByRole('navigation',{name:'Main menu'}).isVisible());assert.match(await page.locator('noscript').innerText(),/direct Play links work/);await ctx.close();return{directLinks:69,nativeMenu:true};});
await test('unavailable-storage-missing-media-and-failure-fallback',async()=>{const ctx=await browser.newContext(),page=await ctx.newPage();await page.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('blocked','SecurityError');}});Object.defineProperty(window,'sessionStorage',{get(){throw new DOMException('blocked','SecurityError');}});});await page.route(/\.(png|jpg|webp|svg)(\?.*)?$/,r=>r.abort());await page.goto(base);await page.locator('#query').fill('Emberwild');await page.locator('#game-grid [data-favourite="game-emberwild"]').click();assert.match(await page.locator('#storage-status').innerText(),/unavailable/);assert(await page.locator('#game-grid .primary').filter({visible:true}).first().isVisible());await page.locator('#game-grid [data-info="game-emberwild"]').click();await pause(300);assert.match(await page.locator('#dialog-media').innerText(),/Image unavailable/);assert(await page.locator('#dialog-play').isVisible());await ctx.close();return{browsing:true,inMemoryFavourite:true,gameLinks:true,imageFallback:true};});
await test('all-69-rendered-start-surfaces',async()=>{for(const g of data.games){const ctx=await browser.newContext({viewport:{width:1280,height:720},reducedMotion:'reduce'}),page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));try{const response=await page.goto(base+g.route,{waitUntil:'load',timeout:20000});await pause(900);const surface=await page.evaluate(()=>({title:document.title,canvas:[...document.querySelectorAll('canvas')].filter(e=>e.getBoundingClientRect().width>20&&e.getBoundingClientRect().height>20).length,controls:[...document.querySelectorAll('button,input,select,a[href]')].filter(e=>e.getBoundingClientRect().width>0).length,text:document.body.innerText.slice(0,1100)}));const ready=response.status()===200&&(surface.canvas>0||surface.controls>0);report.routes.push({id:g.id,route:g.route,status:response.status(),ready,surface,errors,depth:'Initial load and rendered input surface; not a completed game'});if(!ready)await page.screenshot({path:path.join(out,'route-'+g.id+'.png')});}catch(e){report.routes.push({id:g.id,route:g.route,ready:false,error:e.message});}await ctx.close();}assert(report.routes.every(r=>r.ready),'Some initial game surfaces did not render');return{routes:69,rendered:report.routes.filter(r=>r.ready).length,runtimeErrors:report.routes.filter(r=>r.errors?.length).map(r=>({route:r.route,errors:r.errors}))};});
await test('accepted-preview-playback-seeking-pause-close',async()=>{const media=data.games.filter(g=>g.media.video);if(!media.length)return{status:'not-run-no-accepted-media',count:0};const proofs=[];for(const width of [390,1280]){const ctx=await browser.newContext({viewport:{width,height:844}}),page=await ctx.newPage();const requests=[];page.on('request',r=>requests.push(r.url()));await page.goto(base);await noMedia(requests);for(const g of media){await page.locator('#query').fill(g.title);await page.locator('#game-grid [data-watch="'+g.id+'"]').click();const v=page.locator('#game-dialog video');await page.waitForFunction(()=>{const v=document.querySelector('#game-dialog video');return v&&!v.paused&&v.currentTime>.5;});const state=await v.evaluate(v=>({duration:v.duration,time:v.currentTime,ready:v.readyState}));assert(state.duration>=12&&state.duration<=25);await v.evaluate(v=>v.currentTime=v.duration/2);await page.waitForFunction(()=>{const v=document.querySelector('video');return v&&v.currentTime>v.duration/2-.5;});await v.evaluate(v=>v.pause());const paused=await v.evaluate(v=>v.currentTime);await pause(200);assert.equal(await v.evaluate(v=>v.currentTime),paused);assert.equal(await page.locator('video').count(),1);await page.locator('#dialog-close').click();assert.equal(await page.locator('video').count(),0);proofs.push({title:g.title,width,...state,seeking:true,paused:true,closedAndStopped:true});}await ctx.close();}return{count:media.length,proofs};});
await browser.close();report.pass=report.checks.every(c=>c.pass);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,checks:report.checks.map(c=>({name:c.name,pass:c.pass,error:c.error?.split('\n')[0]})),routes:report.routes.length},null,2));if(!report.pass)process.exitCode=1;})();
