#!/usr/bin/env python3
"""Pass U whole-domain sitemap COVERAGE additions (hand-back; not applied to main).
Purely additive: derives the agreed missing pages from each pinned tree, true last-commit
lastmods, exclusions by rule + the reviewer's per-folder calls. dead=0 so nothing is removed."""
import os,re,subprocess,urllib.parse
HOST='https://madebymatt.uk/'
TREES=[('Lessons/','/workspace/lessons/'),('Games/','/workspace/games/'),('Matt-s-Apps-/','/workspace/matt-s-apps-/')]
sm=set(urllib.parse.unquote(m.group(1)[len(HOST):]) for m in re.finditer(r'<loc>('+re.escape(HOST)+r'[^<]*)</loc>',open('sitemap.xml').read()))
disallow=[re.match(r'\s*Disallow:\s*(\S+)',l).group(1).strip('/')+'/' for l in open('robots.txt') if re.match(r'\s*Disallow:\s*\S',l)]
def is_stub(p):
    try: return 'mbm:redirect-stub' in open(p,errors='ignore').read(3000)
    except: return False
def excluded(rel,full):
    b=os.path.basename(rel).lower(); low=rel.lower()
    if b in ('404.html',) : return 'error page'
    if b=='index.html' and rel.count('/')==1: return 'section-root dup'   # Lessons/index.html etc.
    if b.endswith('-health.html'): return 'internal diagnostics dashboard (🩺)'  # hub-health, suite-health
    if '/build-engine/' in low: return 'internal generator (README: Build Lesson Engine)'
    if '/_archive' in low: return 'archived version'
    if '_autosave' in b: return 'editor autosave artifact'
    if '_source' in b: return 'dev source (canonical sibling exists)'
    # NB: '-1.html' is a NORMAL filename pattern in this estate (the sitemap already lists e.g.
    # Lesson1_Indicators-1.html), so it is NOT treated as a duplicate marker. Any genuine stale
    # duplicate is a content-dedup finding for the §5 Lessons sweep, not a sitemap exclusion.
    return None
def gitdate(root,rel_in_tree):
    return subprocess.run(['git','-C',root.rstrip('/'),'log','-1','--format=%cs','--',rel_in_tree],capture_output=True,text=True).stdout.strip()

added=[]; skipped=[]
for pre,root in TREES:
    for r,_,fs in os.walk(root):
        if '/.git' in r: continue
        for f in sorted(fs):
            if not f.endswith('.html'): continue
            full=os.path.join(r,f); rel_in_tree=os.path.relpath(full,root); rel=pre+rel_in_tree
            if rel in sm: continue
            u=pre+(rel_in_tree[:-len('index.html')] if f=='index.html' else rel_in_tree)  # dir URL for index.html
            if u in sm or u.rstrip('/')+'/' in sm: continue
            if any(rel_in_tree.startswith(d) for d in disallow): skipped.append((rel,'robots disallow')); continue
            if is_stub(full): skipped.append((rel,'redirect stub')); continue
            why=excluded(rel,full)
            if why: skipped.append((rel,why)); continue
            date=gitdate(root,rel_in_tree)
            is_hub=(f=='index.html')
            added.append((HOST+urllib.parse.quote(u),date,'0.7' if is_hub else '0.6',pre))
from collections import defaultdict
bysec=defaultdict(list)
for loc,date,pri,pre in added: bysec[pre].append((loc,date,pri))
print("=== ADDITIONS by section ===")
for pre in ('Lessons/','Games/','Matt-s-Apps-/'): print(f"  {pre:16} +{len(bysec[pre])}")
print("=== SKIPPED (excluded by rule/policy) ===")
for rel,why in sorted(skipped): print(f"  - {rel}  [{why}]")
lines=["  <!-- Pass U whole-domain coverage additions (generated by _passu/gen_coverage.py from pinned trees:",
       "       Lessons@32ca685e Games@43bf1f8a Matt-s-Apps-@27d4e0ac; true last-commit lastmods; dead locs=0, additive only). -->"]
for pre in ('Lessons/','Games/','Matt-s-Apps-/'):
    if not bysec[pre]: continue
    lines.append(f"  <!-- +{len(bysec[pre])} {pre} -->")
    for loc,date,pri in sorted(bysec[pre]):
        lines.append(f"  <url>\n    <loc>{loc}</loc>\n    <lastmod>{date}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>{pri}</priority>\n  </url>")
open('_passu/coverage_block.xml','w').write('\n'.join(lines)+'\n')
print(f"\nTOTAL additions: {len(added)}  (skipped {len(skipped)})")
