/* The stamped inline exit region, and one place that knows how to remove it.
 *
 * Eleven declared single-file games carry an inline exit control instead of
 * <script src="/hud.js">, because their own verifiers forbid the external
 * script. Those verifiers police things about THE GAME: how many script blocks
 * it has, that every localStorage access goes through its own prefixed helper,
 * that reversing the permitted edits reproduces the delivered artifact.
 *
 * The region is not the game. It is a platform control stamped into the file by
 * tools/render_inline_exit.py, identical in all eleven, and it reads one
 * platform key (mbm_audience_view) that has nothing to do with the game's save.
 * So the gates that judge the game judge the file with the region removed, and
 * assert separately that the region is present.
 *
 * WHY A SHARED HELPER AND NOT FIVE COPIES OF A REGEX
 * Five hand-written strippers is the second-literal trap five times over: the
 * day the region's marker text changes, four of them keep passing against a
 * file they are no longer removing anything from. One definition, imported.
 *
 * WHAT THIS DELIBERATELY DOES NOT DO
 * It does not check that the region is byte-identical across the eleven, and it
 * does not check that the control renders. Those are separate jobs and they
 * belong to tools/verify_inline_exit.mjs, which does them in a browser. The
 * /neonbreach/ precedent is the warning: a verifier was amended to admit a
 * script, the script then rendered nothing for months, and the amendment was
 * never paired with anything that would notice.
 */
'use strict';

const BEGIN = '<!-- MBM-INLINE-EXIT:BEGIN generated by tools/render_inline_exit.py, do not edit by hand -->';
const END = '<!-- MBM-INLINE-EXIT:END -->';

const esc = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const REGION_RE = new RegExp(esc(BEGIN) + '[\\s\\S]*?' + esc(END) + '\\n?');

/** True when the file carries the stamped region. */
function hasExitRegion(html) {
  return REGION_RE.test(html);
}

/** The region as stamped, or null. */
function exitRegion(html) {
  const m = html.match(REGION_RE);
  return m ? m[0] : null;
}

/** The file as the game ships it, with the platform's region removed.
 *  Gates that judge the game's own contract run against this. */
function stripExitRegion(html) {
  return html.replace(REGION_RE, '');
}

module.exports = { BEGIN, END, REGION_RE, hasExitRegion, exitRegion, stripExitRegion };
