#!/usr/bin/env python3
"""Generate the inline exit control and stamp it into the declared single-file games.

WHY THIS EXISTS
---------------
Eleven root-level games ship under a contract their own verifier enforces: a
single self-contained HTML file, no external script, and in several cases a
pinned byte ledger or source SHA.  data/hud-coverage.json declares them, in both
this repository and MattRoper1977/Lessons, precisely because adding
<script src="/hud.js"> to one of them retracts a promise the game makes.

The consequence recorded there was that a visitor playing one of the eleven has
the browser Back button and nothing else.  On a locked-down school device the
browser chrome may not be there at all, so a child finishing echovault or
relicforge has no way out of the page.  This tool gives them one WITHOUT adding
a dependency: an inline control, generated once, stamped byte-identically into
every declared file.

ONE GENERATOR, NEVER HAND-COPIED
--------------------------------
Eleven hand-written copies of one control is the second-literal trap eleven
times over.  The region below is built once, from the data files that own the
values, and written to every target.  --check asserts every stamped region is
byte-identical to the freshly generated one, so a hand-edit in any single file
is a red gate rather than a silent divergence.

NO RUNTIME FETCH (R3)
---------------------
The homepage map is spliced in at build time from data/audience-homepages.json,
exactly as hud.js's MBM-HOMEPAGE-CHOICES region is, and for the same reason: a
fetch on a game's load path would put a request in front of a child mid-session
and break the offline promise.

MEMBERSHIP IS DERIVED, NOT TYPED
--------------------------------
The target list comes from data/hud-coverage.json in each repository - the file
that already owns "which games cannot carry hud.js".  hud.js embeds a ROOT_GAMES
map because it is served onto every page type and must ask "am I a game?" at run
time.  This region is only ever stamped into files that ARE games, so it asks no
such question and carries no second copy of that inventory.

Usage:
  render_inline_exit.py --root SITE_ROOT [--root LESSONS_ROOT ...] [--check]
"""
import argparse
import hashlib
import json
import os
import re
import sys

BEGIN = "<!-- MBM-INLINE-EXIT:BEGIN generated by tools/render_inline_exit.py, do not edit by hand -->"
END = "<!-- MBM-INLINE-EXIT:END -->"
REGION_RE = re.compile(
    re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.DOTALL)

# The glyph hud.js draws for the chosen-homepage control, character for
# character, so the two controls read as one family across the estate.
HOME_GLYPH = (
    '<svg viewBox=\\"0 0 24 24\\" width=\\"15\\" height=\\"15\\" aria-hidden=\\"true\\" '
    'focusable=\\"false\\" fill=\\"none\\" stroke=\\"currentColor\\" stroke-width=\\"2\\" '
    'stroke-linecap=\\"round\\" stroke-linejoin=\\"round\\">'
    '<path d=\\"M4 10.6 12 4.2l8 6.4\\"/><path d=\\"M6.2 9.6V19.8h11.6V9.6\\"/></svg>'
)

CSS = (
    "#mbmexit-back,#mbmexit-home{position:fixed;top:calc(8px + env(safe-area-inset-top,0px));"
    "z-index:2147483000;width:44px;height:44px;min-width:44px;min-height:44px;box-sizing:border-box;"
    "display:flex;align-items:center;justify-content:center;border-radius:50%;"
    "background:rgba(22,29,61,.72);color:#B9E6CD;border:1.5px solid rgba(185,230,205,.45);"
    "font:700 16px/1 Poppins,'Segoe UI',system-ui,sans-serif;text-decoration:none;"
    "-webkit-backdrop-filter:blur(6px);backdrop-filter:blur(6px);opacity:.55}"
    "#mbmexit-back{left:calc(8px + env(safe-area-inset-left,0px))}"
    "#mbmexit-home{left:calc(58px + env(safe-area-inset-left,0px))}"
    "#mbmexit-back:hover,#mbmexit-home:hover{opacity:1;border-color:#B9E6CD}"
    "#mbmexit-back:focus-visible,#mbmexit-home:focus-visible{opacity:1;outline:3px solid #F2A24A;"
    "outline-offset:2px;border-color:#B9E6CD}"
    "@media print{#mbmexit-back,#mbmexit-home{display:none!important}}"
)

# The script. Kept deliberately plain: no optional chaining, no arrow
# functions, no template literals, so it parses in whatever the school device
# is running and survives `node --check` on an extracted block.
JS_TEMPLATE = """(function(){"use strict";
try{
if(window.__mbmExit)return;window.__mbmExit=1;
var HOMES=__HOMES__;
var KEY="mbm_audience_view";
function lsGet(k){try{var v=localStorage.getItem(k);return v===null?"":v;}catch(e){return "";}}
function el(t,a,h){var e=document.createElement(t);for(var k in a)e.setAttribute(k,a[k]);if(h!==undefined)e.innerHTML=h;return e;}
function adultOff(){try{var d=document.documentElement,b=document.body;
return (d&&d.getAttribute("data-mbm-adult-features")==="off")||(b&&b.getAttribute("data-mbm-adult-features")==="off");}catch(e){return false;}}
function chosen(){var v=lsGet(KEY);
if(!Object.prototype.hasOwnProperty.call(HOMES,v))return null;
var h=HOMES[v];
if(h.r==="/main/"&&adultOff())return null;
return h;}
function mount(){
if(!document.body||document.getElementById("mbmexit-back"))return;
var st=document.createElement("style");st.id="mbmexit-style";st.textContent=__CSS__;
(document.head||document.documentElement).appendChild(st);
var back=el("a",{id:"mbmexit-back",href:"/games/","aria-label":"Back: Arcade",title:"Back to the Arcade"},"\\u2190");
document.body.appendChild(back);
var h=chosen();
if(h){var home=el("a",{id:"mbmexit-home",href:h.r,"aria-label":"Your homepage: "+h.l,title:"Your homepage: "+h.l},"__GLYPH__");
document.body.appendChild(home);}
}
if(document.body)mount();else document.addEventListener("DOMContentLoaded",mount);
}catch(e){}
})();"""


def build_region(homes):
    """Build the stamped region. Byte-identical for every target by construction."""
    homes_js = json.dumps(
        {k: {"r": v["r"], "l": v["l"]} for k, v in homes.items()},
        separators=(",", ":"), ensure_ascii=True)
    js = (JS_TEMPLATE
          .replace("__HOMES__", homes_js)
          .replace("__CSS__", json.dumps(CSS, ensure_ascii=True))
          .replace("__GLYPH__", HOME_GLYPH))
    return BEGIN + "\n<script>" + js + "</script>\n" + END + "\n"


def write_helper(root, check):
    """Emit tools/mbm_exit_region.js into a checkout.

    Both repositories' verifiers need to remove the region before judging the
    game's own contract, and neither can require() a file in the other. Two
    hand-written strippers is the second-literal trap twice over, so this
    generator writes both copies and --check asserts they are byte-identical.
    """
    src = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mbm_exit_region.js")
    body = open(src, encoding="utf-8").read()
    dest = os.path.join(root, "tools", "mbm_exit_region.js")
    if os.path.abspath(dest) == os.path.abspath(src):
        return "source"
    if os.path.exists(dest) and open(dest, encoding="utf-8").read() == body:
        return "ok"
    if check:
        return "drift"
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    open(dest, "w", encoding="utf-8").write(body)
    return "written"


def read_homes(site_root):
    """The homepage map, from the file that owns those values.

    hud.js carries the same map behind MBM-HOMEPAGE-CHOICES, generated from the
    same source by render_audience_homepages.py. Reading hud.js's generated
    region rather than re-deriving the shape keeps the two provably in step:
    a drift between them is a red --check here, not a difference nobody sees.
    """
    hud = open(os.path.join(site_root, "hud.js"), encoding="utf-8").read()
    m = re.search(r"var HOMES\s*=\s*(\{.*?\});", hud, re.DOTALL)
    if not m:
        sys.exit("hud.js: MBM-HOMEPAGE-CHOICES HOMES map not found")
    raw = m.group(1)
    # The generated literal uses bare keys r/l; normalise to JSON.
    raw = re.sub(r"([{,])(\w+):", r'\1"\2":', raw)
    return json.loads(raw)


def targets_for(root):
    """Declared single-file games in this checkout, derived from its own ledger."""
    cov = os.path.join(root, "data", "hud-coverage.json")
    if not os.path.exists(cov):
        return []
    data = json.load(open(cov, encoding="utf-8"))
    out = []
    for entry in data.get("excluded", []):
        route = entry["route"]
        if route.endswith(".html"):
            # A Lessons route: /Lessons/Games/X.html served from repo root.
            rel = route[len("/Lessons/"):] if route.startswith("/Lessons/") else route.lstrip("/")
        else:
            rel = route.strip("/") + "/index.html"
        path = os.path.join(root, rel)
        if os.path.exists(path):
            out.append((route, path))
        else:
            sys.exit("declared route %s has no file at %s" % (route, path))
    return out


def insert_point(html):
    """Before the last </body>, but ahead of any trailing comments it carries.

    biopunkhive asserts its build sentinel sits immediately before </body>;
    stamping between the two would break a gate that is doing its job. Walking
    back over trailing comments handles that without naming the game.
    """
    idx = html.rfind("</body>")
    if idx < 0:
        return None
    head = html[:idx]
    while True:
        stripped = head.rstrip()
        if stripped.endswith("-->"):
            start = stripped.rfind("<!--")
            if start < 0:
                break
            head = stripped[:start]
            idx = start
            continue
        break
    return idx


def stamp(path, region, check):
    html = open(path, encoding="utf-8").read()
    existing = REGION_RE.search(html)
    if existing:
        if existing.group(0) == region:
            return "ok"
        if check:
            return "drift"
        html = REGION_RE.sub("", html, count=1)
    elif check:
        return "missing"
    at = insert_point(html)
    if at is None:
        sys.exit("%s: no </body> to stamp before" % path)
    out = html[:at] + region + html[at:]
    open(path, "w", encoding="utf-8").write(out)
    return "stamped"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", action="append", required=True,
                    help="a checkout to stamp; the first must be the site repo")
    ap.add_argument("--check", action="store_true",
                    help="assert every region is present and byte-identical; never write")
    args = ap.parse_args()

    site_root = args.root[0]
    region = build_region(read_homes(site_root))
    digest = hashlib.sha256(region.encode("utf-8")).hexdigest()

    print("region: %d bytes, sha256 %s" % (len(region.encode("utf-8")), digest))
    bad = 0
    total = 0
    for root in args.root:
        res = write_helper(root, args.check)
        print("  %-8s tools/mbm_exit_region.js  (%s)" % (res, root))
        if res == "drift":
            bad += 1
        for route, path in targets_for(root):
            total += 1
            res = stamp(path, region, args.check)
            size = os.path.getsize(path)
            print("  %-8s %-40s %8d B  %s" % (res, route, size, os.path.relpath(path, root)))
            if res in ("drift", "missing"):
                bad += 1
    if total == 0:
        sys.exit("no targets found - refusing to report success over an empty sweep")
    print("%d target(s); %d divergent" % (total, bad))
    if bad:
        sys.exit(1)


if __name__ == "__main__":
    main()
