#!/usr/bin/env python3
"""Generate the Made by Matt splash and stamp it into the site-root games that lack one.

WHY THIS EXISTS
Matt reported Echo Vault's missing splash from a phone. A census of all nineteen
site-root routes says how many siblings share it: FOUR carry no splash at all -
/biopunkhive/, /echovault/, /fracture/ and /relicforge/.

Getting that list right took three instruments, and the first two were wrong.
A browser poll at 150 ms across 4.5 s (never a single sample - a splash that
self-closes at 1.4 s reads as absent to one) called all nineteen "bespoke",
because it measured "is something covering the screen", which is a different
question from "did a splash play": a title screen covers the viewport and never
leaves. Requiring the overlay to VANISH fixed that. A source grep for
id="...splash..." then missed /olympics/, which builds its splash in JavaScript,
and missed /novasiege/, whose splash is the canonical donor and uses classes
rather than ids. Only the third instrument - the literal `mbm-splash-inline`,
which is what the estate's own gates derive their targets from - was right.

/fracture/ has a #loading-screen, which is not a splash: it says the game is
busy, not who made it.

ONE GENERATOR, NEVER HAND-COPIED
Four hand-written splashes is one literal repeated four times, and the first
divergence would be invisible. --check asserts every stamped region is
byte-identical to a freshly generated one.

BYTE-IDENTICAL, WHICH MEANS NOTHING PER-FILE IS BAKED IN
The slug and the title are DERIVED AT RUNTIME - the slug from location.pathname,
the title from document.title. Baking either one in would give four different
regions and leave nothing to byte-compare.

PRESERVE EVERY BESPOKE SPLASH
Fifteen of the nineteen already brand themselves and are not touched - twelve
bespoke, and /novasiege/ and /olympics/ carrying this same donor already. An
earlier draft of this file stamped novasiege a second time; its own verifier
caught it.

WHAT IS STAMPED
assets/brand/mbm-splash.js, inlined VERBATIM, plus a small bootstrap. Verbatim
because tools/verify_novasiege.mjs asserts byte-identity with that donor, and
because inventing new splash markup here would have been a third grammar beside
the donor and the twelve bespoke ones.

Usage:
  render_splash.py --root SITE_ROOT [--check]
"""
import argparse
import hashlib
import json
import os
import re
import sys

BEGIN = "<!-- MBM-SPLASH:BEGIN generated by tools/render_splash.py, do not edit by hand -->"
END = "<!-- MBM-SPLASH:END -->"
REGION_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.DOTALL)

# The four that the census found carrying no splash. Declared rather than
# derived from a live browser run, because a generator that boots nineteen games
# to decide what to write is a generator nobody can run offline - and because
# which games get a Made by Matt splash is a branding decision, not a fact about
# the filesystem. The census that produced this list is recorded in the commit.
TARGETS = ["biopunkhive", "echovault", "fracture", "relicforge"]


# ---------------------------------------------------------------- HELD
# THIS GENERATOR IS HELD, AND WILL REFUSE TO STAMP, UNTIL THE DONOR IS FIXED.
#
# Stamping the donor into four games and judging them with the estate's own
# splash gate produced 478 passed and 26 FAILED, every failure the same
# assertion: S2/S3 "<key> does not leak to the game (keydown 0->1)".
#
# The donor listens for keydown on the SPLASH ELEMENT and for click on
# .mbm-skip, and stops neither. The gate counts keydown/click on `window` in the
# bubble phase, the way a game's own listeners do. So pressing Space to skip the
# splash also presses Space in the game underneath: the intro is skipped and the
# player has fired, jumped or started a run they never asked for. On a phone the
# tap that dismisses the splash is the tap that starts the game.
#
# This is a defect in assets/brand/mbm-splash.js, not in the four games and not
# in the gate. It is ALREADY SHIPPED in /novasiege/ and /olympics/, which inline
# this donor verbatim and have never been held to that assertion because they
# sit outside the gate's default scope. Fixing it means editing the donor,
# re-inlining it into those two games, and moving their pinned SHAs and byte
# ledgers - a change to two live games that deserves its own sitting rather than
# the tail of a long pass.
#
# The fix is small and known: while the splash is up, take keydown/keyup/click/
# pointerdown on `document` in the CAPTURE phase, stopPropagation, and remove
# the listeners in close(). tools/render_inline_exit.py's region does exactly
# this and passes the same assertion.
#
# Remove this guard in the same commit that fixes the donor, and not before.
HELD_UNTIL_DONOR_STOPS_SKIP_LEAK = True

DONOR_REL = os.path.join("assets", "brand", "mbm-splash.js")

# The bootstrap. Deliberately tiny, and it derives the title AT RUNTIME from
# document.title so every stamped copy of this region is byte-identical - a
# per-file title baked in would give four different regions and leave nothing to
# byte-compare. `mbm-splash-inline` is the literal the estate's gates derive
# their target lists from, so it stays exactly as novasiege and olympics carry it.
BOOTSTRAP = """
(function(){try{
if(!window.MadeByMattSplash||window.__mbmSplashStarted)return;window.__mbmSplashStarted=1;
var t=(document.title||"").split(/\\s+[\\u2014\\u2013-]\\s+/)[0].trim();
var slug=(location.pathname||"").replace(/index\\.html$/,"").replace(/^\\/|\\/$/g,"").split("/").pop()||"mbm";
function go(){
  MadeByMattSplash.start({title:t,kicker:"A Made by Matt Game",duration:3000});
  var el=document.querySelector(".mbm-splash");
  if(el){el.setAttribute("data-mbm-splash",slug);el.setAttribute("data-mbm-splash-state","open");
    var obs=setInterval(function(){if(!el.isConnected){el.setAttribute("data-mbm-splash-state","closed");clearInterval(obs);}},120);}
}
if(document.body)go();else document.addEventListener("DOMContentLoaded",go);
}catch(e){}})();"""


def build_region(root):
    """The canonical donor, inlined verbatim, plus a byte-identical bootstrap.

    Verbatim matters: tools/verify_novasiege.mjs asserts the inlined block is
    byte-identical to assets/brand/mbm-splash.js, and that is the standard this
    estate already keeps for a site-root game's splash. An earlier draft of this
    generator invented its own splash markup instead, which would have been a
    THIRD grammar beside the donor and the twelve bespoke ones - and it stamped
    novasiege, which already had the donor, with a second splash on top. The
    gate caught it.
    """
    donor = open(os.path.join(root, DONOR_REL), encoding="utf-8").read().rstrip("\n")
    return (BEGIN + "\n"
            + "<!-- mbm-splash-inline: canonical Made by Matt splash, inlined from the games estate standard. -->\n"
            + "<script>\n" + donor + "\n" + BOOTSTRAP + "\n</script>\n"
            + END + "\n")


def insert_point(html):
    """Immediately after the <body ...> opening tag.

    A splash must paint over the game, and a game that builds its own
    full-screen UI on load will otherwise be underneath something that arrives
    later in the document. z-index alone is not enough when a later element
    creates its own stacking context.
    """
    m = re.search(r"<body\b[^>]*>", html, re.IGNORECASE)
    return m.end() if m else None


def stamp(path, region, check):
    html = open(path, encoding="utf-8").read()
    found = REGION_RE.search(html)
    if found:
        if found.group(0) == region:
            return "ok"
        if check:
            return "drift"
        html = REGION_RE.sub("", html, count=1)
    elif check:
        return "missing"
    at = insert_point(html)
    if at is None:
        sys.exit("%s: no <body> to stamp after" % path)
    open(path, "w", encoding="utf-8").write(html[:at] + "\n" + region + html[at:])
    return "stamped"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if HELD_UNTIL_DONOR_STOPS_SKIP_LEAK and not args.check:
        sys.exit("render_splash.py is HELD: assets/brand/mbm-splash.js lets the skip key and the "
                 "skip tap through to the game underneath (26 S2/S3 failures). Read the block at "
                 "the top of this file. Fix the donor first; stamping it now ships that defect "
                 "into four more games.")

    region = build_region(args.root)
    digest = hashlib.sha256(region.encode()).hexdigest()
    print("region: %d bytes, sha256 %s" % (len(region.encode()), digest))

    bad = 0
    for slug in TARGETS:
        path = os.path.join(args.root, slug, "index.html")
        if not os.path.exists(path):
            sys.exit("declared target /%s/ has no file at %s" % (slug, path))
        res = stamp(path, region, args.check)
        print("  %-8s /%s/%s %8d B" % (res, slug, " " * (13 - len(slug)), os.path.getsize(path)))
        if res in ("drift", "missing"):
            bad += 1
    if not TARGETS:
        sys.exit("no targets - refusing to report success over an empty sweep")
    print("%d target(s); %d divergent" % (len(TARGETS), bad))
    if bad:
        sys.exit(1)


if __name__ == "__main__":
    main()
