#!/usr/bin/env python3
"""Generate the Made by Matt splash and stamp it into the site-root games that lack one.

WHY THIS EXISTS
Matt reported Echo Vault's missing splash from a phone. A census of all nineteen
site-root routes says how many siblings share it: FOUR carry no splash at all -
/biopunkhive/, /echovault/, /fracture/ and /relicforge/.

Getting that list right took three instruments, and the first two were wrong.
A browser poll at 150 ms across 4.5 s (never a single sample - a splash that
self-closes at 1.4 s reads as absent to one) called all nineteen "bespoke",
because it measured "is something covering the screen", which is a different
question from "did a splash play": a title screen covers the viewport and never
leaves. Requiring the overlay to VANISH fixed that. A source grep for
id="...splash..." then missed /olympics/, which builds its splash in JavaScript,
and missed /novasiege/, whose splash is the canonical donor and uses classes
rather than ids. Only the third instrument - the literal `mbm-splash-inline`,
which is what the estate's own gates derive their targets from - was right.

/fracture/ has a #loading-screen, which is not a splash: it says the game is
busy, not who made it.

ONE GENERATOR, NEVER HAND-COPIED
Four hand-written splashes is one literal repeated four times, and the first
divergence would be invisible. --check asserts every stamped region is
byte-identical to a freshly generated one.

BYTE-IDENTICAL, WHICH MEANS NOTHING PER-FILE IS BAKED IN
The slug and the title are DERIVED AT RUNTIME - the slug from location.pathname,
the title from document.title. Baking either one in would give four different
regions and leave nothing to byte-compare.

PRESERVE EVERY BESPOKE SPLASH
Fifteen of the nineteen already brand themselves and are not touched - twelve
bespoke, and /novasiege/ and /olympics/ carrying this same donor already. An
earlier draft of this file stamped novasiege a second time; its own verifier
caught it.

WHAT IS STAMPED
assets/brand/mbm-splash.js, inlined VERBATIM, plus a small bootstrap. Verbatim
because tools/verify_novasiege.mjs asserts byte-identity with that donor, and
because inventing new splash markup here would have been a third grammar beside
the donor and the twelve bespoke ones.

Usage:
  render_splash.py --root SITE_ROOT [--check]
"""
import argparse
import hashlib
import json
import os
import re
import sys

BEGIN = "<!-- MBM-SPLASH:BEGIN generated by tools/render_splash.py, do not edit by hand -->"
END = "<!-- MBM-SPLASH:END -->"
REGION_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.DOTALL)

# The four that the census found carrying no splash. Declared rather than
# derived from a live browser run, because a generator that boots nineteen games
# to decide what to write is a generator nobody can run offline - and because
# which games get a Made by Matt splash is a branding decision, not a fact about
# the filesystem. The census that produced this list is recorded in the commit.
TARGETS = ["apexcurl", "apexvelodrome", "biopunkhive", "echovault", "fracture", "relicforge"]


# ------------------------------------------------------- HELD, THEN RESOLVED
# THE HOLD IS LIFTED. It is kept here as history because the defect it names is
# the reason this generator sat unused, and because the next person to touch the
# donor needs to know what the assertion is actually for.
#
# WHAT WAS WRONG. Stamping the donor into four games and judging them with the
# estate's own splash gate produced 478 passed and 26 FAILED, every failure the
# same assertion: S2/S3 "<key> does not leak to the game (keydown 0->1)". The
# donor listened for keydown on the SPLASH ELEMENT and for click on .mbm-skip,
# and stopped neither: e.preventDefault() suppresses a default action, it does
# not stop propagation. So the Space that skipped the intro also reached the
# game underneath, and on a phone the tap that dismissed the splash was the tap
# that started the game.
#
# WHAT FIXED IT. assets/brand/mbm-splash.js now takes keydown, keyup, click,
# pointerdown and pointerup on `document` in the CAPTURE phase and stops them
# there - before they can descend to a target or bubble back out to `window`,
# where a game's own listeners sit - and removes those listeners a short window
# after dismissal, so the trailing keyup / pointerup / click of the dismissing
# gesture is swallowed too. Measured before and after with a probe that counts
# bubble-phase events on `window`, the way a game's own listeners do:
#     BEFORE  Space -> keydown 1, keyup 1 | Escape -> keydown 1, keyup 1
#             skip tap -> click 1, pointerdown 1, pointerup 1
#     AFTER   all three dismissal paths -> 0 across every counted event,
#             and the splash still dismisses in every case.
# The original note named keydown and click; the measurement also found keyup
# and pointerup leaking, so the fix covers five event types rather than three.
#
# STILL OUTSTANDING, DELIBERATELY. /olympics/ carries a DRIFTED copy of this
# donor - not byte-identical to it and not stamped by this generator - so it is
# a bespoke splash and is preserved as one. It keeps a partially-hardened
# variant of the same code and has never been held to this assertion. That is
# its own sitting. /novasiege/ inlined the donor verbatim and has been
# re-inlined with the fixed one, because tools/verify_novasiege.mjs compares the
# two byte for byte.
HELD_UNTIL_DONOR_STOPS_SKIP_LEAK = False

# ------------------------------------------------------- DECLARED EXCEPTIONS
# Routes that carry a splash this generator does NOT own, and must not stamp.
# Declared 2026-08-23, so the next sweep finds a decision here rather than
# re-deriving the same question from the drift.
#
# /olympics/ — BESPOKE, KEEP.
#   It inlines a splash that is not this donor and is not stale: measured
#   6,469 B against the donor's 6,248 B, 72 lines present that the donor does
#   not have. The differences are DESIGN, not decay — an Olympic rings mark
#   (.marc arcs on staggered .a1/.a2/.a3 delays) and a torch flame (.mflame)
#   in place of the donor's M-path and star, on a deep-blue #0b2141/#050816
#   ground with a gold #ffd75e kicker instead of the house #222B55 and #F2A24A.
#   Stamping the donor over it would destroy a deliberate variant, so the
#   exception is the right call and adopting the generated block is not.
#
#   RECORDED HONESTLY, BECAUSE THE EXCEPTION IS NOT A CLEAN BILL OF HEALTH:
#   this variant still leaks its own dismissal, measured 2026-08-23 with the
#   same bubble-phase probe used on the donor —
#       Space  -> keyup 1     Escape -> keyup 1
#       skip tap -> pointerdown 1, pointerup 1
#   It is partially hardened already (it takes keydown on capture, which is why
#   keydown does not leak) but does not stop keyup or the pointer pair. That is
#   a smaller defect than the donor's was and it is a change to a live game with
#   its own pinned SHAs, so it is its own sitting rather than the tail of this
#   one. It is on the books now instead of being rediscovered.
#
# /novasiege/ is NOT an exception: it inlines this donor VERBATIM, and
# tools/verify_novasiege.mjs byte-compares the two. It was re-inlined with the
# fixed donor in the same pass that lifted the hold.
DECLARED_EXCEPTIONS = {
    "olympics": "bespoke Olympic rings/torch variant, declared 2026-08-23; "
                "still leaks keyup and the pointer pair — its own sitting",
}


DONOR_REL = os.path.join("assets", "brand", "mbm-splash.js")

# The bootstrap. Deliberately tiny, and it derives the title AT RUNTIME from
# document.title so every stamped copy of this region is byte-identical - a
# per-file title baked in would give four different regions and leave nothing to
# byte-compare. `mbm-splash-inline` is the literal the estate's gates derive
# their target lists from, so it stays exactly as novasiege and olympics carry it.
BOOTSTRAP = """
(function(){try{
if(!window.MadeByMattSplash||window.__mbmSplashStarted)return;window.__mbmSplashStarted=1;
var t=(document.title||"").split(/\\s+[\\u2014\\u2013-]\\s+/)[0].trim();
var slug=(location.pathname||"").replace(/index\\.html$/,"").replace(/^\\/|\\/$/g,"").split("/").pop()||"mbm";
function go(){
  MadeByMattSplash.start({title:t,kicker:"A Made by Matt Game",duration:3000});
  var el=document.querySelector(".mbm-splash");
  if(el){el.setAttribute("data-mbm-splash",slug);el.setAttribute("data-mbm-splash-state","open");
    var obs=setInterval(function(){if(!el.isConnected){el.setAttribute("data-mbm-splash-state","closed");clearInterval(obs);}},120);}
}
if(document.body)go();else document.addEventListener("DOMContentLoaded",go);
}catch(e){}})();"""


def build_region(root):
    """The canonical donor, inlined verbatim, plus a byte-identical bootstrap.

    Verbatim matters: tools/verify_novasiege.mjs asserts the inlined block is
    byte-identical to assets/brand/mbm-splash.js, and that is the standard this
    estate already keeps for a site-root game's splash. An earlier draft of this
    generator invented its own splash markup instead, which would have been a
    THIRD grammar beside the donor and the twelve bespoke ones - and it stamped
    novasiege, which already had the donor, with a second splash on top. The
    gate caught it.
    """
    donor = open(os.path.join(root, DONOR_REL), encoding="utf-8").read().rstrip("\n")
    return (BEGIN + "\n"
            + "<!-- mbm-splash-inline: canonical Made by Matt splash, inlined from the games estate standard. -->\n"
            + "<script>\n" + donor + "\n" + BOOTSTRAP + "\n</script>\n"
            + END + "\n")


def insert_point(html):
    """Immediately after the <body ...> opening tag.

    A splash must paint over the game, and a game that builds its own
    full-screen UI on load will otherwise be underneath something that arrives
    later in the document. z-index alone is not enough when a later element
    creates its own stacking context.
    """
    m = re.search(r"<body\b[^>]*>", html, re.IGNORECASE)
    return m.end() if m else None


def stamp(path, region, check):
    html = open(path, encoding="utf-8").read()
    found = REGION_RE.search(html)
    if found:
        if found.group(0) == region:
            return "ok"
        if check:
            return "drift"
        html = REGION_RE.sub("", html, count=1)
    elif check:
        return "missing"
    at = insert_point(html)
    if at is None:
        sys.exit("%s: no <body> to stamp after" % path)
    open(path, "w", encoding="utf-8").write(html[:at] + "\n" + region + html[at:])
    return "stamped"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if HELD_UNTIL_DONOR_STOPS_SKIP_LEAK and not args.check:
        sys.exit("render_splash.py is HELD: assets/brand/mbm-splash.js lets the skip key and the "
                 "skip tap through to the game underneath (26 S2/S3 failures). Read the block at "
                 "the top of this file. Fix the donor first; stamping it now ships that defect "
                 "into four more games.")

    region = build_region(args.root)
    digest = hashlib.sha256(region.encode()).hexdigest()
    print("region: %d bytes, sha256 %s" % (len(region.encode()), digest))

    bad = 0
    for slug in TARGETS:
        path = os.path.join(args.root, slug, "index.html")
        if not os.path.exists(path):
            sys.exit("declared target /%s/ has no file at %s" % (slug, path))
        res = stamp(path, region, args.check)
        print("  %-8s /%s/%s %8d B" % (res, slug, " " * (13 - len(slug)), os.path.getsize(path)))
        if res in ("drift", "missing"):
            bad += 1
    if not TARGETS:
        sys.exit("no targets - refusing to report success over an empty sweep")
    print("%d target(s); %d divergent" % (len(TARGETS), bad))
    if bad:
        sys.exit(1)


if __name__ == "__main__":
    main()
