#!/usr/bin/env python3
"""Generate AS1's opted-in in-document pilot region; never sweep game files."""
import argparse
import importlib.util
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
BEGIN = '<!-- MBM-AS1:BEGIN generated by tools/render_arcade_pilot.py -->'
END = '<!-- MBM-AS1:END -->'
REGION = re.compile(re.escape(BEGIN)+r'.*?'+re.escape(END)+r'\n?', re.S)

def generate():
    spec=importlib.util.spec_from_file_location('exitgen',ROOT/'tools/render_inline_exit.py')
    module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module)
    pilot=json.loads((ROOT/'data/as1-pilot.json').read_text())
    path=ROOT/pilot['path'];html=path.read_text()
    assert module.REGION_RE.search(html).group()==module.build_region(module.read_homes(str(ROOT))), 'Canonical inline exit drift'
    tokens=(ROOT/'assets/mbm-tokens.css').read_text()
    brand=(ROOT/'assets/brand/brand-tokens.css').read_text()
    brand=brand[brand.index(':root{'):brand.index('\n.mbm-btn')]
    codec=(ROOT/'assets/arcade/cartridge.js').read_text()
    ghost=(ROOT/'assets/arcade/ghost.js').read_text()
    shell=(ROOT/'assets/arcade/shell.js').read_text()
    adapter=(ROOT/'assets/game-saves.js').read_text().split("  if (typeof document === 'undefined') return;")[0]
    adapter+="  root.MBMGameSaves=api;\n})(globalThis);\n"
    rules=json.loads((ROOT/'data/game-storage-allowlist.json').read_text())
    # Only this pilot's existing transfer grant; shared profiles and careers stay out.
    rules['localStorageExactKeys']=[k for k in rules['localStorageExactKeys'] if k.startswith('mbm_rallyvector_')]
    rules['localStorageDynamicFamilies']=[];rules['sharedGameProfileSubtrees']=[]
    config='window.MBMAS1Rules='+json.dumps(rules,separators=(',',':'))+';\nwindow.MBMAS1Sizing='+ (ROOT/'data/as1-sizing.json').read_text().strip()+';'
    vendor=(ROOT/'assets/arcade/vendor/pako-1.0.11.min.js').read_text()
    licence=(ROOT/'assets/arcade/vendor/pako-LICENSE.txt').read_text()
    region=BEGIN+'\n<style>\n'+tokens+'\n'+brand+'\n'+(ROOT/'assets/arcade/shell.css').read_text()+'</style>\n'
    region+='<script>\n/* '+licence+' */\n'+vendor+'\n'+adapter+config+'\n'+codec+ghost+shell+'\nwindow.MBMArcadeHooks.loadGhost();\n</script>\n'
    region+='<noscript><a href="/games/">Exit to the Arcade</a></noscript>\n'+END+'\n'
    if REGION.search(html):html=REGION.sub(lambda _:region,html,count=1)
    else:html=html.replace('</body>',region+'</body>')
    hooks=(ROOT/'assets/arcade/rally-hooks.js').read_text()
    start='/* MBM-AS1-HOOKS:BEGIN */';end='/* MBM-AS1-HOOKS:END */'
    block=start+'\n'+hooks+end+'\n'
    pattern=re.compile(re.escape(start)+r'.*?'+re.escape(end)+r'\n?',re.S)
    if pattern.search(html):html=pattern.sub(lambda _:block,html,count=1)
    else:html=html.replace('v6Install();\nboot();','v6Install();\n'+block+'boot();')
    assert html.count(start)==1 and html.count(BEGIN)==1
    return path,html

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path,html=generate()
    if args.check:
        if path.read_text()!=html:raise SystemExit('AS1 pilot generation drift')
        print('AS1 pilot generator GREEN')
    else:path.write_text(html);print('Generated only '+str(path.relative_to(ROOT)))
