#!/usr/bin/env python3
"""
stamp-data.py — content-hash the data files this repo owns, and splice the
stamp into every page that fetches one.

Why this exists
---------------
Matt's phone showed a homepage that does not exist in the tree: the old
four-door site.json, rendered by a renderer that has since been deleted. The
mechanism was in the source the whole time. Two scripts fetched the SAME url:

    assets/mbm-doors.js:328   fetch(url, { cache: "no-cache" })   -> revalidates
    assets/mbm-features.js:44 fetch(url, o)  with no cache option -> may be stale

So on one page load, one renderer drew the current nine doors into the zone
strips and the other drew a cached four-door copy underneath them. Nothing on
the page could notice or correct it, and no visitor could be told to fix it.

A cache mode is a per-call-site decision that has to be got right at every call
site. A stamped url is not: the url IS the version, so a stale copy cannot be
addressed at all.

What is stamped, and what deliberately is not
---------------------------------------------
STAMPED — data files this repo owns and can therefore hash:
    site.json, data/resources.json

NOT STAMPED — data files that live in OTHER repositories:
    /Lessons/resources.json, /Games/games.json
    This repo cannot hash them. A number copied by hand from another repo is
    the studio count all over again: it was written down as 28, then 29, and
    was 30 the whole time (98b0a59). So these get forced revalidation instead
    of a version this repo would be inventing. Honest and slightly slower
    beats confident and wrong.

NOT STAMPED — third-party endpoints (api.counterapi.dev). Not data files, not
    ours, and their call sites are left exactly as they were.

Usage
-----
    python3 tools/stamp-data.py           rewrite the stamp block in every page
    python3 tools/stamp-data.py --check   exit 1 if any page is out of date

--check is the drift instrument: it fails when a data file has changed and the
pages still carry the old hash. Run it before shipping.
"""

import hashlib
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Data files this repo owns. A path added here is stamped everywhere at once.
DATA = [
    "site.json",
    "data/resources.json",
]

# Every page that loads a script which fetches one of the above, directly or
# through app.js / mbm-features.js / mbm-doors.js, plus any page with its own
# inline fetch of a .json.
#
# This list used to be hand-maintained with a comment saying "keep it in step".
# On 2026-08-02 members/index.html stopped loading mbm-features.js and the list
# did not follow, so --check reported drift on a page that no longer needed a
# stamp at all. A list that must be kept in step by hand is a list that will
# eventually be wrong, so it is now derived. FETCHERS is the only thing left to
# maintain, and it changes far less often than the set of pages.
FETCHERS = ("app.js", "mbm-features.js", "mbm-doors.js")


def discover_pages():
    """Every .html that could fetch a DATA file, found rather than remembered."""
    found = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in (".git", "node_modules")]
        for name in sorted(filenames):
            if not name.endswith(".html"):
                continue
            rel = os.path.relpath(os.path.join(dirpath, name), ROOT)
            with open(os.path.join(dirpath, name), encoding="utf-8", errors="replace") as fh:
                html = fh.read()
            hit = any(('src="' + f) in html or ("src='" + f) in html
                      or ('/' + f + '"') in html for f in FETCHERS)
            if not hit:
                # an inline fetch of one of the DATA files counts too
                hit = any(d in html and "fetch(" in html for d in DATA)
            if hit:
                found.append(rel)
    return found


PAGES = discover_pages()

# A derived list can go to zero silently — a broken walk, a moved root, a typo
# in FETCHERS — and "0 pages, 0 stale" would then read as a pass. That is a
# false zero: a gate satisfied by removing its own population. Fail loudly
# instead. The floor is 1 because index.html is the reason this tool exists.
if not PAGES:
    raise SystemExit(
        "stamp-data: discovered 0 pages to stamp. That is a broken scan, not a\n"
        "clean tree — index.html alone should always match. Check ROOT and FETCHERS."
    )

BEGIN = "<!-- DATA-STAMP:BEGIN generated by tools/stamp-data.py, do not edit by hand -->"
END = "<!-- DATA-STAMP:END -->"


def digest(path):
    with open(os.path.join(ROOT, path), "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()[:12]


def block():
    """The generated region, including its delimiters.

    MBM_STAMP returns {url, opts} rather than a string so one call answers both
    questions a fetch has to ask: which url, and — when there is no stamp to put
    on it — what cache mode stands in for one.
    """
    pairs = ",".join('"/%s":"%s"' % (p, digest(p)) for p in DATA)
    js = (
        "window.MBM_DATA_STAMP={%s};"
        "window.MBM_STAMP=function(u){"
        "var D=window.MBM_DATA_STAMP||{},k=String(u==null?\"\":u),"
        "p=k.charAt(0)===\"/\"?k:\"/\"+k.replace(/^\\.\\//,\"\"),h=D[p]||D[k];"
        "return h?{url:k+(k.indexOf(\"?\")<0?\"?\":\"&\")+\"v=\"+h,opts:{}}"
        ":{url:k,opts:{cache:\"no-cache\"}};};"
    ) % pairs
    return BEGIN + "\n<script>" + js + "</script>\n" + END


def splice(html, generated):
    """Replace the region if it is there, insert it before </head> if not."""
    i = html.find(BEGIN)
    if i >= 0:
        j = html.find(END, i)
        if j < 0:
            raise SystemExit("unterminated DATA-STAMP region")
        return html[:i] + generated + html[j + len(END):]
    k = html.find("</head>")
    if k < 0:
        raise SystemExit("no </head> to insert before")
    return html[:k] + generated + "\n" + html[k:]


def main():
    check = "--check" in sys.argv[1:]
    generated = block()
    stale = []
    for page in PAGES:
        path = os.path.join(ROOT, page)
        with open(path, encoding="utf-8") as fh:
            html = fh.read()
        out = splice(html, generated)
        if out == html:
            continue
        stale.append(page)
        if not check:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(out)

    for p in DATA:
        print("  %-24s %s" % (p, digest(p)))
    # Population and failures together: "N pages, M stale", never a bare "0".
    print("%d data files, %d pages, %d %s"
          % (len(DATA), len(PAGES), len(stale), "stale" if check else "rewritten"))
    if stale:
        print("  " + ", ".join(stale))
    if check and stale:
        print("DRIFT: run python3 tools/stamp-data.py and commit the result")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
