#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),http=require('http');
const ROOT=path.resolve(__dirname,'..');
function assert(x,m){if(!x)throw new Error(m)}
(async()=>{let chromium;try{({chromium}=require('playwright'))}catch(e){throw new Error('Playwright missing: '+e.message)}
 const server=http.createServer((req,res)=>{let p=new URL(req.url,'http://127.0.0.1').pathname;let f=path.join(ROOT,p);if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!f.startsWith(ROOT)||!fs.existsSync(f)){res.writeHead(404);return res.end('not found')}res.writeHead(200,{'content-type':f.endsWith('.html')?'text/html; charset=utf-8':'text/plain','cache-control':'no-store'});fs.createReadStream(f).pipe(res)});await new Promise((ok,no)=>{server.once('error',no);server.listen(0,'127.0.0.1',ok)});const url=`http://127.0.0.1:${server.address().port}/apextennis/`;let browser;const rows=[];
 try{browser=await chromium.launch({headless:true});for(const vp of [{w:360,h:640},{w:390,h:844},{w:768,h:900}]){const context=await browser.newContext({viewport:{width:vp.w,height:vp.h}}),page=await context.newPage(),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{const u=new URL(r.url());if(u.hostname!=='127.0.0.1')external.push(r.url())});const r=await page.goto(url,{waitUntil:'load'});assert(r&&r.status()===200,`${vp.w}: load`);await page.evaluate(()=>document.getElementById('mbmSplash')?.remove());await page.click('#tour');assert(await page.locator('.plan-card').count()===3,`${vp.w}: plan cards`);await page.locator('.plan-card').first().click();await page.waitForSelector('#hud:not(.hidden)');const sizes=await page.locator('button:visible').evaluateAll(bs=>bs.map(b=>({id:b.id||b.textContent.trim(),w:b.getBoundingClientRect().width,h:b.getBoundingClientRect().height})));assert(sizes.every(s=>s.w>=44&&s.h>=44),`${vp.w}: target under 44 ${JSON.stringify(sizes.filter(s=>s.w<44||s.h<44))}`);const clauses=await page.locator('#clauseList .clause').count();assert(clauses===3,`${vp.w}: clauses ${clauses}`);const box=await page.locator('#court').boundingBox();await page.mouse.click(box.x+box.width/2,box.y+box.height*.45);const aim=await page.evaluate(()=>window.__AT_DEBUG.state().aimX);assert(Math.abs(aim)<18,`${vp.w}: pointer mapping ${aim}`);assert(errors.length===0,`${vp.w}: page errors ${errors}`);assert(external.length===0,`${vp.w}: external ${external}`);const overflow=await page.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth,sh:document.documentElement.scrollHeight,ch:document.documentElement.clientHeight}));assert(overflow.sw<=overflow.cw+1&&overflow.sh<=overflow.ch+1,`${vp.w}: overflow ${JSON.stringify(overflow)}`);rows.push(`${vp.w}×${vp.h}: ${sizes.length} targets, 3 clauses, pointer ${aim.toFixed(1)}`);await context.close()}
 const nojs=await browser.newContext({viewport:{width:360,height:640},javaScriptEnabled:false,reducedMotion:'reduce'}),p=await nojs.newPage();await p.goto(url,{waitUntil:'load'});const text=await p.textContent('body');assert(/Apex Tennis needs JavaScript/.test(text),'no-JS message absent');const splash=await p.locator('#mbmSplash').evaluate(e=>getComputedStyle(e).display);assert(splash==='none','no-JS splash visible');await nojs.close();
 const pc=await browser.newContext({viewport:{width:1280,height:800}}),pp=await pc.newPage();await pp.goto(url);await pp.evaluate(()=>document.getElementById('mbmSplash')?.remove());await pp.click('#practice');await pp.locator('.plan-card').first().click();const perf=await pp.evaluate(async()=>{const gaps=[];let prev=performance.now();for(let i=0;i<3600;i++)await new Promise(ok=>requestAnimationFrame(t=>{gaps.push(t-prev);prev=t;ok()}));const sorted=gaps.slice().sort((a,b)=>a-b);return{frames:gaps.length,max:Math.max(...gaps),over32:gaps.filter(x=>x>32).length,over50:gaps.filter(x=>x>50).length,over120:gaps.filter(x=>x>120).length,p95:sorted[Math.floor(sorted.length*.95)],avg:gaps.reduce((a,b)=>a+b,0)/gaps.length}});const cadenceOk=p=>p.frames===3600&&p.over32/p.frames<=.02&&p.over50<=3&&p.over120<=1&&p.p95<25&&p.max<250;assert(cadenceOk(perf),`sustained cadence failed: ${JSON.stringify(perf)}`);assert(!cadenceOk({...perf,over32:400,over50:400,over120:20,p95:80,max:300}),'cadence negative control inert');await pc.close();console.log('PASS B1 rendered mobile/a11y/network — '+rows.join(' | '));console.log(`PASS B2 60-second frame run — ${perf.frames} frames, avg ${perf.avg.toFixed(2)}ms, p95 ${perf.p95.toFixed(2)}ms, max ${perf.max.toFixed(2)}ms, over32 ${perf.over32}, over50 ${perf.over50}, over120 ${perf.over120}; overload control rejected`);console.log('ALL APEX TENNIS BROWSER GATES PASSED')
 }finally{if(browser)await browser.close();await new Promise(ok=>server.close(ok))}
})().catch(e=>{console.error('FAIL browser — '+(e.stack||e));process.exit(1)});
