#!/usr/bin/env node
/* The inline exit control, judged in a browser.
 *
 * WHAT THIS IS FOR
 * Eleven declared single-file games carry a stamped inline exit region instead
 * of <script src="/hud.js">, because their own verifiers forbid the external
 * script. This gate proves the control a child actually gets: present in the
 * DOM, at least 44 px as RENDERED, resolving a real href, reachable by
 * keyboard, and on top where a finger lands.
 *
 * WHY IT IS NOT A TEXT SEARCH
 * R-HUC01: a text search over source is evidence about the text, never about
 * the runtime. Trekkers_Trail_Runner (2).html contains the line that sets its
 * exit href and still renders "#" in a browser, because the function that sets
 * it never runs. /neonbreach/ loaded hud.js for months and rendered no control
 * at all. Both would pass a grep.
 *
 * IT SERVES ITSELF
 * The splash gate and verify_games_offline_runtime both derived targets from
 * the filesystem, then fetched them over HTTP from a port they never started
 * and never checked - so they measured whatever happened to be listening, and
 * three different failure counts were read as flakiness. This one starts its
 * own server, asserts the port is listening before judging anything, and
 * assembles BOTH estates onto one origin: the Lessons games' exit resolves to
 * /games/ on the site origin, so a single-origin assembly is the only place
 * that link can be judged at all.
 *
 * EVERY JUDGEMENT HAS A DEADLINE
 * A hang is worse than a failure, because a failure names the file. One run
 * hung 17 minutes on target 9 of 10 and produced nothing.
 *
 * EXITS
 *   0  every judgement passed
 *   1  at least one finding
 *   3  INCONCLUSIVE - the gate could not put itself in a position to judge
 *      (no browser, no port, an estate missing). Declared, not a stack trace.
 *
 * Usage:
 *   node tools/verify_inline_exit.mjs [--lessons /path/to/Lessons]
 */
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const argv = process.argv.slice(2);
const lessonsArg = argv.includes('--lessons') ? argv[argv.indexOf('--lessons') + 1] : null;
const LESSONS = lessonsArg || process.env.MBM_LESSONS_ROOT ||
  ['/home/user/Lessons', path.join(ROOT, '..', 'Lessons')].find(p => fs.existsSync(p));

const VIEWPORTS = [[390, 844, '390'], [768, 1024, '768'], [1440, 900, '1440']];
const FLOOR = 44;                 // the estate's touch-target floor, in px
const KEY = 'mbm_audience_view';
const CHOICE = 'teachers';        // not a route any game would navigate to by itself
const CHOICE_ROUTE = '/for/teachers/';
const NAV_MS = 30000;             // per-page deadline
const SETTLE_MS = 700;

const BEGIN = '<!-- MBM-INLINE-EXIT:BEGIN generated by tools/render_inline_exit.py, do not edit by hand -->';
const END = '<!-- MBM-INLINE-EXIT:END -->';
const REGION_RE = new RegExp(
  BEGIN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' +
  END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));

let pass = 0;
const findings = [];
function check(ok, label, detail = '') {
  if (ok) { pass += 1; console.log(`  [PASS] ${label}${detail ? ' · ' + detail : ''}`); }
  else { findings.push(`${label}${detail ? ' · ' + detail : ''}`); console.error(`  [FAIL] ${label}${detail ? ' · ' + detail : ''}`); }
  return ok;
}
function inconclusive(why) {
  console.error(`\nINCONCLUSIVE: ${why}`);
  console.error('This gate did not judge anything. That is not a pass.');
  process.exit(3);
}

/* ---- targets: derived from each estate's own ledger, never a filename list ---- */
function targets() {
  const out = [];
  const add = (root, prefix) => {
    const f = path.join(root, 'data', 'hud-coverage.json');
    if (!fs.existsSync(f)) return false;
    for (const e of JSON.parse(fs.readFileSync(f, 'utf8')).excluded) {
      const route = e.route;
      const rel = route.endsWith('.html')
        ? (route.startsWith('/Lessons/') ? route.slice('/Lessons/'.length) : route.replace(/^\//, ''))
        : route.replace(/^\/|\/$/g, '') + '/index.html';
      out.push({ route, file: path.join(root, rel), estate: prefix });
    }
    return true;
  };
  if (!add(ROOT, 'site')) inconclusive('the site repository has no data/hud-coverage.json');
  if (!LESSONS || !add(LESSONS, 'lessons')) {
    inconclusive('the Lessons checkout was not found. Three of the eleven live there; ' +
      'judging eight and reporting a green would be a coverage figure that quietly ' +
      'means "the ones it could reach". Pass --lessons /path/to/Lessons.');
  }
  return out;
}

/* ---- the server, which proves it is listening before anything is judged ---- */
const TYPES = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8',
  '.png': 'image/png', '.jpg': 'image/jpeg', '.webp': 'image/webp', '.svg': 'image/svg+xml',
  '.woff2': 'font/woff2', '.mp3': 'audio/mpeg', '.ico': 'image/x-icon' };

function serveBothEstates() {
  return new Promise((resolve, reject) => {
    const server = http.createServer((req, res) => {
      let url;
      try { url = decodeURIComponent(req.url.split('?')[0]); } catch { url = req.url.split('?')[0]; }
      // /Lessons/... comes from the Lessons checkout; everything else from the site.
      // /__adultoff/<route> serves the same file with data-mbm-adult-features="off"
      // on <html>, the way a page that carries the flag really carries it. Setting
      // it from an init script races the region's own mount(), which runs
      // synchronously at parse time when the region sits at the end of <body>;
      // a control that depends on winning that race proves nothing either way.
      let adultOff = false;
      if (url.startsWith('/__adultoff/')) { adultOff = true; url = url.slice('/__adultoff'.length); }
      let file = url.startsWith('/Lessons/')
        ? path.join(LESSONS, url.slice('/Lessons/'.length))
        : path.join(ROOT, url.replace(/^\//, ''));
      if (adultOff) {
        try {
          const src = fs.readFileSync(fs.statSync(file).isDirectory() ? path.join(file, 'index.html') : file, 'utf8');
          const out = src.replace(/<html\b/i, '<html data-mbm-adult-features="off"');
          res.writeHead(200, { 'Content-Type': TYPES['.html'] }).end(out);
        } catch (e) { res.writeHead(500).end(String(e)); }
        return;
      }
      try {
        if (fs.existsSync(file) && fs.statSync(file).isDirectory()) file = path.join(file, 'index.html');
        if (!fs.existsSync(file)) { res.writeHead(404).end('not found'); return; }
        res.writeHead(200, { 'Content-Type': TYPES[path.extname(file).toLowerCase()] || 'application/octet-stream' });
        fs.createReadStream(file).pipe(res);
      } catch (e) { res.writeHead(500).end(String(e)); }
    });
    server.on('error', reject);
    server.listen(0, '127.0.0.1', () => resolve(server));
  });
}

async function assertListening(origin) {
  // The lesson from the splash gate, in code: never judge against a port you
  // have not proven is yours and is answering.
  const probe = await fetch(origin + '/hud.js', { signal: AbortSignal.timeout(5000) })
    .catch(e => ({ ok: false, status: String(e) }));
  if (!probe.ok) inconclusive(`the gate's own server is not answering on ${origin} (${probe.status})`);
  console.log(`  [PASS] the gate's own server is listening and answering on ${origin}`);
  pass += 1;
}

/* ---- browser-side probes. Real functions: Playwright's Node API evaluates a
 *      string as an EXPRESSION and drops the argument, so the string form is
 *      green by never asserting anything. ---- */
const PROBE = (id) => {
  const e = document.getElementById(id);
  if (!e) return { present: false };
  const b = e.getBoundingClientRect();
  const cs = getComputedStyle(e);
  const mid = document.elementFromPoint(b.x + b.width / 2, b.y + b.height / 2);
  return {
    present: true,
    w: Math.round(b.width * 100) / 100,
    h: Math.round(b.height * 100) / 100,
    href: e.getAttribute('href'),
    resolved: e.href,
    label: e.getAttribute('aria-label'),
    onTop: !mid ? 'NOTHING' : (mid === e || e.contains(mid)) ? 'ON TOP'
      : 'COVERED by ' + mid.tagName.toLowerCase() + (mid.id ? '#' + mid.id : ''),
    display: cs.display,
    visible: cs.visibility !== 'hidden' && cs.display !== 'none' && Number(cs.opacity) > 0,
    tabbable: e.tabIndex >= 0 || e.tagName === 'A',
  };
};

/*
 * A real tab walk, not a proxy for one.
 *
 * Focus is reset to the very start of the document, then Tab is pressed and
 * document.activeElement is followed until every wanted id has been landed on,
 * the order cycles back to where it began, or the press cap is hit. The cap is
 * a FAILURE, never a pass: a control the walk never reaches is not reachable,
 * whatever .focus() would have said about it.
 *
 * Why the walk starts from document.body with a blur rather than from wherever
 * focus happens to be: a page that has already moved focus onto or past the
 * control would make the first Tab land on it by accident, which is the same
 * false positive in a different costume.
 */
const TAB_CAP = 120;
async function tabReach(page, ids) {
  const out = { presses: {} };
  for (const id of ids) { out[id] = false; out.presses[id] = null; }
  await page.evaluate(() => {
    if (document.activeElement && document.activeElement !== document.body) document.activeElement.blur();
    document.body.setAttribute('tabindex', '-1');
    document.body.focus();
    document.body.removeAttribute('tabindex');
  });
  for (let i = 1; i <= TAB_CAP; i++) {
    await page.keyboard.press('Tab');
    // Cycle detection keys on ELEMENT IDENTITY, stamped on the node itself.
    //
    // It first keyed on a descriptor string - tag, id, class, href - and that
    // was wrong in a way that mattered. A page with a run of id-less identical
    // controls (seven .mode-card on /apexpool/, nine .pickCard on
    // /rallyvector3d/, three .chassis-card on /relicforge/) yields the same
    // descriptor on consecutive presses; the walk read that as a cycle and
    // stopped before it ever reached the exit, then reported those three exits
    // unreachable. They are reachable, at presses 14, 27 and 12. The check
    // written to replace a vacuous proxy had a false negative of its own, and
    // only a reproduction showed it.
    //
    // /relicforge/ read 8 here until it was re-measured, and the difference is
    // not a typo worth silently fixing: the number is TOUCH-CAPABILITY
    // dependent, and NOT viewport dependent.
    //
    //     hasTouch: false  ->   8 presses, at 390x844 AND at 1440x900
    //     hasTouch: true   ->  12 presses, at 390x844 AND at 1440x900
    //
    // Viewport does not move the number at all; only touch capability does.
    // Four .touch-button controls - #touch-fire, #touch-utility, #touch-dash,
    // #touch-pause - sit in the DOM either way, but only enter the tab order
    // under touch, where they take presses 8-11:
    //
    //     touch on    chassis x3 · start · how · journal · settings ·
    //                 touch-fire · touch-utility · touch-dash · touch-pause ·
    //                 mbmexit-back
    //     touch off   chassis x3 · start · how · journal · settings ·
    //                 mbmexit-back
    //
    // The rendered leg begins at the header "rendered: the only evidence about
    // rendered geometry" (:326 as this is written), and EVERY browser context
    // opened below it pins hasTouch: true - :336, :391 and :457, which is all
    // three of them. Grep newContext if those numbers have drifted; the claim is
    // that no context in this file omits hasTouch, not that it lives on a line.
    // So 12 is the number this file asserts, and it asserts it identically at
    // 390, 768 and 1440. The 8 belongs to a non-touch context, which this file
    // never creates.
    //
    // /apexpool/ and /rallyvector3d/ measure 14 and 27 with touch on or off,
    // which is why only relicforge's row was ever wrong.
    //
    // The sentence this replaced read "with hasTouch false, and at 1440x900, it
    // is 8", which parses as though 1440x900 produced 8 on its own. It does not.
    // The heading above it was already correct; only the sentence was loose -
    // the third time this week a true claim has sat over a sentence implying a
    // false one. The other two: #141's F1 table kept a stale press count of 8
    // beside a correct 12 in the same body, and the /neonmeridian/ flash census
    // recorded 59.5 fps in a column read as sample quality when it was the
    // sampler idling over a canvas that never rendered. Prose ages while the
    // assertion beside it stays green, and nothing goes red when it does.
    const where = await page.evaluate(() => {
      const a = document.activeElement;
      if (!a || a === document.body) return { id: null, repeat: false };
      const repeat = a.hasAttribute('data-mbm-tabwalk');
      if (!repeat) a.setAttribute('data-mbm-tabwalk', '1');
      return { id: a.id || null, repeat };
    });
    if (where.id && Object.prototype.hasOwnProperty.call(out, where.id) && out[where.id] === false) {
      out[where.id] = true;
      out.presses[where.id] = i;
      if (ids.every(x => out[x] === true)) { await clearWalkMarks(page); return out; }
    }
    // Landed on an element this walk has already visited: the order has cycled
    // and every remaining id is genuinely unreachable.
    if (where.repeat) { await clearWalkMarks(page); return out; }
  }
  await clearWalkMarks(page);
  return out;
}

// The walk must not leave the page different from how it found it: the probe is
// not allowed to become part of what later checks measure.
async function clearWalkMarks(page) {
  await page.evaluate(() => {
    for (const e of document.querySelectorAll('[data-mbm-tabwalk]')) e.removeAttribute('data-mbm-tabwalk');
  });
}

async function main() {
  // ESM import() does not honour NODE_PATH, so a globally installed playwright
  // is invisible to a bare specifier. Resolve it explicitly and say where it
  // was found, rather than reporting "not importable" for a copy that is there.
  let chromium;
  {
    const tried = [];
    for (const spec of ['playwright', process.env.MBM_PLAYWRIGHT,
      '/opt/node22/lib/node_modules/playwright/index.js'].filter(Boolean)) {
      try {
        // A CJS playwright imported from ESM puts its exports on .default when
        // the lexer cannot see them as named. Take whichever actually carries
        // chromium rather than assuming the shape.
        const mod = await import(spec);
        chromium = mod.chromium || (mod.default && mod.default.chromium);
        if (!chromium) { tried.push(`${spec} (no chromium export)`); continue; }
        console.log(`  playwright: ${spec}`);
        break;
      } catch (e) { tried.push(`${spec} (${String(e.code || e).slice(0, 40)})`); }
    }
    if (!chromium) inconclusive(`playwright is not importable, so nothing could be rendered. Tried: ${tried.join('; ')}`);
  }

  const T = targets();
  console.log(`Inline exit control · ${T.length} declared game(s) from two estates' ledgers · ` +
    `${VIEWPORTS.length} viewports · floor ${FLOOR} px\n`);

  /* -------- source-level: one region, byte-identical everywhere -------- */
  const regions = new Map();
  for (const t of T) {
    if (!fs.existsSync(t.file)) { check(false, `${t.route}: the ledger names a file that exists`); continue; }
    const html = fs.readFileSync(t.file, 'utf8');
    const m = html.match(REGION_RE);
    if (!check(!!m, `${t.route}: carries the stamped exit region`)) continue;
    regions.set(t.route, crypto.createHash('sha256').update(m[0]).digest('hex'));
  }
  const distinct = new Set(regions.values());
  check(distinct.size === 1,
    'the stamped region is byte-identical in every file that carries it',
    `${distinct.size} distinct region(s) across ${regions.size} file(s)`);

  /* -------- rendered: the only evidence about rendered geometry -------- */
  const server = await serveBothEstates().catch(e => inconclusive(`could not start a server: ${e}`));
  const { port } = server.address();
  const origin = `http://127.0.0.1:${port}`;
  await assertListening(origin);

  const browser = await chromium.launch().catch(e => inconclusive(`chromium would not launch: ${e}`));

  try {
    for (const [width, height, vp] of VIEWPORTS) {
      const ctx = await browser.newContext({ viewport: { width, height }, hasTouch: true });
      const page = await ctx.newPage();
      for (const t of T) {
        const url = origin + t.route.split('/').map(encodeURIComponent).join('/');
        try {
          await page.goto(url, { waitUntil: 'domcontentloaded', timeout: NAV_MS });
          await page.evaluate(([k, v]) => localStorage.setItem(k, v), [KEY, CHOICE]);
          await page.reload({ waitUntil: 'domcontentloaded', timeout: NAV_MS });
          await page.waitForTimeout(SETTLE_MS);
        } catch (e) {
          check(false, `${vp}px ${t.route}: loads within ${NAV_MS} ms`, String(e).slice(0, 100));
          continue;
        }
        const back = await page.evaluate(PROBE, 'mbmexit-back');
        if (check(back.present, `${vp}px ${t.route}: the exit control renders`)) {
          check(back.w >= FLOOR && back.h >= FLOOR,
            `${vp}px ${t.route}: exit is at least ${FLOOR}x${FLOOR} as rendered`, `${back.w}x${back.h}`);
          check(back.resolved === origin + '/games/',
            `${vp}px ${t.route}: exit resolves a real href`, back.resolved);
          check(back.onTop === 'ON TOP', `${vp}px ${t.route}: exit is on top where a finger lands`, back.onTop);
          check(back.visible, `${vp}px ${t.route}: exit is visible`);
          check(!!back.label, `${vp}px ${t.route}: exit has an accessible name`, back.label || '(none)');
        }
        const home = await page.evaluate(PROBE, 'mbmexit-home');
        if (check(home.present, `${vp}px ${t.route}: the chosen-homepage control renders when one is stored`)) {
          check(home.w >= FLOOR && home.h >= FLOOR,
            `${vp}px ${t.route}: homepage control is at least ${FLOOR}x${FLOOR}`, `${home.w}x${home.h}`);
          check(home.resolved === origin + CHOICE_ROUTE,
            `${vp}px ${t.route}: homepage control resolves the stored choice`, home.resolved);
          check(home.onTop === 'ON TOP', `${vp}px ${t.route}: homepage control is on top`, home.onTop);
        }
        // Keyboard: both controls must be reachable by Tab from the document
        // start. This says what it does now. It used to say exactly this
        // sentence while the code below it called e.focus() and compared
        // document.activeElement - which is a different and much weaker claim,
        // because .focus() succeeds on elements Tab can never reach:
        // tabindex="-1", elements removed from the tab order, elements present
        // but not tabbable. A child on a locked-down device using only a
        // keyboard is exactly who this control exists for, so the proxy was
        // guarding the case it could not see. The negative control below proves
        // the difference: a tabindex="-1" clone passes the old check and fails
        // this one.
        const reach = await tabReach(page, ['mbmexit-back', 'mbmexit-home']);
        check(reach['mbmexit-back'] === true,
          `${vp}px ${t.route}: exit is reachable by Tab`, `presses: ${reach.presses['mbmexit-back']}`);
        if (home.present) check(reach['mbmexit-home'] === true,
          `${vp}px ${t.route}: homepage control is reachable by Tab`, `presses: ${reach.presses['mbmexit-home']}`);
      }
      await ctx.close();
    }

    /* -------- controls: the gate must be able to go red -------- */
    console.log('\n  --- controls (each must report a problem) ---');
    /* The sample must be a file that ACTUALLY CARRIES the region, not merely
       the first declared target.

       This was `T[0]`, and it produced two failures of its own the moment the
       first declared game legitimately lost its region — which is exactly the
       state this gate exists to detect:
         · control 1 removed a region that was already absent and then PASSED,
           proving that removing nothing removes nothing. Vacuous.
         · control 2 hashed `...match(REGION_RE)[0]` on a file with no region,
           threw a TypeError, and took the whole run to INCONCLUSIVE — masking
           ten genuine FAILs the gate had already correctly reported.
       So the gate could not report the very defect it had found. Found by
       tools/verify_inline_exit_control.sh, which breaks a real declared game. */
    const sample = T.find(t => REGION_RE.test(fs.readFileSync(t.file, 'utf8')));
    if (!sample) {
      inconclusive('no declared game still carries the stamped exit region, so the controls below ' +
        'have nothing to exercise. The findings above stand; the controls did not run.');
    }
    const clean = fs.readFileSync(sample.file, 'utf8');
    check(REGION_RE.test(clean),
      `control precondition: the sample ${sample.route} carries a region to remove`);
    const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true });
    const page = await ctx.newPage();
    const url = origin + sample.route.split('/').map(encodeURIComponent).join('/');

    // 1. region removed -> the control is absent
    fs.writeFileSync(sample.file, clean.replace(REGION_RE, ''));
    await page.goto(url, { waitUntil: 'domcontentloaded', timeout: NAV_MS });
    await page.waitForTimeout(SETTLE_MS);
    const gone = await page.evaluate(PROBE, 'mbmexit-back');
    check(!gone.present, 'control: removing the region removes the control (the gate can go red)');

    // 2. region mutated -> byte-equality reports it
    const mutated = clean.replace('Back to the Arcade', 'Back to the Arcadex');
    fs.writeFileSync(sample.file, mutated);
    const mMatch = fs.readFileSync(sample.file, 'utf8').match(REGION_RE);
    if (!mMatch) {
      // Guarded rather than indexed. `[0]` on a null match threw a TypeError and
      // ended the run INCONCLUSIVE, which reported nothing about the mutation
      // and buried every real finding above it. A control that cannot run is a
      // FAIL that names itself, not a crash.
      check(false, 'control: mutating one copy breaks byte-equality (the mutated sample lost its region entirely)');
    } else {
      const mSha = crypto.createHash('sha256').update(mMatch[0]).digest('hex');
      check(mSha !== [...distinct][0], 'control: mutating one copy breaks byte-equality');
    }

    fs.writeFileSync(sample.file, clean);

    // 3. no stored preference -> the homepage control correctly does not render,
    //    and the exit control is untouched
    await page.goto(url, { waitUntil: 'domcontentloaded', timeout: NAV_MS });
    await page.evaluate(k => localStorage.removeItem(k), KEY);
    await page.reload({ waitUntil: 'domcontentloaded', timeout: NAV_MS });
    await page.waitForTimeout(SETTLE_MS);
    const noPref = await page.evaluate(PROBE, 'mbmexit-home');
    const stillBack = await page.evaluate(PROBE, 'mbmexit-back');
    check(!noPref.present, 'control: with no stored homepage the second control does not render at all');
    check(stillBack.present, 'control: with no stored homepage the exit control is still there');

    /* 4. THE PROXY CONTROL — the whole reason the keyboard check changed.
     *
     * An element that .focus() reaches and Tab cannot: an anchor with
     * tabindex="-1". The old check called e.focus() and compared
     * document.activeElement, so it passed on exactly this element. The tab
     * walk cannot reach it, so it fails. BOTH outcomes are asserted here — a
     * control that only showed the new check failing would not prove the old
     * one was ever wrong. */
    await page.goto(url, { waitUntil: 'domcontentloaded', timeout: NAV_MS });
    await page.waitForTimeout(SETTLE_MS);
    const proxyProbe = await page.evaluate(() => {
      const a = document.createElement('a');
      a.id = 'mbmexit-proxytest';
      a.href = '/games/';
      a.textContent = 'unreachable';
      a.setAttribute('tabindex', '-1');
      document.body.appendChild(a);
      // The OLD check, verbatim, on this element.
      a.focus();
      return { oldCheckSays: document.activeElement === a };
    });
    const proxyWalk = await tabReach(page, ['mbmexit-proxytest']);
    check(proxyProbe.oldCheckSays === true,
      'control: a tabindex="-1" anchor PASSES the old .focus()/activeElement check — the proxy was vacuous');
    check(proxyWalk['mbmexit-proxytest'] === false,
      'control: the same anchor FAILS the tab walk — the new check is not a proxy',
      `presses to reach: ${proxyWalk.presses['mbmexit-proxytest']}`);
    await page.evaluate(() => document.getElementById('mbmexit-proxytest')?.remove());

    await ctx.close();

    // 4. On a page carrying adult-features="off", a stored 'main' must NOT
    //    resolve the brand to /main/. Positive limb first, so the negative one
    //    is not passing because the control never rendered either way.
    for (const [flag, expectHome] of [[null, true], ['off', false]]) {
      const c = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true });
      await c.addInitScript(k => { try { localStorage.setItem(k, 'main'); } catch (e) {} }, KEY);
      const p = await c.newPage();
      const target = flag
        ? origin + '/__adultoff' + sample.route.split('/').map(encodeURIComponent).join('/')
        : url;
      await p.goto(target, { waitUntil: 'domcontentloaded', timeout: NAV_MS });
      await p.waitForTimeout(SETTLE_MS);
      const h = await p.evaluate(PROBE, 'mbmexit-home');
      if (expectHome) {
        check(h.present && h.resolved === origin + '/main/',
          'control: with adult features allowed, a stored "main" does resolve to /main/', h.resolved || 'absent');
      } else {
        check(!h.present,
          'control: on a page carrying adult-features="off" the brand never resolves to /main/',
          h.present ? h.resolved : 'control correctly absent');
      }
      await c.close();
    }
  } finally {
    await browser.close().catch(() => {});
    server.close();
  }

  console.log(`\n${pass} passed · ${findings.length} failed`);
  if (findings.length) {
    console.error('\nFindings:');
    findings.forEach(f => console.error('  · ' + f));
    process.exit(1);
  }
  process.exit(0);
}

main().catch(e => inconclusive(`the gate threw before it could judge: ${e && e.stack || e}`));
