#!/usr/bin/env node

/* Runtime contract for the generated Made by Matt splash.
 *
 * Presence is POLLED from document start; a single sample can miss a splash
 * that closes itself. Membership comes from render_splash.py, and generator
 * byte identity remains the renderer's --check responsibility.
 */
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const renderer = fs.readFileSync(path.join(ROOT, 'tools/render_splash.py'), 'utf8');
const targetLiteral = (renderer.match(/^TARGETS\s*=\s*(\[[^\n]+\])/m) || [])[1];
if (!targetLiteral) throw new Error('render_splash.py TARGETS was not found');
const TARGETS = JSON.parse(targetLiteral);
if (!TARGETS.length) throw new Error('refusing to verify an empty splash target set');

const BEGIN = '<!-- MBM-SPLASH:BEGIN generated by tools/render_splash.py, do not edit by hand -->';
const END = '<!-- MBM-SPLASH:END -->';
const regionPattern = new RegExp(
  BEGIN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' +
  END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\n?');
const MIME = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.svg': 'image/svg+xml', '.webp': 'image/webp' };

let pass = 0;
const failures = [];
function check(ok, label, detail = '') {
  if (ok) { pass += 1; console.log(`  [PASS] ${label}${detail ? ` · ${detail}` : ''}`); }
  else { failures.push(`${label}${detail ? ` · ${detail}` : ''}`); console.error(`  [FAIL] ${label}${detail ? ` · ${detail}` : ''}`); }
}

function server() {
  return new Promise((resolve, reject) => {
    const instance = http.createServer((req, res) => {
      let pathname = decodeURIComponent((req.url || '/').split('?')[0]);
      const control = pathname.startsWith('/__no_splash__/');
      if (control) pathname = pathname.slice('/__no_splash__'.length);
      let file = path.join(ROOT, pathname.replace(/^\//, ''));
      if (fs.existsSync(file) && fs.statSync(file).isDirectory()) file = path.join(file, 'index.html');
      if (!fs.existsSync(file)) { res.writeHead(404).end('not found'); return; }
      if (control) {
        const source = fs.readFileSync(file, 'utf8').replace(regionPattern, '');
        res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' }).end(source);
        return;
      }
      res.writeHead(200, { 'Content-Type': MIME[path.extname(file)] || 'application/octet-stream', 'Cache-Control': 'no-store' });
      fs.createReadStream(file).pipe(res);
    });
    instance.once('error', reject);
    instance.listen(0, '127.0.0.1', () => resolve(instance));
  });
}

async function chromiumApi() {
  const require = createRequire(import.meta.url);
  try {
    const mod = require('playwright');
    if (mod.chromium) return mod.chromium;
  } catch { /* fall through to portable ESM locations */ }
  for (const spec of ['playwright', process.env.MBM_PLAYWRIGHT, '/opt/node22/lib/node_modules/playwright/index.js'].filter(Boolean)) {
    try {
      const mod = await import(spec);
      const chromium = mod.chromium || mod.default?.chromium;
      if (chromium) return chromium;
    } catch { /* next */ }
  }
  throw new Error('Playwright is not importable; install playwright before running this browser gate');
}

const initProbe = () => {
  window.__mbmSplashProbe = { samples: 0, seen: false, visible: false, maxW: 0, maxH: 0, skipW: 0, skipH: 0 };
  const sample = () => {
    const out = window.__mbmSplashProbe;
    out.samples += 1;
    const splash = document.querySelector('.mbm-splash');
    if (!splash) return;
    out.seen = true;
    const box = splash.getBoundingClientRect();
    const css = getComputedStyle(splash);
    if (box.width > 0 && box.height > 0 && css.display !== 'none' && css.visibility !== 'hidden') out.visible = true;
    out.maxW = Math.max(out.maxW, box.width);
    out.maxH = Math.max(out.maxH, box.height);
    const skip = splash.querySelector('.mbm-skip,button');
    if (skip) {
      const b = skip.getBoundingClientRect();
      out.skipW = Math.max(out.skipW, b.width);
      out.skipH = Math.max(out.skipH, b.height);
    }
  };
  window.__mbmSplashTimer = setInterval(sample, 50);
  document.addEventListener('DOMContentLoaded', sample, { once: true });
};

async function observe(browser, origin, slug, reduced, control = false) {
  const context = await browser.newContext({
    viewport: { width: 390, height: 844 },
    hasTouch: true,
    isMobile: true,
    reducedMotion: reduced ? 'reduce' : 'no-preference',
  });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('requestfailed', request => errors.push(`${request.method()} ${request.url()}: ${request.failure()?.errorText || 'failed'}`));
  await page.addInitScript(initProbe);
  await page.goto(`${origin}${control ? '/__no_splash__' : ''}/${slug}/`, { waitUntil: 'domcontentloaded', timeout: 30000 });
  if (control) {
    await page.waitForTimeout(700);
  } else {
    await page.waitForFunction(() => window.__mbmSplashProbe?.seen === true, null, { timeout: 4500 });
    await page.waitForFunction(() => window.__mbmSplashProbe?.seen && !document.querySelector('.mbm-splash'), null, { timeout: 7000 });
  }
  const result = await page.evaluate(() => {
    clearInterval(window.__mbmSplashTimer);
    return { ...window.__mbmSplashProbe, stillOpen: !!document.querySelector('.mbm-splash') };
  });
  await context.close();
  return { ...result, errors };
}

const instance = await server();
const address = instance.address();
const origin = `http://127.0.0.1:${address.port}`;
let browser;
try {
  const chromium = await chromiumApi();
  const executablePath = chromium.executablePath();
  browser = await chromium.launch({
    headless: true,
    ...(executablePath && fs.existsSync(executablePath) ? { executablePath } : {}),
  });
  console.log(`\n=== GENERATED SPLASH · ${TARGETS.length} TARGETS × 2 MOTION STATES ===\n`);
  for (const slug of TARGETS) {
    for (const reduced of [false, true]) {
      const result = await observe(browser, origin, slug, reduced);
      const label = `/${slug}/ rm=${reduced ? 'reduce' : 'full'}`;
      check(result.seen && result.visible, `${label}: splash observed by polling`, `${result.samples} samples, ${Math.round(result.maxW)}×${Math.round(result.maxH)}`);
      check(!result.stillOpen, `${label}: splash completes and clears`);
      check(result.skipW >= 44 && result.skipH >= 44, `${label}: skip target is at least 44px`, `${Math.round(result.skipW)}×${Math.round(result.skipH)}`);
      check(result.errors.length === 0, `${label}: no runtime/request errors`, result.errors.slice(0, 2).join(' | '));
    }
  }

  const control = await observe(browser, origin, TARGETS[0], false, true);
  check(control.seen === false && control.visible === false,
    'CONTROL: removing one generated region makes the presence predicate red',
    `${control.samples} polls, seen=${control.seen}`);
} finally {
  if (browser) await browser.close();
  await new Promise(resolve => instance.close(resolve));
}

console.log(`\nsplash runtime: ${pass}/${pass + failures.length} passed`);
if (failures.length) {
  console.error(`${failures.length} FAILED`);
  process.exit(1);
}
