#!/usr/bin/env node
/* Real-origin browser evidence for the generated Made by Matt splash.
 *
 * Modes:
 *   --mode=controls  SS1–SS8 plus the four dismissal paths and a removal control
 *   --mode=census    classify the canonical inventory before application
 *   --mode=verify    judge every applied route after application
 *
 * The runner is intentionally serial.  Every route gets a fresh browser
 * context (RL14), and both viewports are measured rather than inferred.
 */
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const HERE = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_SITE = path.resolve(HERE, '..');
const arg = name => {
  const hit = process.argv.find(v => v.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : null;
};
const MODE = arg('mode') || 'controls';
const SITE = path.resolve(arg('site-root') || DEFAULT_SITE);
const LESSONS = path.resolve(arg('lessons-root') || path.join(SITE, '_lessons'));
const REPORT = path.resolve(arg('report') || path.join(SITE, 'artifacts', `maker-splash-${MODE}.json`));
const KEY = 'mbm_splash_last';
const BEGIN = '<!-- MBM-MAKER-SPLASH:BEGIN generated by tools/render_maker_splash.py, do not edit by hand -->';
const END = '<!-- MBM-MAKER-SPLASH:END -->';
const REGION = new RegExp('(?:\\r?\\n)?' + escapeRegex(BEGIN) + '[\\s\\S]*?' + escapeRegex(END) + '(?:\\r?\\n)?');
const VIEWPORTS = [{ width: 390, height: 844 }, { width: 1280, height: 800 }];
const MIME = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.mjs': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8', '.svg': 'image/svg+xml', '.png': 'image/png', '.webp': 'image/webp', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.gif': 'image/gif', '.ico': 'image/x-icon', '.woff2': 'font/woff2', '.mp4': 'video/mp4', '.webm': 'video/webm' };

function escapeRegex(value) { return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
function readJson(file) { return JSON.parse(fs.readFileSync(file, 'utf8')); }
function routeFile(route) {
  const lessons = route.startsWith('/Lessons/');
  const root = lessons ? LESSONS : SITE;
  let rel = lessons ? route.slice('/Lessons/'.length) : route.replace(/^\//, '');
  let file = path.resolve(root, rel);
  if (route.endsWith('/')) file = path.join(file, 'index.html');
  if (file !== root && !file.startsWith(root + path.sep)) return null;
  return fs.existsSync(file) && fs.statSync(file).isFile() ? file : null;
}
function routeRepo(route) { return route.startsWith('/Lessons/') ? 'Lessons' : 'Site'; }
function routeGroup(entry) {
  if (entry.category === 'game') return entry.route.startsWith('/Lessons/') ? 'Lessons games' : 'root-level games';
  if (entry.category === 'lesson') return 'lessons';
  if (['resource', 'tool', 'app'].includes(entry.category)) return 'resources/tools/apps';
  return 'other interactive inventory';
}
function insertEvidence(file) {
  if (!file || path.extname(file).toLowerCase() !== '.html') return null;
  const source = fs.readFileSync(file, 'utf8');
  const m = source.match(/<body\b[^>]*>/i);
  return m ? `after <body> byte ${Buffer.byteLength(source.slice(0, m.index + m[0].length))}` : 'UNMEASURED: no <body>';
}
function applied(root) {
  const data = readJson(path.join(root, 'data', 'hud-coverage.json'));
  const list = data.makerSplash?.applied;
  if (!Array.isArray(list) || !list.length) throw new Error(`${root}: makerSplash.applied is missing or empty`);
  return list.map(item => typeof item === 'string' ? item : item.route);
}

function makeServer({ stripRoute = null } = {}) {
  const server = http.createServer((req, res) => {
    let pathname;
    try { pathname = decodeURIComponent(new URL(req.url, 'http://127.0.0.1').pathname); }
    catch { res.writeHead(400); return res.end('bad path'); }
    let file = routeFile(pathname);
    if (!file) {
      const root = pathname.startsWith('/Lessons/') ? LESSONS : SITE;
      const rel = pathname.startsWith('/Lessons/') ? pathname.slice(9) : pathname.slice(1);
      file = path.resolve(root, rel);
      if (file !== root && !file.startsWith(root + path.sep)) file = null;
      if (file && fs.existsSync(file) && fs.statSync(file).isDirectory()) file = path.join(file, 'index.html');
      if (!file || !fs.existsSync(file) || !fs.statSync(file).isFile()) file = null;
    }
    if (!file) { res.writeHead(404); return res.end('not found'); }
    const type = MIME[path.extname(file).toLowerCase()] || 'application/octet-stream';
    if (type.startsWith('text/html') && stripRoute === pathname) {
      const body = fs.readFileSync(file, 'utf8').replace(REGION, '');
      res.writeHead(200, { 'content-type': type, 'cache-control': 'no-store' });
      return res.end(body);
    }
    res.writeHead(200, { 'content-type': type, 'cache-control': 'no-store' });
    fs.createReadStream(file).pipe(res);
  });
  return new Promise((resolve, reject) => {
    server.once('error', reject);
    server.listen(0, '127.0.0.1', () => resolve(server));
  });
}

async function newContext(browser, options = {}) {
  const context = await browser.newContext({ viewport: options.viewport || VIEWPORTS[0], reducedMotion: options.reduced ? 'reduce' : 'no-preference', serviceWorkers: 'block' });
  if (options.seed !== undefined) await context.addInitScript(({ key, value }) => { try { localStorage.setItem(key, value); } catch {} }, { key: KEY, value: String(options.seed) });
  if (options.throwWrite) await context.addInitScript(key => {
    const original = Storage.prototype.setItem;
    Storage.prototype.setItem = function (k, v) {
      if (this === localStorage && k === key) throw new DOMException('blocked', 'QuotaExceededError');
      return original.call(this, k, v);
    };
  }, KEY);
  return context;
}

async function pageProbe(context, origin, route, { action = 'none', waitAbsent = 650 } = {}) {
  const page = await context.newPage();
  const errors = [], external = [];
  page.on('pageerror', error => errors.push(`pageerror: ${error.message}`));
  page.on('console', msg => { if (msg.type() === 'error') errors.push(`console: ${msg.text()}`); });
  page.on('request', request => {
    const url = request.url();
    if (!url.startsWith(origin) && !url.startsWith('data:') && !url.startsWith('blob:')) external.push(url);
  });
  await page.addInitScript(() => {
    window.__makerProbe = { seen: false, first: null, last: null, focus: null, geometry: null };
    addEventListener('focusin', event => {
      const p = window.__makerProbe;
      if (!p.focus && event.target && !event.target.closest?.('[data-mbm-maker-splash]')) p.focus = { t: performance.now(), id: event.target.id || '', tag: event.target.tagName || '' };
    });
    function sample() {
      const p = window.__makerProbe;
      const el = document.querySelector('[data-mbm-maker-splash],#mbmSplash,.mbm-splash,[data-mbm-splash]');
      if (el) {
        const rect = el.getBoundingClientRect(), css = getComputedStyle(el);
        const label = `${el.getAttribute('aria-label') || ''} ${el.textContent || ''}`;
        if (/made\s+by\s+matt/i.test(label) && rect.width > 0 && rect.height > 0 && css.display !== 'none' && css.visibility !== 'hidden') {
          p.seen = true; if (p.first === null) p.first = performance.now(); p.last = performance.now();
          p.geometry = { width: rect.width, height: rect.height, role: el.getAttribute('role'), modal: el.getAttribute('aria-modal'), z: css.zIndex };
        }
      }
      requestAnimationFrame(sample);
    }
    requestAnimationFrame(sample);
  });
  const wall = Date.now();
  let response = null;
  try { response = await page.goto(origin + encodeURI(route), { waitUntil: 'domcontentloaded', timeout: 30000 }); }
  catch (error) { errors.push(`navigation: ${error.message}`); }
  const maker = page.locator('[data-mbm-maker-splash]');
  const appeared = await maker.waitFor({ state: 'attached', timeout: waitAbsent }).then(() => true).catch(() => false);
  if (appeared) {
    await page.waitForTimeout(20);
    if (action === 'key') await page.keyboard.press('a');
    else if (action === 'pointer') await maker.click({ position: { x: 20, y: 20 } });
    else if (action === 'timeout') await maker.evaluate(el => { el.style.animation = 'none'; });
    if (action !== 'none') await maker.waitFor({ state: 'detached', timeout: 2800 }).catch(() => {});
  }
  const state = await page.evaluate(key => {
    const p = window.__makerProbe || {};
    const legacy = document.querySelector('#mbmSplash,.mbm-splash,[data-mbm-splash]');
    const primary = document.querySelector('#startBtn,#playBtn,#beginBtn,#launchBtn,#openBtn,#start,a.skip,main button:not([disabled]),button:not([disabled]),main a[href],a[href]');
    const rect = primary?.getBoundingClientRect();
    let local = null, session = null, keys = [];
    try { local = localStorage.getItem(key); keys = Object.keys(localStorage); } catch {}
    try { session = sessionStorage.getItem(key); } catch {}
    return {
      probe: p,
      makerPresent: !!document.querySelector('[data-mbm-maker-splash]'),
      anySplashPresent: !!legacy,
      legacyLabel: legacy ? `${legacy.getAttribute('aria-label') || ''} ${legacy.textContent || ''}`.trim().slice(0, 100) : '',
      local, session, keys,
      active: { id: document.activeElement?.id || '', tag: document.activeElement?.tagName || '' },
      primaryRect: rect ? { x: rect.x, y: rect.y, width: rect.width, height: rect.height, id: primary.id || '', tag: primary.tagName } : null,
      overflow: document.documentElement.scrollWidth - document.documentElement.clientWidth,
      ready: document.readyState,
    };
  }, KEY).catch(error => ({ probe: {}, error: error.message }));
  const result = { ...state, appeared, wall, status: response?.status() ?? null, finalUrl: page.url(), errors, external };
  await page.close();
  return result;
}

async function wayOutProbe(browser, origin, route, activation) {
  const context = await newContext(browser);
  const page = await context.newPage();
  const errors = [], external = [];
  page.on('pageerror', error => errors.push(`pageerror: ${error.message}`));
  page.on('console', msg => { if (msg.type() === 'error') errors.push(`console: ${msg.text()}`); });
  page.on('request', request => {
    const url = request.url();
    if (!url.startsWith(origin) && !url.startsWith('data:') && !url.startsWith('blob:')) external.push(url);
  });
  await page.goto(origin + encodeURI(`${route}?splash=force`), { waitUntil: 'domcontentloaded', timeout: 30000 });
  const maker = page.locator('[data-mbm-maker-splash]');
  await maker.waitFor({ state: 'attached', timeout: 1000 });
  await page.keyboard.press('Tab');
  await maker.waitFor({ state: 'detached', timeout: 2800 });
  let tabs = 0;
  for (; tabs <= 30; tabs += 1) {
    if (await page.evaluate(() => document.activeElement?.id === 'mbmexit-back')) break;
    await page.keyboard.press('Tab');
  }
  const reached = tabs <= 30 && await page.evaluate(() => document.activeElement?.id === 'mbmexit-back');
  const before = page.url();
  if (reached) await page.keyboard.press(activation);
  await page.waitForTimeout(300);
  const after = page.url();
  await context.close();
  return { activation, tabs, reached, before, after, navigated: after !== before, errors, external };
}

async function census(browser, origin) {
  const index = readJson(path.join(SITE, 'data', 'mbm-search-index.json'));
  const entries = index.entries || [];
  const rows = [];
  for (let i = 0; i < entries.length; i += 1) {
    const entry = entries[i], file = routeFile(entry.route), ext = file ? path.extname(file).toLowerCase() : path.extname(entry.route).toLowerCase();
    const base = { route: entry.route, repository: routeRepo(entry.route), group: routeGroup(entry), category: entry.category, fileBytes: file ? fs.statSync(file).size : null, insertionPoint: file && ext === '.html' ? insertEvidence(file) : null };
    if (!file) {
      rows.push({ ...base, class: 'UNMEASURED', evidence: entry.route.startsWith('/Matt-s-Apps-/') ? 'route belongs to the out-of-scope Apps repository' : 'inventory route has no file in the three authorised repositories' });
      continue;
    }
    if (ext !== '.html') {
      rows.push({ ...base, class: 'SPLASH DECLINED', evidence: `${ext || 'non-HTML'} contract cannot host an HTML splash` });
      continue;
    }
    const observations = [];
    for (const viewport of VIEWPORTS) {
      const ctx = await newContext(browser, { viewport });
      const seen = await pageProbe(ctx, origin, `${entry.route}${entry.route.includes('?') ? '&' : '?'}splash=force`, { waitAbsent: 450 });
      await ctx.close();
      observations.push({ viewport, seen: !!seen.probe?.seen, status: seen.status, errors: seen.errors, external: seen.external });
    }
    const has = observations.some(o => o.seen);
    if (!has) {
      rows.push({ ...base, class: 'SPLASH ABSENT', evidence: observations });
    } else {
      const ctx = await newContext(browser, { viewport: VIEWPORTS[0] });
      const skip = await pageProbe(ctx, origin, `${entry.route}${entry.route.includes('?') ? '&' : '?'}splash=skip`, { waitAbsent: 450 });
      await ctx.close();
      const skipped = !skip.probe?.seen;
      rows.push({ ...base, class: skipped ? 'SPLASH OK' : 'SPLASH BROKEN', evidence: skipped ? 'force showed and skip suppressed in fresh contexts' : 'SS7: ?splash=skip still painted the Made by Matt layer', observations });
    }
    if ((i + 1) % 25 === 0) console.log(`census ${i + 1}/${entries.length}`);
  }
  return rows;
}

async function controls(browser, origin) {
  const siteRoute = applied(SITE)[0];
  const lessonRoute = applied(LESSONS)[0];
  const assertions = [];
  const check = (condition, label, detail = '') => assertions.push({ pass: !!condition, label, detail });
  let ctx = await newContext(browser);
  const forceBaseline = await pageProbe(ctx, origin, `${lessonRoute}?splash=force`, { action: 'key', waitAbsent: 700 });
  await ctx.close();
  ctx = await newContext(browser);
  const first = await pageProbe(ctx, origin, lessonRoute, { action: 'none', waitAbsent: 700 });
  const firstKey = first.local;
  const second = await pageProbe(ctx, origin, siteRoute, { action: 'none', waitAbsent: 700 });
  await ctx.close();
  ctx = await newContext(browser);
  const skippedControl = await pageProbe(ctx, origin, `${siteRoute}?splash=skip`, { waitAbsent: 700 });
  await ctx.close();
  check(first.probe?.seen, 'SS1 fresh context shows');
  check(first.local && Math.abs(Number(first.local) - first.wall) <= 5000, 'SS1 timestamp written within five seconds', first.local);
  const addedKeys = (first.keys || []).filter(key => !(forceBaseline.keys || []).includes(key));
  check(addedKeys.length === 1 && addedKeys[0] === KEY, 'SS1 splash adds exactly the declared storage key', JSON.stringify({ force: forceBaseline.keys, shown: first.keys, added: addedKeys }));
  check(!second.probe?.seen && second.local === firstKey, 'SS2 second cross-repository route suppresses and leaves key unchanged');
  check(JSON.stringify(second.primaryRect) === JSON.stringify(skippedControl.primaryRect), 'SS5 suppressed and skip-control first geometry match');
  check(second.active?.id === second.primaryRect?.id && second.active?.tag === second.primaryRect?.tag && skippedControl.active?.id === skippedControl.primaryRect?.id && skippedControl.active?.tag === skippedControl.primaryRect?.tag, 'SS6 suppressed and skip-control focus land on the primary control', JSON.stringify({ suppressed: second.active, skip: skippedControl.active }));
  for (const [name, seed] of [['expired', Date.now() - 86400001], ['future', Date.now() + 604800000], ['banana', 'banana']]) {
    ctx = await newContext(browser, { seed }); const value = await pageProbe(ctx, origin, siteRoute, { waitAbsent: 700 }); await ctx.close();
    check(value.probe?.seen, `SS3 ${name} opens the window`);
    if (name === 'future') check(Number(value.local) <= Date.now() && Number(value.local) >= value.wall - 1000, 'SS3 future value is corrected', value.local);
    if (name === 'banana') check(value.errors.length === 0, 'SS3 invalid value has no console error', value.errors.join(' | '));
  }
  ctx = await newContext(browser, { throwWrite: true }); const failure = await pageProbe(ctx, origin, siteRoute, { waitAbsent: 700 }); await ctx.close();
  check(failure.probe?.seen && failure.session && failure.errors.length === 0, 'SS4 local write failure shows, boots and falls back to session', JSON.stringify({ session: failure.session, errors: failure.errors }));
  const fixed = Date.now() - 1000;
  ctx = await newContext(browser, { seed: fixed }); const forced = await pageProbe(ctx, origin, `${siteRoute}?splash=force`, { waitAbsent: 700 }); await ctx.close();
  check(forced.probe?.seen && forced.local === String(fixed), 'SS7 force shows without writing');
  ctx = await newContext(browser); const skipped = await pageProbe(ctx, origin, `${siteRoute}?splash=skip`, { waitAbsent: 700 }); await ctx.close();
  check(!skipped.probe?.seen && skipped.local === null, 'SS7 skip suppresses without writing');
  ctx = await newContext(browser, { reduced: true }); const reduced = await pageProbe(ctx, origin, siteRoute, { action: 'key', waitAbsent: 700 }); await ctx.close();
  check(reduced.probe?.seen && reduced.probe.last <= 500, 'SS8 reduced motion clears within 500 ms', String(reduced.probe?.last));
  check(reduced.local && Math.abs(Number(reduced.local) - reduced.wall) <= 5000, 'SS8 reduced motion still writes the daily timestamp', reduced.local);
  for (const viewport of VIEWPORTS) {
    for (const action of ['key', 'pointer', 'auto', 'timeout']) {
      ctx = await newContext(browser, { viewport });
      const result = await pageProbe(ctx, origin, `${siteRoute}?splash=force`, { action, waitAbsent: 700 });
      await ctx.close();
      const duration = result.probe?.first == null ? null : result.probe.last - result.probe.first;
      check(result.probe?.seen, `${action} path paints at ${viewport.width}x${viewport.height}`);
      check(duration !== null && duration >= 280, `${action} path stays visible at least 300 ms (two-frame tolerance)`, String(duration));
      check(!result.makerPresent && !result.anySplashPresent, `${action} path leaves no pointer or accessibility-tree overlay at ${viewport.width}x${viewport.height}`);
      check(result.active?.id === result.primaryRect?.id && result.active?.tag === result.primaryRect?.tag, `${action} path focuses the primary control at ${viewport.width}x${viewport.height}`, JSON.stringify({ active: result.active, primary: result.primaryRect }));
      check(result.errors.length === 0 && result.external.length === 0, `${action} path has zero error/external request`, result.errors.concat(result.external).join(' | '));
    }
  }
  const wayOut = await wayOutProbe(browser, origin, siteRoute, 'Enter');
  check(wayOut.reached && wayOut.tabs <= 30, 'focus way out is reachable within 30 Tab presses', JSON.stringify(wayOut));
  check(wayOut.navigated, 'Enter activates the focused way-out control', JSON.stringify(wayOut));
  check(wayOut.errors.length === 0 && wayOut.external.length === 0, 'way-out path has zero error/external request', wayOut.errors.concat(wayOut.external).join(' | '));
  // Positive control against the real stamped route: a second server strips
  // exactly that region and the presence predicate must turn red.
  const controlServer = await makeServer({ stripRoute: siteRoute });
  const controlOrigin = `http://127.0.0.1:${controlServer.address().port}`;
  ctx = await newContext(browser); const removed = await pageProbe(ctx, controlOrigin, `${siteRoute}?splash=force`, { waitAbsent: 700 }); await ctx.close();
  await new Promise(resolve => controlServer.close(resolve));
  check(!removed.probe?.seen, 'RL4 removal control turns the presence predicate red');
  return { siteRoute, lessonRoute, assertions, pass: assertions.every(a => a.pass) };
}

async function verify(browser, origin) {
  const routes = [...applied(SITE), ...applied(LESSONS)];
  const rows = [];
  for (let i = 0; i < routes.length; i += 1) {
    const route = routes[i], observations = [];
    for (const viewport of VIEWPORTS) {
      const ctx = await newContext(browser, { viewport });
      const result = await pageProbe(ctx, origin, `${route}${route.includes('?') ? '&' : '?'}splash=force`, { action: 'key', waitAbsent: 700 });
      await ctx.close();
      const duration = result.probe?.first == null ? null : result.probe.last - result.probe.first;
      observations.push({ viewport, seen: !!result.probe?.seen, duration, active: result.active, overflow: result.overflow, errors: result.errors, external: result.external });
    }
    const pass = observations.every(o => o.seen && o.duration >= 280 && o.overflow <= 0 && o.errors.length === 0 && o.external.length === 0 && ['A', 'BUTTON', 'MAIN', 'H1'].includes(o.active.tag));
    rows.push({ route, repository: routeRepo(route), class: pass ? 'SPLASH OK' : 'SPLASH BROKEN', observations });
    if ((i + 1) % 25 === 0) console.log(`verify ${i + 1}/${routes.length}`);
  }
  return rows;
}

fs.mkdirSync(path.dirname(REPORT), { recursive: true });
const server = await makeServer();
const origin = `http://127.0.0.1:${server.address().port}`;
let browser;
let payload;
try {
  browser = await chromium.launch({ headless: true });
  if (MODE === 'census') payload = { mode: MODE, site: SITE, lessons: LESSONS, rows: await census(browser, origin) };
  else if (MODE === 'controls') payload = { mode: MODE, site: SITE, lessons: LESSONS, controls: await controls(browser, origin) };
  else if (MODE === 'verify') payload = { mode: MODE, site: SITE, lessons: LESSONS, rows: await verify(browser, origin) };
  else throw new Error(`unknown mode: ${MODE}`);
} finally {
  if (browser) await browser.close();
  await new Promise(resolve => server.close(resolve));
}
payload.generatedAt = new Date().toISOString();
payload.generatorRegionSha256 = (() => {
  const source = fs.readFileSync(path.join(SITE, 'tools', 'render_maker_splash.py'), 'utf8');
  const hit = source.match(/JS = r'''([\s\S]*?)'''/);
  return hit ? require('node:crypto').createHash('sha256').update(hit[1]).digest('hex') : null;
})();
fs.writeFileSync(REPORT, JSON.stringify(payload, null, 2) + '\n');
if (MODE === 'controls') {
  for (const assertion of payload.controls.assertions) console.log(`${assertion.pass ? 'PASS' : 'FAIL'} ${assertion.label}${assertion.detail ? ` · ${assertion.detail}` : ''}`);
  console.log(`controls: ${payload.controls.assertions.filter(a => a.pass).length}/${payload.controls.assertions.length}`);
  process.exit(payload.controls.pass ? 0 : 1);
}
const rows = payload.rows;
const totals = Object.fromEntries([...new Set(rows.map(row => row.class))].sort().map(key => [key, rows.filter(row => row.class === key).length]));
console.log(JSON.stringify({ mode: MODE, routes: rows.length, totals, report: REPORT }, null, 2));
process.exit(MODE === 'verify' && rows.some(row => row.class !== 'SPLASH OK') ? 1 : 0);
