#!/usr/bin/env python3
"""Prove the maker-splash RECORD rules red, not just green.

tools/render_maker_splash.py stamps the MBM-MAKER-SPLASH region on the routes
declared in data/hud-coverage.json.  Three of its four classes are records
rather than stamps: `declined-with-reason`, `variant-retained-with-reason` and
`held-at-previous-region-with-reason` each say a route deliberately does NOT
carry the current region, and each costs the author something -- a reason, and
for a held route the digest of the bytes it keeps instead.

Those record rules had no firing control.  A stamp gate that reds when a
region is missing says nothing about whether a DECLINED route can quietly grow
one back, whether a reason can be deleted, or whether a held digest can drift;
each of those is a separate assertion, and an assertion that has never failed
is not evidence.

The second record is docs/play-q1/coverage.json, the derived per-route
coverage table that .github/workflows/splash-region-records.yml gates with
tools/play_splash_coverage.py --check --owner site.  That workflow runs a
--self-test for each of its other two gates and none for this one, which is
the gate that actually reads the regions.  Its --owner site narrowing is a
deliberate claim -- that a Lessons-side change cannot red a job this
repository could not fix -- and a claim about what a gate does NOT do needs a
control just as much as one about what it does.

Every case below is planted against a synthetic root, so the control never
depends on the estate's own ledger or coverage record being in any particular
state, and each part asserts its clean case first: a suite whose "red" cases
red because the fixture was broken all along proves nothing.

    python3 tools/verify_splash_region_record_controls.py
"""
from __future__ import annotations

import copy
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
TOOL = HERE / "render_maker_splash.py"
REGION_RE = re.compile(
    r"<!-- MBM-MAKER-SPLASH:BEGIN generated by tools/render_maker_splash\.py, do not edit by hand -->.*?"
    r"<!-- MBM-MAKER-SPLASH:END -->",
    re.DOTALL,
)

PAGE = "<!doctype html>\n<html><head><title>fixture</title></head><body>\n<main>fixture</main>\n</body></html>\n"

APPLIED = "/Games/Fixture_Applied.html"
DECLINED = "/Games/Fixture_Declined.html"
VARIANT = "/Games/Fixture_Variant.html"
HELD = "/Games/Fixture_Held.html"
ROUTES = (APPLIED, DECLINED, VARIANT, HELD)


def run(root: Path, mode: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(TOOL), "--root", str(root), mode],
        capture_output=True, text=True,
    )


def region_digest(path: Path) -> str:
    """The digest a held entry pins: the region's own bytes, newline-terminated,
    exactly as render_maker_splash.py recomputes them."""
    found = REGION_RE.findall(path.read_text(encoding="utf-8"))
    if len(found) != 1:
        raise SystemExit(f"fixture: expected one region in {path}, found {len(found)}")
    return hashlib.sha256(found[0].strip("\r\n").encode("utf-8") + b"\n").hexdigest()


def build(tmp: Path) -> dict:
    """A stamped fixture root, then a ledger that records three of its four
    routes.  The held digest is READ from the stamped bytes rather than typed,
    so the clean case cannot pass by coincidence."""
    for route in ROUTES:
        target = tmp / route.lstrip("/")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(PAGE, encoding="utf-8")
    ledger_path = tmp / "data" / "hud-coverage.json"
    ledger_path.parent.mkdir(parents=True, exist_ok=True)
    # Stamp every route first, so the held route has a real region to pin and
    # the declined and variant routes have one to be stripped of.
    ledger_path.write_text(json.dumps({"makerSplash": {
        "applied": list(ROUTES),
        "declined-with-reason": [],
        "variant-retained-with-reason": [],
    }}, indent=2) + "\n", encoding="utf-8")
    stamped = run(tmp, "--write")
    if stamped.returncode != 0:
        raise SystemExit("fixture: --write did not stamp the synthetic root\n" + stamped.stdout + stamped.stderr)
    held_sha = region_digest(tmp / HELD.lstrip("/"))
    for route in (DECLINED, VARIANT):
        target = tmp / route.lstrip("/")
        target.write_text(REGION_RE.sub("", target.read_text(encoding="utf-8"), count=1).replace("\n\n\n", "\n"), encoding="utf-8")
    return {"makerSplash": {
        "applied": [APPLIED],
        "declined-with-reason": [{"route": DECLINED, "reason": "fixture: declined for this control"}],
        "variant-retained-with-reason": [{"route": VARIANT, "reason": "fixture: variant retained for this control"}],
        "held-at-previous-region-with-reason": [
            {"route": HELD, "reason": "fixture: held for this control", "region_sha256": held_sha}
        ],
    }}


def write_ledger(root: Path, ledger: dict) -> None:
    (root / "data" / "hud-coverage.json").write_text(json.dumps(ledger, indent=2) + "\n", encoding="utf-8")


def regrow_region(root: Path, route: str, donor: str) -> None:
    """Put the current region back on a route whose record says it carries none."""
    target = root / route.lstrip("/")
    text = target.read_text(encoding="utf-8")
    at = text.index("<main>")
    target.write_text(text[:at] + donor + "\n" + text[at:], encoding="utf-8")


def part_a() -> int:
    """The ledger's record classes, through render_maker_splash.py --check."""
    failures: list[str] = []
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        clean = build(root)
        write_ledger(root, clean)
        donor = REGION_RE.findall((root / HELD.lstrip("/")).read_text(encoding="utf-8"))[0]

        baseline = run(root, "--check")
        if baseline.returncode != 0:
            print(baseline.stdout + baseline.stderr)
            print("FAIL clean fixture: the records gate reds on a correct root, so every case below is vacuous")
            return 1
        print("PASS clean: applied stamped, declined and variant bare, held digest matched")

        def case(name: str, mutate) -> None:
            snapshot = {route: (root / route.lstrip("/")).read_text(encoding="utf-8") for route in ROUTES}
            ledger = copy.deepcopy(clean)
            mutate(ledger)
            write_ledger(root, ledger)
            result = run(root, "--check")
            if result.returncode == 0:
                failures.append(name)
                print("FAIL " + name)
                print(result.stdout + result.stderr)
            else:
                print(f"PASS {name} (gate exit {result.returncode})")
            for route, text in snapshot.items():
                (root / route.lstrip("/")).write_text(text, encoding="utf-8")
            write_ledger(root, clean)

        case("a declined route that grows the region back is caught",
             lambda _: regrow_region(root, DECLINED, donor))
        case("a variant-retained route that grows the region back is caught",
             lambda _: regrow_region(root, VARIANT, donor))
        case("a held route whose pinned region drifts is caught",
             lambda _: regrow_region(root, HELD, donor))
        case("a declined route stripped of its reason is caught",
             lambda l: l["makerSplash"]["declined-with-reason"][0].__setitem__("reason", ""))
        case("a variant-retained route stripped of its reason is caught",
             lambda l: l["makerSplash"]["variant-retained-with-reason"][0].__setitem__("reason", ""))
        case("a held route stripped of its pinned digest is caught",
             lambda l: l["makerSplash"]["held-at-previous-region-with-reason"][0].pop("region_sha256"))
        case("a held digest that is not a sha256 is caught",
             lambda l: l["makerSplash"]["held-at-previous-region-with-reason"][0].__setitem__("region_sha256", "not-a-digest"))
        case("a route recorded in two classes at once is caught",
             lambda l: l["makerSplash"]["declined-with-reason"].append(
                 {"route": APPLIED, "reason": "fixture: also declined"}))

    print("")
    print(f"{8 - len(failures)} of 8 ledger-record controls fired; clean fixture green")
    for name in failures:
        print("  DID NOT FIRE  " + name)
    return 1 if failures else 0


COVERAGE = HERE / "play_splash_coverage.py"
SITE_ROUTE = "/fixturegame/"
LESSONS_ROUTE = "/Lessons/Games/Fixture_Shelf.html"


def coverage_run(tmp: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(COVERAGE), "--catalogue", str(tmp / "catalogue.json"),
         "--site", str(tmp / "site"), "--lessons", str(tmp / "lessons"), *args],
        capture_output=True, text=True,
    )


def build_coverage_fixture(tmp: Path) -> None:
    """Two routes, one per estate, both stamped by the real generator, then the
    record written by the writer under test. Nothing here is typed by hand."""
    site, lessons = tmp / "site", tmp / "lessons"
    (site / "tools").mkdir(parents=True)
    (site / "tools" / "render_maker_splash.py").write_bytes(TOOL.read_bytes())
    for root, route, ledger_route in ((site, SITE_ROUTE, SITE_ROUTE), (lessons, LESSONS_ROUTE, LESSONS_ROUTE)):
        rel = route[len("/Lessons/"):] if route.startswith("/Lessons/") else route.lstrip("/")
        target = root / (rel + "index.html" if route.endswith("/") else rel)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(PAGE, encoding="utf-8")
        ledger = root / "data" / "hud-coverage.json"
        ledger.parent.mkdir(parents=True, exist_ok=True)
        ledger.write_text(json.dumps({"makerSplash": {
            "applied": [{"route": ledger_route}],
            "declined-with-reason": [],
            "variant-retained-with-reason": [],
        }}, indent=1) + "\n", encoding="utf-8")
        stamped = run(root, "--write")
        if stamped.returncode != 0:
            raise SystemExit("fixture: --write did not stamp " + str(root) + "\n" + stamped.stdout + stamped.stderr)
    (tmp / "catalogue.json").write_text(json.dumps({
        "games": [{"route": SITE_ROUTE, "title": "Fixture Site Game"},
                  {"route": LESSONS_ROUTE, "title": "Fixture Shelf Game"}],
        "activities": [],
    }), encoding="utf-8")
    written = coverage_run(tmp, "--write", str(site / "docs/play-q1/coverage.json"))
    if written.returncode != 0:
        raise SystemExit("fixture: the coverage writer failed\n" + written.stdout + written.stderr)


def part_b() -> int:
    """The derived coverage record, through play_splash_coverage.py --check."""
    failures: list[str] = []
    with tempfile.TemporaryDirectory() as raw:
        tmp = Path(raw)
        build_coverage_fixture(tmp)
        site = tmp / "site"
        record = site / "docs/play-q1/coverage.json"
        site_page = site / "fixturegame/index.html"
        lessons_page = tmp / "lessons/Games/Fixture_Shelf.html"
        site_ledger = site / "data/hud-coverage.json"
        snapshot = {p: p.read_text(encoding="utf-8") for p in (record, site_page, lessons_page, site_ledger)}

        baseline = coverage_run(tmp, "--check", "--owner", "site")
        if baseline.returncode != 0:
            print(baseline.stdout + baseline.stderr)
            print("FAIL clean fixture: the coverage gate reds on a freshly written record")
            return 1
        print("PASS clean: the freshly written coverage record matches its own writer")

        def case(name: str, mutate, *args: str, expect_red: bool = True) -> None:
            mutate()
            result = coverage_run(tmp, "--check", *(args or ("--owner", "site")))
            red = result.returncode != 0
            if red != expect_red:
                failures.append(name)
                print("FAIL " + name)
                print(result.stdout + result.stderr)
            else:
                print(f"PASS {name} (gate exit {result.returncode})")
            for path, text in snapshot.items():
                path.write_text(text, encoding="utf-8")

        def drift(path: Path) -> None:
            text = path.read_text(encoding="utf-8")
            path.write_text(text.replace("<!-- MBM-MAKER-SPLASH:END -->", "<!-- x --><!-- MBM-MAKER-SPLASH:END -->", 1), encoding="utf-8")

        case("a Site route whose region drifts is caught", lambda: drift(site_page))
        case("a Site route whose file disappears is caught", lambda: site_page.unlink())
        case("a record whose generator digest is stale is caught",
             lambda: record.write_text(record.read_text().replace('"generatorRegionSha256": "', '"generatorRegionSha256": "0', 1), encoding="utf-8"))
        case("a Site route quietly undeclared in the ledger is caught",
             lambda: site_ledger.write_text(json.dumps({"makerSplash": {"applied": [], "declined-with-reason": [], "variant-retained-with-reason": []}}, indent=1) + "\n", encoding="utf-8"))
        case("a missing coverage record is caught", lambda: record.unlink())
        # The --owner site narrowing is a claim about what this gate does NOT do.
        # Both halves are asserted: a Lessons-side drift must not red the Site job,
        # and the same drift must red the unscoped run -- otherwise the narrowing
        # would be hiding a check that no longer works at all.
        case("a Lessons-side drift does not red the Site-owned scope", lambda: drift(lessons_page), expect_red=False)
        case("the same Lessons-side drift does red the unscoped run", lambda: drift(lessons_page), "--owner", "all")

    print("")
    print(f"{7 - len(failures)} of 7 coverage-record controls fired as expected; clean fixture green")
    for name in failures:
        print("  WRONG VERDICT  " + name)
    return 1 if failures else 0


def main() -> int:
    print("== the ledger's record classes ==")
    a = part_a()
    print("")
    print("== the derived coverage record ==")
    b = part_b()
    return 1 if (a or b) else 0


if __name__ == "__main__":
    raise SystemExit(main())
