#!/usr/bin/env node
/* Real-origin browser evidence for the generated Made by Matt splash.
 *
 * Modes:
 *   --mode=controls  SS1–SS8 plus the four dismissal paths and a removal control
 *   --mode=census    classify the canonical inventory before application
 *   --mode=verify    judge every applied route after application
 *   --mode=lesson-timing prove shown/suppressed slide timing and cross-route suppression
 *
 * The runner is intentionally serial.  Every route gets a fresh browser
 * context (RL14), and both viewports are measured rather than inferred.
 */
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const HERE = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_SITE = path.resolve(HERE, '..');
const arg = name => {
  const hit = process.argv.find(v => v.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : null;
};
const MODE = arg('mode') || 'controls';
const SCOPE = arg('scope') || 'both';
const SITE_ROUTE = arg('site-route');
const SECOND_ROUTE = arg('second-route');
if (!['both', 'site', 'lessons'].includes(SCOPE)) throw new Error(`unknown scope: ${SCOPE}`);
const SITE = path.resolve(arg('site-root') || DEFAULT_SITE);
const LESSONS = path.resolve(arg('lessons-root') || path.join(SITE, '_lessons'));
const REPORT = path.resolve(arg('report') || path.join(SITE, 'artifacts', `maker-splash-${MODE}.json`));
const KEY = 'mbm_splash_last';
const BEGIN = '<!-- MBM-MAKER-SPLASH:BEGIN generated by tools/render_maker_splash.py, do not edit by hand -->';
const END = '<!-- MBM-MAKER-SPLASH:END -->';
const REGION = new RegExp('(?:\\r?\\n)?' + escapeRegex(BEGIN) + '[\\s\\S]*?' + escapeRegex(END) + '(?:\\r?\\n)?');
const VIEWPORTS = [{ width: 390, height: 844 }, { width: 1280, height: 800 }];
const MIME = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.mjs': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8', '.svg': 'image/svg+xml', '.png': 'image/png', '.webp': 'image/webp', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.gif': 'image/gif', '.ico': 'image/x-icon', '.woff2': 'font/woff2', '.mp4': 'video/mp4', '.webm': 'video/webm' };

function escapeRegex(value) { return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
function readJson(file) { return JSON.parse(fs.readFileSync(file, 'utf8')); }
function routeFile(route) {
  const lessons = route.startsWith('/Lessons/');
  const root = lessons ? LESSONS : SITE;
  let rel = lessons ? route.slice('/Lessons/'.length) : route.replace(/^\//, '');
  let file = path.resolve(root, rel);
  if (route.endsWith('/')) file = path.join(file, 'index.html');
  if (file !== root && !file.startsWith(root + path.sep)) return null;
  return fs.existsSync(file) && fs.statSync(file).isFile() ? file : null;
}
function routeRepo(route) { return route.startsWith('/Lessons/') ? 'Lessons' : 'Site'; }
function routeGroup(entry) {
  if (entry.category === 'game') return entry.route.startsWith('/Lessons/') ? 'Lessons games' : 'root-level games';
  if (entry.category === 'lesson') return 'lessons';
  if (['resource', 'tool', 'app'].includes(entry.category)) return 'resources/tools/apps';
  return 'other interactive inventory';
}
function insertEvidence(file) {
  if (!file || path.extname(file).toLowerCase() !== '.html') return null;
  const source = fs.readFileSync(file, 'utf8');
  const m = source.match(/<body\b[^>]*>/i);
  return m ? `after <body> byte ${Buffer.byteLength(source.slice(0, m.index + m[0].length))}` : 'UNMEASURED: no <body>';
}
function applied(root) {
  const data = readJson(path.join(root, 'data', 'hud-coverage.json'));
  const list = data.makerSplash?.applied;
  if (!Array.isArray(list)) throw new Error(`${root}: makerSplash.applied is missing or is not a list`);
  return list.map(item => typeof item === 'string' ? item : item.route);
}

function makeServer({ stripRoute = null, slowReducedRoute = null, prematureWriteRoute = null } = {}) {
  const server = http.createServer((req, res) => {
    let pathname;
    try { pathname = decodeURIComponent(new URL(req.url, 'http://127.0.0.1').pathname); }
    catch { res.writeHead(400); return res.end('bad path'); }
    let file = routeFile(pathname);
    if (!file) {
      const root = pathname.startsWith('/Lessons/') ? LESSONS : SITE;
      const rel = pathname.startsWith('/Lessons/') ? pathname.slice(9) : pathname.slice(1);
      file = path.resolve(root, rel);
      if (file !== root && !file.startsWith(root + path.sep)) file = null;
      if (file && fs.existsSync(file) && fs.statSync(file).isDirectory()) file = path.join(file, 'index.html');
      if (!file || !fs.existsSync(file) || !fs.statSync(file).isFile()) file = null;
    }
    if (!file) { res.writeHead(404); return res.end('not found'); }
    const type = MIME[path.extname(file).toLowerCase()] || 'application/octet-stream';
    if (type.startsWith('text/html') && (stripRoute === pathname || slowReducedRoute === pathname || prematureWriteRoute === pathname)) {
      let body = fs.readFileSync(file, 'utf8');
      if (stripRoute === pathname) body = body.replace(REGION, '');
      if (slowReducedRoute === pathname) body = body
        .replace('animation-duration:.35s', 'animation-duration:.7s')
        .replace('reduced?450:2100', 'reduced?900:2100');
      if (prematureWriteRoute === pathname) body = body.replace(
        '(document.body||document.documentElement).appendChild(el);',
        '(document.body||document.documentElement).appendChild(el);if(MODE!=="force")writeNow();',
      );
      res.writeHead(200, { 'content-type': type, 'cache-control': 'no-store' });
      return res.end(body);
    }
    res.writeHead(200, { 'content-type': type, 'cache-control': 'no-store' });
    fs.createReadStream(file).pipe(res);
  });
  return new Promise((resolve, reject) => {
    server.once('error', reject);
    server.listen(0, '127.0.0.1', () => resolve(server));
  });
}

async function newContext(browser, options = {}) {
  const context = await browser.newContext({ viewport: options.viewport || VIEWPORTS[0], reducedMotion: options.reduced ? 'reduce' : 'no-preference', serviceWorkers: 'block' });
  if (options.seed !== undefined) await context.addInitScript(({ key, value }) => { try { localStorage.setItem(key, value); } catch {} }, { key: KEY, value: String(options.seed) });
  if (options.throwWrite) await context.addInitScript(key => {
    const original = Storage.prototype.setItem;
    Storage.prototype.setItem = function (k, v) {
      if (this === localStorage && k === key) throw new DOMException('blocked', 'QuotaExceededError');
      return original.call(this, k, v);
    };
  }, KEY);
  return context;
}

async function pageProbe(context, origin, route, { action = 'none', waitAbsent = 650, mutateUnderlay = false } = {}) {
  const page = await context.newPage();
  const errors = [], external = [];
  page.on('pageerror', error => errors.push(`pageerror: ${error.message}`));
  page.on('console', msg => { if (msg.type() === 'error') errors.push(`console: ${msg.text()}`); });
  page.on('request', request => {
    const url = request.url();
    if (!url.startsWith(origin) && !url.startsWith('data:') && !url.startsWith('blob:')) external.push(url);
  });
  await page.addInitScript(() => {
    window.__makerProbe = { seen: false, first: null, last: null, focus: null, geometry: null, contentFirst: null, contentGeometry: null, domContentLoaded: null, writeEvents: [] };
    try {
      const originalSetItem = Storage.prototype.setItem;
      Storage.prototype.setItem = function (key, value) {
        if (key === 'mbm_splash_last') {
          const el = document.querySelector('[data-mbm-maker-splash]');
          window.__makerProbe.writeEvents.push({
            t: performance.now(),
            value: String(value),
            makerPresent: !!el,
            ariaHidden: el?.getAttribute('aria-hidden') || null,
            pointerEvents: el ? getComputedStyle(el).pointerEvents : null,
          });
        }
        return originalSetItem.call(this, key, value);
      };
    } catch {}
    document.addEventListener('DOMContentLoaded', () => { window.__makerProbe.domContentLoaded = performance.now(); }, { once: true });
    addEventListener('focusin', event => {
      const p = window.__makerProbe;
      if (!p.focus && event.target && !event.target.closest?.('[data-mbm-maker-splash]')) p.focus = { t: performance.now(), id: event.target.id || '', tag: event.target.tagName || '' };
    });
    function observeAdded(root) {
      const candidates = [];
      if (root.nodeType === 1 && root.matches?.('[data-mbm-maker-splash],#mbmSplash,.mbm-splash,[data-mbm-splash]')) candidates.push(root);
      if (root.querySelectorAll) candidates.push(...root.querySelectorAll('[data-mbm-maker-splash],#mbmSplash,.mbm-splash,[data-mbm-splash]'));
      for (const el of candidates) {
        const label = `${el.getAttribute('aria-label') || ''} ${el.textContent || ''}`;
        if (/made\s+by\s+matt/i.test(label)) {
          const p = window.__makerProbe;
          p.seen = true;
          if (p.first === null) p.first = performance.now();
        }
      }
    }
    new MutationObserver(records => {
      for (const record of records) for (const node of record.addedNodes) observeAdded(node);
    }).observe(document, { childList: true, subtree: true });
    function sample() {
      const p = window.__makerProbe;
      const el = document.querySelector('[data-mbm-maker-splash],#mbmSplash,.mbm-splash,[data-mbm-splash]');
      if (el) {
        const rect = el.getBoundingClientRect(), css = getComputedStyle(el);
        const label = `${el.getAttribute('aria-label') || ''} ${el.textContent || ''}`;
        if (/made\s+by\s+matt/i.test(label) && rect.width > 0 && rect.height > 0 && css.display !== 'none' && css.visibility !== 'hidden') {
          p.seen = true; if (p.first === null) p.first = performance.now(); p.last = performance.now();
          p.geometry = { width: rect.width, height: rect.height, role: el.getAttribute('role'), modal: el.getAttribute('aria-modal'), z: css.zIndex };
        }
      }
      if (p.contentFirst === null) {
        const candidates = document.querySelectorAll('[data-slide].active,.slide.active,.slide.current,.slide:not([hidden]),main,[role="main"],canvas,h1');
        for (const candidate of candidates) {
          if (candidate.closest?.('[data-mbm-maker-splash]')) continue;
          const rect = candidate.getBoundingClientRect(), css = getComputedStyle(candidate);
          if (rect.width > 0 && rect.height > 0 && css.display !== 'none' && css.visibility !== 'hidden') {
            p.contentFirst = performance.now();
            p.contentGeometry = { x: rect.x, y: rect.y, width: rect.width, height: rect.height, id: candidate.id || '', tag: candidate.tagName };
            break;
          }
        }
      }
      requestAnimationFrame(sample);
    }
    requestAnimationFrame(sample);
  });
  const wall = Date.now();
  let response = null;
  try { response = await page.goto(origin + encodeURI(route), { waitUntil: 'commit', timeout: 30000 }); }
  catch (error) { errors.push(`navigation: ${error.message}`); }
  const maker = page.locator('[data-mbm-maker-splash]');
  const appeared = await maker.waitFor({ state: 'attached', timeout: waitAbsent }).then(() => true).catch(() => false);
  let shownUnderlayRect = null, visibleWallMs = null;
  if (appeared) {
    const visibleWallStart = Date.now();
    await page.waitForTimeout(20);
    await page.waitForLoadState('domcontentloaded', { timeout: 30000 }).catch(error => errors.push(`shown-domcontentloaded: ${error.message}`));
    shownUnderlayRect = await page.evaluate(mutate => {
      const selectors = ['[data-mbm-primary-start]','#startBtn','#playBtn','#beginBtn','#launchBtn','#openBtn','#start','a.skip','main button:not([disabled])','button:not([disabled])','main a[href]','a[href]'];
      const visible = el => { const css = getComputedStyle(el), box = el.getBoundingClientRect(); return !el.disabled && css.display !== 'none' && css.visibility !== 'hidden' && box.width > 0 && box.height > 0; };
      let primary = null;
      for (const selector of selectors) { primary = [...document.querySelectorAll(selector)].find(el => visible(el) && !el.closest('[data-mbm-maker-splash]')) || null; if (primary) break; }
      if (mutate && primary) { primary.style.setProperty('position', 'relative', 'important'); primary.style.setProperty('left', '7px', 'important'); }
      const rect = primary?.getBoundingClientRect();
      return rect ? { x: rect.x, y: rect.y, width: rect.width, height: rect.height, id: primary.id || '', tag: primary.tagName } : null;
    }, mutateUnderlay);
    if (action === 'key') await page.keyboard.press('a');
    else if (action === 'pointer') {
      const box = await maker.boundingBox();
      if (box) await page.mouse.click(box.x + box.width / 2, box.y + box.height / 2);
      else errors.push('pointer: splash had no rendered box');
    }
    else if (action === 'timeout') await maker.evaluate(el => { el.style.animation = 'none'; });
    if (action !== 'none') { await maker.waitFor({ state: 'detached', timeout: 2800 }).catch(() => {}); visibleWallMs = Date.now() - visibleWallStart; }
  }
  await page.waitForLoadState('domcontentloaded', { timeout: 30000 }).catch(error => errors.push(`domcontentloaded: ${error.message}`));
  const state = await page.evaluate(key => {
    const p = window.__makerProbe || {};
    const legacy = document.querySelector('#mbmSplash,.mbm-splash,[data-mbm-splash]');
    const selectors = ['[data-mbm-primary-start]','#startBtn','#playBtn','#beginBtn','#launchBtn','#openBtn','#start','a.skip','main button:not([disabled])','button:not([disabled])','main a[href]','a[href]'];
    const visible = el => { const css = getComputedStyle(el), box = el.getBoundingClientRect(); return !el.disabled && css.display !== 'none' && css.visibility !== 'hidden' && box.width > 0 && box.height > 0; };
    let primary = null;
    for (const selector of selectors) {
      primary = [...document.querySelectorAll(selector)].find(el => visible(el) && !el.closest('[data-mbm-maker-splash]')) || null;
      if (primary) break;
    }
    const rect = primary?.getBoundingClientRect();
    let local = null, session = null, keys = [];
    try { local = localStorage.getItem(key); keys = Object.keys(localStorage); } catch {}
    try { session = sessionStorage.getItem(key); } catch {}
    return {
      probe: p,
      makerPresent: !!document.querySelector('[data-mbm-maker-splash]'),
      anySplashPresent: !!legacy,
      legacyLabel: legacy ? `${legacy.getAttribute('aria-label') || ''} ${legacy.textContent || ''}`.trim().slice(0, 100) : '',
      local, session, keys,
      active: { id: document.activeElement?.id || '', tag: document.activeElement?.tagName || '' },
      primaryRect: rect ? { x: rect.x, y: rect.y, width: rect.width, height: rect.height, id: primary.id || '', tag: primary.tagName } : null,
      overflow: document.documentElement.scrollWidth - document.documentElement.clientWidth,
      ready: document.readyState,
    };
  }, KEY).catch(error => ({ probe: {}, error: error.message }));
  const result = { ...state, appeared, wall, shownUnderlayRect, visibleWallMs, status: response?.status() ?? null, finalUrl: page.url(), errors, external };
  await page.close();
  return result;
}

function writesOnlyAfterDismissal(result) {
  const writes = result.probe?.writeEvents || [];
  return writes.length > 0 && writes.every(write => write.ariaHidden === 'true' && write.pointerEvents === 'none');
}

async function wayOutProbe(browser, origin, route, activation, { disableWayOut = false } = {}) {
  const context = await newContext(browser);
  const page = await context.newPage();
  const errors = [], external = [];
  page.on('pageerror', error => errors.push(`pageerror: ${error.message}`));
  page.on('console', msg => { if (msg.type() === 'error') errors.push(`console: ${msg.text()}`); });
  page.on('request', request => {
    const url = request.url();
    if (!url.startsWith(origin) && !url.startsWith('data:') && !url.startsWith('blob:')) external.push(url);
  });
  await page.goto(origin + encodeURI(`${route}?splash=force`), { waitUntil: 'commit', timeout: 30000 });
  const maker = page.locator('[data-mbm-maker-splash]');
  const attached = await maker.waitFor({ state: 'attached', timeout: 1000 }).then(() => true).catch(() => false);
  if (!attached) {
    await context.close();
    return { activation, tabs: 31, reached: false, before: page.url(), after: page.url(), navigated: false, errors: errors.concat('maker splash was not observed before DOMContentLoaded'), external };
  }
  await page.keyboard.press('Tab');
  await maker.waitFor({ state: 'detached', timeout: 2800 });
  await page.waitForLoadState('domcontentloaded', { timeout: 30000 });
  if (disableWayOut) await page.evaluate(() => {
    const wayOut = document.querySelector('#mbmexit-back,#mbmhud-back');
    if (wayOut) { wayOut.id = 'mbm-way-out-disabled-control'; wayOut.tabIndex = -1; }
  });
  let tabs = 0;
  for (; tabs <= 30; tabs += 1) {
    if (await page.evaluate(() => document.activeElement?.matches?.('#mbmexit-back,#mbmhud-back'))) break;
    await page.keyboard.press('Tab');
  }
  const activeId = await page.evaluate(() => document.activeElement?.id || '');
  const reached = tabs <= 30 && await page.evaluate(() => document.activeElement?.matches?.('#mbmexit-back,#mbmhud-back'));
  const before = page.url();
  const preActivationErrors = errors.slice(), preActivationExternal = external.slice();
  if (reached) await page.keyboard.press(activation);
  await page.waitForTimeout(300);
  const after = page.url();
  await context.close();
  return { activation, tabs, reached, activeId, before, after, navigated: after !== before, errors: preActivationErrors, external: preActivationExternal };
}

async function reducedMotionProbe(browser, origin, route) {
  const context = await newContext(browser, { reduced: true });
  await context.addInitScript(() => {
    window.__mbmReducedProbe = {
      attached: false,
      attachedAt: null,
      clearedAt: null,
      detachedAt: null,
      started: false,
      endElapsed: null,
      endAt: null,
    };
    document.addEventListener('animationstart', event => {
      if (event.animationName !== 'mbmSplash' || !event.target?.matches?.('[data-mbm-maker-splash]')) return;
      window.__mbmReducedProbe.started = true;
    }, true);
    document.addEventListener('animationend', event => {
      if (event.animationName !== 'mbmSplash' || !event.target?.matches?.('[data-mbm-maker-splash]')) return;
      window.__mbmReducedProbe.endElapsed = event.elapsedTime * 1000;
      window.__mbmReducedProbe.endAt = performance.now();
    }, true);
    new MutationObserver(records => {
      const probe = window.__mbmReducedProbe;
      const recordClearance = el => {
        if (!el || !probe.attached || probe.clearedAt !== null) return;
        const css = getComputedStyle(el);
        if (el.getAttribute('aria-hidden') === 'true' || el.inert || css.visibility === 'hidden' || css.pointerEvents === 'none') {
          probe.clearedAt = performance.now();
        }
      };
      for (const record of records) {
        if (record.type === 'attributes' && record.target.matches?.('[data-mbm-maker-splash]')) recordClearance(record.target);
        for (const node of record.addedNodes) {
          const el = node.nodeType === 1 && node.matches?.('[data-mbm-maker-splash]') ? node : node.querySelector?.('[data-mbm-maker-splash]');
          if (!el || probe.attached) continue;
          probe.attached = true;
          probe.attachedAt = performance.now();
          recordClearance(el);
        }
        for (const node of record.removedNodes) {
          const removed = node.nodeType === 1 && node.matches?.('[data-mbm-maker-splash]') ? node : node.querySelector?.('[data-mbm-maker-splash]');
          if (!removed || !probe.attached || probe.detachedAt !== null) continue;
          probe.detachedAt = performance.now();
          if (probe.clearedAt === null) probe.clearedAt = probe.detachedAt;
        }
      }
    }).observe(document, { childList: true, subtree: true, attributes: true, attributeFilter: ['class', 'style', 'aria-hidden', 'inert'] });
  });
  const page = await context.newPage(), errors = [];
  page.on('pageerror', error => errors.push(`pageerror: ${error.message}`));
  page.on('console', msg => { if (msg.type() === 'error') errors.push(`console: ${msg.text()}`); });
  const wall = Date.now();
  await page.goto(origin + encodeURI(route), { waitUntil: 'commit', timeout: 30000 });
  await page.waitForTimeout(850);
  const probe = await page.evaluate(() => window.__mbmReducedProbe);
  const final = await page.locator('[data-mbm-maker-splash]').evaluate(el => { const css = getComputedStyle(el); return { visibility: css.visibility, pointerEvents: css.pointerEvents }; }).catch(() => ({ visibility: 'detached', pointerEvents: 'none' }));
  await page.waitForLoadState('domcontentloaded', { timeout: 30000 }).catch(error => errors.push(`domcontentloaded: ${error.message}`));
  const local = await page.evaluate(key => { try { return localStorage.getItem(key); } catch { return null; } }, KEY);
  await context.close();
  return { wall, local, errors, probe, final };
}

function reducedMotionClearanceElapsed(result) {
  const attachedAt = result.probe?.attachedAt;
  const clearedAt = result.probe?.clearedAt;
  return Number.isFinite(attachedAt) && Number.isFinite(clearedAt) ? clearedAt - attachedAt : null;
}

function reducedMotionObservedElapsed(result) {
  return Number.isFinite(result.probe?.endElapsed) ? result.probe.endElapsed : reducedMotionClearanceElapsed(result);
}

function reducedMotionClearsWithinDeadline(result) {
  const elapsed = reducedMotionObservedElapsed(result);
  return result.probe?.attached === true && elapsed >= 300 && elapsed <= 500 && result.final.pointerEvents === 'none';
}

async function census(browser, origin) {
  const index = readJson(path.join(SITE, 'data', 'mbm-search-index.json'));
  const entries = index.entries || [];
  const rows = [];
  for (let i = 0; i < entries.length; i += 1) {
    const entry = entries[i], file = routeFile(entry.route), ext = file ? path.extname(file).toLowerCase() : path.extname(entry.route).toLowerCase();
    const base = { route: entry.route, repository: routeRepo(entry.route), group: routeGroup(entry), category: entry.category, fileBytes: file ? fs.statSync(file).size : null, insertionPoint: file && ext === '.html' ? insertEvidence(file) : null };
    if (!file) {
      rows.push({ ...base, class: 'UNMEASURED', evidence: entry.route.startsWith('/Matt-s-Apps-/') ? 'route belongs to the out-of-scope Apps repository' : 'inventory route has no file in the three authorised repositories' });
      continue;
    }
    if (ext !== '.html') {
      rows.push({ ...base, class: 'SPLASH DECLINED', evidence: `${ext || 'non-HTML'} contract cannot host an HTML splash` });
      continue;
    }
    const observations = [];
    for (const viewport of VIEWPORTS) {
      const ctx = await newContext(browser, { viewport });
      const seen = await pageProbe(ctx, origin, `${entry.route}${entry.route.includes('?') ? '&' : '?'}splash=force`, { waitAbsent: 450 });
      await ctx.close();
      observations.push({ viewport, seen: !!seen.probe?.seen, status: seen.status, errors: seen.errors, external: seen.external });
    }
    const has = observations.some(o => o.seen);
    if (!has) {
      rows.push({ ...base, class: 'SPLASH ABSENT', evidence: observations });
    } else {
      const ctx = await newContext(browser, { viewport: VIEWPORTS[0] });
      const skip = await pageProbe(ctx, origin, `${entry.route}${entry.route.includes('?') ? '&' : '?'}splash=skip`, { waitAbsent: 450 });
      await ctx.close();
      const skipped = !skip.probe?.seen;
      rows.push({ ...base, class: skipped ? 'SPLASH OK' : 'SPLASH BROKEN', evidence: skipped ? 'force showed and skip suppressed in fresh contexts' : 'SS7: ?splash=skip still painted the Made by Matt layer', observations });
    }
    if ((i + 1) % 25 === 0) console.log(`census ${i + 1}/${entries.length}`);
  }
  return rows;
}

async function controls(browser, origin) {
  const siteRoutes = applied(SITE);
  const lessonRoutes = SCOPE === 'site' ? [] : applied(LESSONS);
  if (SITE_ROUTE && !siteRoutes.includes(SITE_ROUTE)) throw new Error(`--site-route is not declared applied: ${SITE_ROUTE}`);
  const siteRoute = SITE_ROUTE || siteRoutes[0];
  const defaultSecond = SCOPE === 'site' ? siteRoutes.find(route => route !== siteRoute) : lessonRoutes[0];
  if (SECOND_ROUTE) {
    const declared = SCOPE === 'site' ? siteRoutes : [...siteRoutes, ...lessonRoutes];
    if (!declared.includes(SECOND_ROUTE)) throw new Error(`--second-route is not declared applied: ${SECOND_ROUTE}`);
  }
  const lessonRoute = SECOND_ROUTE || defaultSecond;
  if (!siteRoute || !lessonRoute || siteRoute === lessonRoute) throw new Error('controls require two distinct declared applied routes');
  const firstRoute = SCOPE === 'site' ? siteRoute : lessonRoute;
  const secondRoute = SCOPE === 'site' ? lessonRoute : siteRoute;
  const reducedRoute = siteRoute;
  const assertions = [];
  const check = (condition, label, detail = '') => assertions.push({ pass: !!condition, label, detail });
  let ctx = await newContext(browser);
  const forceBaseline = await pageProbe(ctx, origin, `${firstRoute}?splash=force`, { action: 'key', waitAbsent: 700 });
  await ctx.close();
  ctx = await newContext(browser);
  const first = await pageProbe(ctx, origin, firstRoute, { action: 'key', waitAbsent: 700 });
  const firstKey = first.local;
  const second = await pageProbe(ctx, origin, secondRoute, { action: 'none', waitAbsent: 700 });
  const suppressedSite = SCOPE === 'site'
    ? await pageProbe(ctx, origin, siteRoute, { action: 'none', waitAbsent: 700 })
    : second;
  await ctx.close();
  ctx = await newContext(browser);
  const skippedControl = await pageProbe(ctx, origin, `${siteRoute}?splash=skip`, { waitAbsent: 700 });
  await ctx.close();
  check(first.probe?.seen, 'SS1 fresh context shows');
  check(first.local && Math.abs(Number(first.local) - first.wall) <= 5000, 'SS1 timestamp written within five seconds of a valid dismissal', first.local);
  check(writesOnlyAfterDismissal(first), 'SS1 suppression is written only after the splash becomes inert and hidden', JSON.stringify(first.probe?.writeEvents || []));
  const addedKeys = (first.keys || []).filter(key => !(forceBaseline.keys || []).includes(key));
  check(addedKeys.length === 1 && addedKeys[0] === KEY, 'SS1 splash adds exactly the declared storage key', JSON.stringify({ force: forceBaseline.keys, shown: first.keys, added: addedKeys }));
  check(!second.probe?.seen && second.local === firstKey,
    SCOPE === 'both' ? 'SS2 second cross-repository route suppresses and leaves key unchanged' : 'SS2 second declared route suppresses and leaves key unchanged');
  check(JSON.stringify(suppressedSite.primaryRect) === JSON.stringify(skippedControl.primaryRect), 'SS5 suppressed and skip-control first geometry match');
  check(suppressedSite.active?.id === suppressedSite.primaryRect?.id && suppressedSite.active?.tag === suppressedSite.primaryRect?.tag && skippedControl.active?.id === skippedControl.primaryRect?.id && skippedControl.active?.tag === skippedControl.primaryRect?.tag, 'SS6 suppressed and skip-control focus land on the primary control', JSON.stringify({ suppressed: suppressedSite.active, skip: skippedControl.active }));
  for (const [name, seed] of [['expired', Date.now() - 86400001], ['future', Date.now() + 604800000], ['banana', 'banana']]) {
    ctx = await newContext(browser, { seed }); const value = await pageProbe(ctx, origin, siteRoute, { action: 'key', waitAbsent: 700 }); await ctx.close();
    check(value.probe?.seen, `SS3 ${name} opens the window`);
    check(writesOnlyAfterDismissal(value), `SS3 ${name} is corrected only after a valid dismissal`, JSON.stringify(value.probe?.writeEvents || []));
    if (name === 'future') check(Number(value.local) <= Date.now() && Number(value.local) >= value.wall - 1000, 'SS3 future value is corrected', value.local);
    if (name === 'banana') check(value.errors.length === 0, 'SS3 invalid value has no console error', value.errors.join(' | '));
  }
  ctx = await newContext(browser, { throwWrite: true }); const failure = await pageProbe(ctx, origin, siteRoute, { action: 'key', waitAbsent: 700 }); await ctx.close();
  check(failure.probe?.seen && failure.session && failure.errors.length === 0, 'SS4 local write failure shows, boots and falls back to session', JSON.stringify({ session: failure.session, errors: failure.errors }));
  const fixed = Date.now() - 1000;
  ctx = await newContext(browser, { seed: fixed }); const forced = await pageProbe(ctx, origin, `${siteRoute}?splash=force`, { action: 'key', waitAbsent: 700 }); await ctx.close();
  check(forced.probe?.seen && forced.local === String(fixed), 'SS7 force shows without writing');
  ctx = await newContext(browser); const skipped = await pageProbe(ctx, origin, `${siteRoute}?splash=skip`, { waitAbsent: 700 }); await ctx.close();
  check(!skipped.probe?.seen && skipped.local === null, 'SS7 skip suppresses without writing');
  check(JSON.stringify(forced.shownUnderlayRect) === JSON.stringify(skippedControl.primaryRect),
    'SS5 shown and suppressed first-paint primary geometry match', JSON.stringify({ shown: forced.shownUnderlayRect, suppressed: skippedControl.primaryRect }));
  ctx = await newContext(browser);
  const shifted = await pageProbe(ctx, origin, `${siteRoute}?splash=force`, { action: 'key', waitAbsent: 700, mutateUnderlay: true }); await ctx.close();
  check(JSON.stringify(shifted.shownUnderlayRect) !== JSON.stringify(skippedControl.primaryRect),
    'RL4 first-paint geometry mutation control turns the equality predicate red', JSON.stringify({ shifted: shifted.shownUnderlayRect, control: skippedControl.primaryRect }));
  check(forced.probe?.focus?.t != null && skippedControl.probe?.focus?.t != null,
    'time-to-interactive is measured with the splash shown and suppressed', JSON.stringify({ shownMs: forced.probe?.focus?.t, suppressedMs: skippedControl.probe?.focus?.t }));
  check(forced.probe?.focus?.t <= (forced.probe?.last ?? 0) + 350,
    'shown time-to-interactive does not extend beyond the visible splash', JSON.stringify({ interactiveMs: forced.probe?.focus?.t, splashLastMs: forced.probe?.last }));
  const reduced = await reducedMotionProbe(browser, origin, reducedRoute);
  check(reducedMotionClearsWithinDeadline(reduced), 'SS8 reduced motion paints and clears within 500 ms', JSON.stringify(reduced));
  check(reduced.local && Math.abs(Number(reduced.local) - reduced.wall) <= 5000, 'SS8 reduced motion still writes the daily timestamp', reduced.local);
  const slowServer = await makeServer({ slowReducedRoute: reducedRoute });
  const slowOrigin = `http://127.0.0.1:${slowServer.address().port}`;
  const slowReduced = await reducedMotionProbe(browser, slowOrigin, reducedRoute);
  await new Promise(resolve => slowServer.close(resolve));
  const slowObservedElapsed = reducedMotionObservedElapsed(slowReduced);
  const slowMissedDeadline = Number.isFinite(slowObservedElapsed)
    ? slowObservedElapsed > 500
    : slowReduced.final.pointerEvents !== 'none';
  check(slowReduced.probe?.attached && slowMissedDeadline && !reducedMotionClearsWithinDeadline(slowReduced),
    'RL4 reduced-motion slow-animation control turns the clearance predicate red', JSON.stringify(slowReduced));
  for (const viewport of VIEWPORTS) {
    for (const action of ['key', 'pointer', 'auto', 'timeout']) {
      ctx = await newContext(browser, { viewport });
      const result = await pageProbe(ctx, origin, `${siteRoute}?splash=force`, { action, waitAbsent: 700 });
      await ctx.close();
      const duration = result.probe?.first == null ? null : result.probe.last - result.probe.first;
      check(result.probe?.seen, `${action} path paints at ${viewport.width}x${viewport.height}`);
      check(duration !== null && duration >= 280, `${action} path stays visible at least 300 ms (two-frame tolerance)`, String(duration));
      check(!result.makerPresent && !result.anySplashPresent, `${action} path leaves no pointer or accessibility-tree overlay at ${viewport.width}x${viewport.height}`);
      check(result.active?.id === result.primaryRect?.id && result.active?.tag === result.primaryRect?.tag, `${action} path focuses the primary control at ${viewport.width}x${viewport.height}`, JSON.stringify({ active: result.active, primary: result.primaryRect }));
      check(result.errors.length === 0 && result.external.length === 0, `${action} path has zero error/external request`, result.errors.concat(result.external).join(' | '));
    }
  }
  const wayOut = await wayOutProbe(browser, origin, siteRoute, 'Enter');
  check(wayOut.reached && wayOut.tabs <= 30, 'focus way out is reachable within 30 Tab presses', JSON.stringify(wayOut));
  check(wayOut.navigated, 'Enter activates the focused way-out control', JSON.stringify(wayOut));
  check(wayOut.errors.length === 0 && wayOut.external.length === 0, 'way-out path has zero error/external request', wayOut.errors.concat(wayOut.external).join(' | '));
  const disabledWayOut = await wayOutProbe(browser, origin, siteRoute, 'Enter', { disableWayOut: true });
  check(!disabledWayOut.reached && !disabledWayOut.navigated, 'RL4 disabled-way-out control turns reach and activation red', JSON.stringify(disabledWayOut));
  // Positive control against the real stamped route: a second server strips
  // exactly that region and the presence predicate must turn red.
  const controlServer = await makeServer({ stripRoute: siteRoute });
  const controlOrigin = `http://127.0.0.1:${controlServer.address().port}`;
  ctx = await newContext(browser); const removed = await pageProbe(ctx, controlOrigin, `${siteRoute}?splash=force`, { waitAbsent: 700 }); await ctx.close();
  await new Promise(resolve => controlServer.close(resolve));
  check(!removed.probe?.seen, 'RL4 removal control turns the presence predicate red');
  const prematureServer = await makeServer({ prematureWriteRoute: siteRoute });
  const prematureOrigin = `http://127.0.0.1:${prematureServer.address().port}`;
  ctx = await newContext(browser); const premature = await pageProbe(ctx, prematureOrigin, siteRoute, { action: 'key', waitAbsent: 700 }); await ctx.close();
  await new Promise(resolve => prematureServer.close(resolve));
  check(!writesOnlyAfterDismissal(premature), 'RL4 premature-write control turns the dismissal-only predicate red', JSON.stringify(premature.probe?.writeEvents || []));
  return { siteRoute, lessonRoute, assertions, pass: assertions.every(a => a.pass) };
}

function addedFrom(candidate = [], baseline = []) {
  const remaining = [...baseline];
  return candidate.filter(value => {
    const at = remaining.indexOf(value);
    if (at < 0) return true;
    remaining.splice(at, 1);
    return false;
  });
}

function sameGeometry(a, b) {
  if (!a || !b || a.id !== b.id || a.tag !== b.tag) return false;
  return ['x', 'y', 'width', 'height'].every(key => Math.abs(a[key] - b[key]) <= 1);
}

async function verify(browser, origin) {
  const routes = [
    ...(SCOPE === 'lessons' ? [] : applied(SITE)),
    ...(SCOPE === 'site' ? [] : applied(LESSONS)),
  ];
  const rows = [];
  for (let i = 0; i < routes.length; i += 1) {
    const route = routes[i], observations = [];
    for (const viewport of VIEWPORTS) {
      const ctx = await newContext(browser, { viewport });
      const result = await pageProbe(ctx, origin, `${route}${route.includes('?') ? '&' : '?'}splash=force`, { action: 'key', waitAbsent: 700 });
      await ctx.close();
      const skipContext = await newContext(browser, { viewport });
      const skipped = await pageProbe(skipContext, origin, `${route}${route.includes('?') ? '&' : '?'}splash=skip`, { waitAbsent: 700 });
      await skipContext.close();
      const duration = result.probe?.first == null ? null : result.probe.last - result.probe.first;
      const addedErrors = addedFrom(result.errors, skipped.errors);
      const addedExternal = addedFrom(result.external, skipped.external);
      observations.push({ viewport, seen: !!result.probe?.seen, duration, active: result.active, primary: result.primaryRect,
        suppressedSeen: !!skipped.probe?.seen, suppressedActive: skipped.active, suppressedPrimary: skipped.primaryRect,
        firstPaintGeometryMatch: sameGeometry(result.probe?.contentGeometry, skipped.probe?.contentGeometry),
        overflowDelta: result.overflow - skipped.overflow, addedErrors, addedExternal,
        baselineErrors: skipped.errors, baselineExternal: skipped.external });
    }
    const wayOut = await wayOutProbe(browser, origin, route, 'Enter');
    const pass = observations.every(o => o.seen && o.duration >= 280 && !o.suppressedSeen && o.firstPaintGeometryMatch && o.overflowDelta <= 0 &&
      o.addedErrors.length === 0 && o.addedExternal.length === 0 && o.active.id === o.primary?.id && o.active.tag === o.primary?.tag &&
      o.suppressedActive.id === o.suppressedPrimary?.id && o.suppressedActive.tag === o.suppressedPrimary?.tag) &&
      wayOut.reached && wayOut.tabs <= 30 && wayOut.navigated && wayOut.errors.length === 0 && wayOut.external.length === 0;
    rows.push({ route, repository: routeRepo(route), class: pass ? 'SPLASH OK' : 'SPLASH BROKEN', observations, wayOut });
    if ((i + 1) % 25 === 0) console.log(`verify ${i + 1}/${routes.length}`);
  }
  return rows;
}

function distribution(values) {
  const clean = values.filter(Number.isFinite).sort((a, b) => a - b);
  if (!clean.length) return { count: 0, median: null, min: null, max: null, spread: null };
  const middle = Math.floor(clean.length / 2);
  const median = clean.length % 2 ? clean[middle] : (clean[middle - 1] + clean[middle]) / 2;
  return { count: clean.length, median, min: clean[0], max: clean.at(-1), spread: clean.at(-1) - clean[0] };
}

async function lessonTiming(browser, origin) {
  const indexPath = path.join(SITE, 'data', 'mbm-search-index.json');
  if (!fs.existsSync(indexPath)) throw new Error(`lesson timing requires the canonical inventory at ${indexPath}`);
  const declared = new Set(applied(LESSONS));
  const routes = (readJson(indexPath).entries || [])
    .filter(entry => entry.category === 'lesson' && entry.route.startsWith('/Lessons/') && declared.has(entry.route))
    .map(entry => entry.route);
  if (!routes.length) throw new Error('lesson timing found no declared lesson routes');
  const rows = [];
  for (let i = 0; i < routes.length; i += 1) {
    const route = routes[i], nextRoute = routes[(i + 1) % routes.length];
    const context = await newContext(browser, { viewport: VIEWPORTS[0] });
    const shown = await pageProbe(context, origin, route, { action: 'key', waitAbsent: 700 });
    const written = shown.local;
    const second = await pageProbe(context, origin, nextRoute, { waitAbsent: 700 });
    await context.close();
    const skipContext = await newContext(browser, { viewport: VIEWPORTS[0] });
    const skipped = await pageProbe(skipContext, origin, `${route}?splash=skip`, { waitAbsent: 700 });
    await skipContext.close();
    const duration = shown.probe?.first == null ? null : shown.probe.last - shown.probe.first;
    const shownSlide = shown.probe?.contentFirst;
    const suppressedSlide = skipped.probe?.contentFirst;
    const delay = Number.isFinite(shownSlide) && Number.isFinite(suppressedSlide) ? shownSlide - suppressedSlide : null;
    const pass = !!shown.probe?.seen && duration >= 280 && Number.isFinite(shownSlide) && shownSlide <= shown.probe.last + 250 &&
      !second.probe?.seen && second.local === written && !skipped.probe?.seen && skipped.local === null;
    rows.push({ route, secondRoute: nextRoute, class: pass ? 'LESSON TIMING OK' : 'LESSON TIMING BROKEN',
      shown: { slideMs: shownSlide, interactiveMs: shown.probe?.focus?.t ?? null, splashDurationMs: duration, splashLastMs: shown.probe?.last ?? null },
      suppressed: { slideMs: suppressedSlide, interactiveMs: skipped.probe?.focus?.t ?? null },
      delayMs: delay, secondRouteSuppressed: !second.probe?.seen, keyUnchanged: second.local === written });
    if ((i + 1) % 25 === 0) console.log(`lesson timing ${i + 1}/${routes.length}`);
  }
  const controlServer = await makeServer({ stripRoute: routes[0] });
  const controlOrigin = `http://127.0.0.1:${controlServer.address().port}`;
  const controlContext = await newContext(browser, { viewport: VIEWPORTS[0] });
  const removed = await pageProbe(controlContext, controlOrigin, `${routes[0]}?splash=force`, { waitAbsent: 700 });
  await controlContext.close();
  await new Promise(resolve => controlServer.close(resolve));
  return {
    rows,
    removalControlRed: !removed.probe?.seen,
    distributions: {
      shownSlideMs: distribution(rows.map(row => row.shown.slideMs)),
      suppressedSlideMs: distribution(rows.map(row => row.suppressed.slideMs)),
      shownInteractiveMs: distribution(rows.map(row => row.shown.interactiveMs)),
      suppressedInteractiveMs: distribution(rows.map(row => row.suppressed.interactiveMs)),
      splashDurationMs: distribution(rows.map(row => row.shown.splashDurationMs)),
      slideDelayMs: distribution(rows.map(row => row.delayMs)),
    },
  };
}

fs.mkdirSync(path.dirname(REPORT), { recursive: true });
const server = await makeServer();
const origin = `http://127.0.0.1:${server.address().port}`;
let browser;
let payload;
try {
  browser = await chromium.launch({ headless: true });
  if (MODE === 'census') payload = { mode: MODE, site: SITE, lessons: LESSONS, rows: await census(browser, origin) };
  else if (MODE === 'controls') payload = { mode: MODE, site: SITE, lessons: LESSONS, controls: await controls(browser, origin) };
  else if (MODE === 'verify') payload = { mode: MODE, scope: SCOPE, site: SITE, lessons: LESSONS, rows: await verify(browser, origin) };
  else if (MODE === 'lesson-timing') payload = { mode: MODE, site: SITE, lessons: LESSONS, ...(await lessonTiming(browser, origin)) };
  else throw new Error(`unknown mode: ${MODE}`);
} finally {
  if (browser) await browser.close();
  await new Promise(resolve => server.close(resolve));
}
payload.generatedAt = new Date().toISOString();
payload.generatorRegionSha256 = (() => {
  const source = fs.readFileSync(path.join(SITE, 'tools', 'render_maker_splash.py'), 'utf8');
  const hit = source.match(/JS = r'''([\s\S]*?)'''/);
  return hit ? require('node:crypto').createHash('sha256').update(hit[1]).digest('hex') : null;
})();
fs.writeFileSync(REPORT, JSON.stringify(payload, null, 2) + '\n');
if (MODE === 'controls') {
  for (const assertion of payload.controls.assertions) console.log(`${assertion.pass ? 'PASS' : 'FAIL'} ${assertion.label}${assertion.detail ? ` · ${assertion.detail}` : ''}`);
  console.log(`controls: ${payload.controls.assertions.filter(a => a.pass).length}/${payload.controls.assertions.length}`);
  process.exit(payload.controls.pass ? 0 : 1);
}
if (MODE === 'lesson-timing') {
  const broken = payload.rows.filter(row => row.class !== 'LESSON TIMING OK');
  console.log(JSON.stringify({ mode: MODE, routes: payload.rows.length, broken: broken.length, removalControlRed: payload.removalControlRed, distributions: payload.distributions, report: REPORT }, null, 2));
  process.exit(broken.length || !payload.removalControlRed ? 1 : 0);
}
const rows = payload.rows;
const totals = Object.fromEntries([...new Set(rows.map(row => row.class))].sort().map(key => [key, rows.filter(row => row.class === key).length]));
const broken = rows.filter(row => row.class !== 'SPLASH OK');
console.log(JSON.stringify({ mode: MODE, routes: rows.length, totals, broken, report: REPORT }, null, 2));
process.exit(MODE === 'verify' && rows.some(row => row.class !== 'SPLASH OK') ? 1 : 0);
